### ISSUE TITLE
Confusing CLI output after CREATE statement 

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#1032]
If you run this query on the example database in the documentation, you add 4 relationships (from Zhang to every other User node including from Zhang to Zhang). However the CLI output says 0 tuples.

```
kuzu> MATCH (a:User {name : "Zhang"}), (b:User) CREATE (a)-[:Follows {since :  2022}]->(b)
-
(0 tuples)
```
Then if you queried them, you can get those 4 records so only the output message is wrong.

**Comment by andyfengHKU** [comment]
This is expected. You get outputs only if the query ends with RETURN.
