### ISSUE TITLE
Phase 2 TODOs (Draft)

### ISSUE THREAD

**Issue by andyfengHKU** [kuzudb/kuzu#1034]
Tier 1
- [ ] Remove code related to adhoc properties
- [ ] Rel delete
- [ ] Rel set property
- [ ] logging

Tier 2
- [ ] Fix bugs related to wcoj
- [ ] Unify transaction design (delta or 2 version)
- [ ] Evaluate rel table remodelling (issue #955)

Tier 3
- [ ] Correlated subquery & optional match
- [ ] Single buffer pool
- [ ] Claim memory on demand
- [ ] Import/export with arrow
- [ ] Case else end
- [ ] Decouple planner and optimizer

**Comment by ray6080** [comment]
See #981 .
