### ISSUE TITLE
Closing ipython session without closing conn causes BufferManagerException

### ISSUE THREAD

**Issue by raulcf** [kuzudb/kuzu#1106]
#### How to reproduce:

1. open an iPython session. 
2. create a (kuzu) connection to a dataset 
3. close ipython (exit()) without closing the kuzu connection

#### Outcome:
"libc++abi: terminating with uncaught exception of type kuzu::common::BufferManagerException: Buffer manager exception: Deleting buffer that is still pinned. pinCount: 1 pageIdx: 12" -> the python process is killed

#### Environment:
python (3.7) running on a virtualenv on macosx

#### What I'd expect instead:
when ipython sends the kill signal to the C++ process, the buffer is unpinned

**Comment by mewim** [comment]
Fixed in #1124
