### ISSUE TITLE
Unnecessary Scans/Reads -> Extra I/O

### ISSUE THREAD

**Issue by queryproc** [kuzudb/kuzu#112]
Consider the following query:

MATCH (a)-e1->(b)
RETURN e1.time;

Currently, we consider two possible QVOs [a, b] and therefore generate two plans:
```
P1: Scan(a) → Extend(b) → ScanEdgeProperty(e1.time) → Project([e1.time])
```
OR
```
P2: Scan(b) → Extend(a) → ScanEdgeProperty(e1.time) → Project([e1.time])
```

The extension to (b) comes from the fact that we tend to cover all of the query edges and vertices blindly regardless of what the query actually requests. The two plans should actually be:   
```
P1: Scan(a) → ScanEdgeProperty(e1.time) → Project([e1.time])
```
OR
```
P2: Scan(b) → ScanEdgeProperty(e1.time) → Project([e1.time])
```

In other cases, where we don’t actually need any properties all together, we should simply get the size from the Lists header and therefore not pin/unpin unnecessarily. The query:

MATCH (a)-e1->(b)
RETURN count(*);

Should generate:
```
P1: Scan(a) → GetListSize(e1) → GROUP BY (COUNT(*))
P1: Scan(b) → GetListSize(e1) → GROUP BY (COUNT(*))
```
We need to be more aware of the actual properties needed. ID is just another property we do a join on.

**Comment by andyfengHKU** [comment]
Solved in PR #1329
