### ISSUE TITLE
CMake config python executable

### ISSUE THREAD

**Issue by andyfengHKU** [kuzudb/kuzu#1184]
We receive multiple cases where CMake detects a python executable that is not compatible with our python library. We should either

- fix the auto-detection
- add an option to change python executable

**Comment by mewim** [comment]
The Python version and interpreter could be specified by environment variables after #1240.
E.g.:
```
env PYBIND11_PYTHON_VERSION=3.9 PYTHON_EXECUTABLE=python3 make release
```
