### ISSUE TITLE
Fix memory leak errors raised by Address Sanitizer from Python tests

### ISSUE THREAD

**Issue by anuchak** [kuzudb/kuzu#1189]
[6_cat asan log.txt](https://github.com/kuzudb/kuzu/files/10436625/6_cat.asan.log.txt)

Currently Address Sanitizer is raising memory leak issues due to which the Python tests are failing:

- In kuzu_binding.cpp the bindEnumTypes function has a memory leak.
- In py_connection.cpp the transformPythonParameters and transformPythonParameter function are taking parameters by value, need to be changed to take the args by const reference.

These are the two I noticed but there can be more.

**Comment by acquamarin** [comment]
As desribed here: https://github.com/pybind/pybind11/issues/3865
There is a memory leakage bug when binding enum class.
