### ISSUE TITLE
Bugs found in lsqb

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#1206]
These queries are failing while running lsqb queries on ldbc dataset:
Q1: 
```
MATCH (:Country)<-[:IS_PART_OF]-(:City)<-[:IS_LOCATED_IN]-(:Person)<-[:HAS_MEMBER]-(:Forum)-[:CONTAINER_OF]->(:Post)<-[:REPLY_OF]-(:Comment)-[:HAS_TAG]->(:Tag)-[:HAS_TYPE]->(:TagClass)
RETURN count(*) AS count
```
Bug:  runs into an infinite loop

Q8:
```
MATCH (tag1:Tag)<-[:HAS_TAG]-(message:Message)<-[:REPLY_OF]-(comment:Comment)-[:HAS_TAG]->(tag2:Tag)
WHERE NOT (comment)-[:HAS_TAG]->(tag1)
  AND tag1 <> tag2
RETURN count(*) AS count
```
Bug: crashes with a C++ error ("RuntimeError: _Map_base::at)"
Q9:
```

MATCH (person1:Person)-[:KNOWS]-(person2:Person)-[:KNOWS]-(person3:Person)-[:HAS_INTEREST]->(tag:Tag)
WHERE NOT (person1)-[:KNOWS]-(person3)
  AND person1 <> person3
RETURN count(*) AS count
```
Bug: crashes with a segfault

Our loader also fails on a large dataset (> sf1)

**Comment by aziz-mu** [comment]
Closing this issue - Q8 and Q9, as written, give Parser Exceptions (expected), and they can be translated to working queries using `WHERE NOT EXISTS {}` syntax, as in https://github.com/kuzudb/kuzu/pull/1566
