### ISSUE TITLE
Fix loader delay issue while loading datasets

### ISSUE THREAD

**Issue by anuchak** [kuzudb/kuzu#1216]
There has been significant increase in time while loading datasets after the Arrow update.

Before arrow, time taken to load with `16 GB` bm size for LDBC 100 dataset:

----------------------------------------------------------------
448626 number of nodes has been copied to nodeTable: Person.
----------------------------------------------------------------
(1 tuple)
Time: 1.30ms (compiling), **841.20ms (executing)**

---------------------------------------------------------------
19941198 number of rels has been copied to relTable: knows.
---------------------------------------------------------------
(1 tuple)
Time: 0.30ms (compiling), **21385.36ms (executing)**

With current master, `16 GB` bm size time taken:

-------------------------------------------------------------
448626 number of tuples has been copied to table: Person.
-------------------------------------------------------------
(1 tuple)
Time: 1.26ms (compiling), **4451.98ms (executing)**

--------------------------------------------------------------
19941198 number of tuples has been copied to table: knows.
--------------------------------------------------------------
(1 tuple)
Time: 0.55ms (compiling), **69242.20ms (executing)**

**Comment by semihsalihoglu-uw** [comment]
Interesting. This conflicts with what @weipang142857 and @printfCalvin had presented as loading performance numbers on ldbc 10 before moving to arrow copier.

**Comment by weipang142857** [comment]
We tested on our own randomly generated files instead of the ldbc 10 when comparing the two implementations. Also, we did not set any constraints on the number of concurrently scheduled tasks when we did the testing. @anuchak maybe you can checkout `configs.h` and try changing `CSV_READING_BLOCK_SIZE` to `1 << 20`, and changing `NUM_COPIER_TASKS_TO_SCHEDULE_PER_BATCH` to some very large number, and see if the issue still exists.

**Comment by anuchak** [comment]
@weipang142857 currently this is the default config while loading:
```
    // Size (in bytes) of the chunks to be read in Node/Rel Copier
    static constexpr uint64_t CSV_READING_BLOCK_SIZE = 1 << 23;

    // Number of tasks to be assigned in a batch when reading files.
    static constexpr uint64_t NUM_COPIER_TASKS_TO_SCHEDULE_PER_BATCH = 200;
```

**Comment by weipang142857** [comment]
@anuchak Yes, and these are not the settings used when we tested arrow loader's performance. You can try changing the first one to `1 << 20` and changing the second to some very large number, say `100000`, and see if the issue still exists.

**Comment by mewim** [comment]
Before merging arrow, on CI it takes 3h 2m to reload ldbc-100 and run the benchmark (https://github.com/kuzudb/kuzu/actions/runs/3849319465/jobs/6558173567) while currently it takes 3h 27m (https://github.com/kuzudb/kuzu/actions/runs/4043375761/jobs/6952428525). So while it is a bit slower, it is not very significant on CI.

**Comment by anuchak** [comment]
@weipang142857 I ran with both `10000` and `100000` as config, the results improved but still around 4x higher than without arrow. 

With this config:
 
```
static constexpr uint64_t CSV_READING_BLOCK_SIZE = 1 << 20;
static constexpr uint64_t NUM_COPIER_TASKS_TO_SCHEDULE_PER_BATCH = 10000;
static constexpr uint64_t MINIMUM_NUM_COPIER_TASKS_TO_SCHEDULE_MORE = 50;
```
**RESULT:**

-------------------------------------------------------------
| 448626 number of tuples has been copied to table: Person. |
-------------------------------------------------------------
(1 tuple)
Time: 0.26ms (compiling), 3532.50ms (executing)

With this config:

```
static constexpr uint64_t CSV_READING_BLOCK_SIZE = 1 << 20;
static constexpr uint64_t NUM_COPIER_TASKS_TO_SCHEDULE_PER_BATCH = 100000;
static constexpr uint64_t MINIMUM_NUM_COPIER_TASKS_TO_SCHEDULE_MORE = 50;
```
**RESULT:**

-------------------------------------------------------------
| 448626 number of tuples has been copied to table: Person. |
-------------------------------------------------------------
(1 tuple)
Time: 0.75ms (compiling), 3388.04ms (executing)
</br>  
</br>    
This was for the NODE table, for the REL loading there is not much benefit, the loading time is more or less the same.  
With `100000` config (ran it 4 times):

--------------------------------------------------------------
| 19941198 number of tuples has been copied to table: knows. |
--------------------------------------------------------------

Time: 1.39ms (compiling), **72251.10ms (executing)**
Time: 0.24ms (compiling), **71543.93ms (executing)**
Time: 0.35ms (compiling), **70497.67ms (executing)**
Time: 0.35ms (compiling), **71156.85ms (executing)**
</br>
With `10000` config:

Time: 1.19ms (compiling), **72881.66ms (executing)**
Time: 0.23ms (compiling), **72646.35ms (executing)**
Time: 0.28ms (compiling), **72438.76ms (executing)**
Time: 0.22ms (compiling), **72875.54ms (executing)**
