### ISSUE TITLE
Release v0.0.2 TODOs

### ISSUE THREAD

**Issue by andyfengHKU** [kuzudb/kuzu#1228]
# Core
- [x] Internal rel ID
- [x] Avoid tuning BM size for data loading
- [x] scalable join order optimizer for large joins
- [x] Fix #1206 

# APIs
- [x] Export to Arrow
- [x] Export to PyG

# Deployment
- [x] Python build pipeline
- [x] C++ build pipeline
- [x] CLI build pipeline
- [x] Headers reorganization

# Documentations
- [x] Parquet import
- [x] Arrow export
- [x] NetworkX export
- [x] PyG export
- [x] Pandas export
- [x] UTF-8
- [x] regex
- [x] DDL statements
- [x] Unlabeled query 

# Colab
- [x] NetworkX example
- [x] PyG example

# Others
- [x] Add documentations examples to test framework 
- [ ] Kuzu twitter account
- [x] Release note
- [x] Release blog post

**Comment by ray6080** [comment]
The release is out now.
