### ISSUE TITLE
DML Create clause Generic Semantics docs seem to be incomplete

### ISSUE THREAD

**Issue by anuchak** [kuzudb/kuzu#1245]
https://kuzudb.com/docs/cypher/data-manipulation-clauses/create.html#generic-semantics

From the official website, the example explanation of the query seems to be incomplete:

> This is because the “a” variable matches to User node “Zhang” and there will be

**Comment by acquamarin** [comment]
solved in [486e696b71aa6a2ae899c1c432908b6d6f63e28b](https://github.com/kuzudb/kuzudb.github.io/commit/64f2fa52669b9b7315df7613e602faa2be314395)
