### ISSUE TITLE
Question: arrow/parquet out 

### ISSUE THREAD

**Issue by lmeyerov** [kuzudb/kuzu#1289]
Similar to the parquet reader, we would like fast batch output in parquet or arrow, ideally via python API -- any pointers here?

Thanks!

**Comment by ray6080** [comment]
Hi @lmeyerov , thanks for your interest! 

For batch output the query result via Python API, currently we can support exporting to an in-memory arrow table in a zero-copy way, and you can process and convert further based on that.
Please refer to our documentation and see `get_as_arrow()` here: https://kuzudb.com/docs/client-apis/python-api/query-result.html#query_result.QueryResult.get_as_arrow.
For directly exporting to parquet files, we do have that in our roadmap, but we're not there yet.

Please let us know if this answers your question, and also if you encounter any problems or have further ideas/suggestions on this.

Thanks!

**Comment by lmeyerov** [comment]
Perfect, missed that, arrow out is great!

**Comment by lmeyerov** [comment]
Meant to say -- yes, thanks!
