### ISSUE TITLE
Clean up `Mask` struct in scan_node_id.h

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#1316]
I'm finding it difficult to read and understand the `Mask` struct which should be a quite simple bitmask library that supports taking ANDs or ORs.

Currently this is the struct:
```
struct Mask {
public:
    Mask(uint64_t size, uint8_t maskedFlag) : maskedFlag{maskedFlag} {
        data = std::make_unique<uint8_t[]>(size);
        std::fill(data.get(), data.get() + size, 0);
    }

    // Notice: This function is not protected with a lock for concurrent writes because of the
    // special use case that there is no mixed reads and writes to the mask, and all writes to the
    // mask try to set a position to the same value, thus it doesn't matter which thread succeeds.
    inline void setMask(uint64_t pos, uint8_t maskerIdx, uint8_t maskValue) {
        // Note: blindly update mask does not parallel well, so we minimize write by first checking
        // if the mask is true or not.
        if (data[pos] == maskerIdx) {
            data[pos] = maskValue;
        }
    }
    inline bool isMasked(uint64_t pos) { return data[pos] == maskedFlag; }

private:
    // The value of maskedFlag is equivalent to the num of maskers passed. It is used to check if a
    // value is selected by all maskers or not. Each masker will increment its selected value by 1.
    uint8_t maskedFlag;
    std::unique_ptr<uint8_t[]> data;
};
```

First fields like maskFlag do not have explicit names. I also think all that is needed is a `std::unique_ptr<bool[]> mask` field that stores true/false and callers should have functions to AND or OR any mask[pos] with a true/false. So two functions `Mask::AND(bool val)` and `Mask::OR(bool val)`. That should be the whole library. We should also state clearly that the struct is not thread safe. 

The rest for how the callers use this struct should be up to the callers and if someone reads that code, they can follow the logic related to the callers.

**Comment by anuchak** [comment]
Closing this issue, has been fixed and merged in master.
Changes made: https://github.com/kuzudb/kuzu/commit/18aba05403b48d9d2d791c3d46180fe03e74ab8d
