### ISSUE TITLE
Cannot specify multiple Nodes in from or to relation

### ISSUE THREAD

**Issue by uwegeercken** [kuzudb/kuzu#1332]
Kuzu version 0.0.2

The documentation https://kuzudb.com/docs/cypher/ddl.html indicates that in the "from" or "to" part one can specify multiple nodes. If I try to do so in the client, I get a Parser exception:

`create node table User(name string, primary key(name));
-------------------------------------
| NodeTable: User has been created. |
-------------------------------------

create node table Pet(name string, primary key(name));
------------------------------------
| NodeTable: Pet has been created. |
------------------------------------

CREATE REL TABLE Likes(FROM User|Pet TO User, ONE_MANY)
Error: Parser exception: mismatched input '|' expecting SP (line: 1, offset: 32)
"CREATE REL TABLE Likes(FROM User|Pet TO User, ONE_MANY)"`

**Comment by andyfengHKU** [comment]
Hi, we have updated our design on DDL statement in version 0.0.2 so multiple nodes is no longer supported. You can find the description in our [release blog](https://kuzudb.com/blog/kuzu-0.0.2-release.html#disable-relationships-with-multiple-source-or-destination-labels).

The documentation looks accurate on my side. Can you point to us where it says "FROM" or "TO" can specify multiple nodes?

For your use case, I suggest the following modelling
- User node table
- Pet node table
- User_likes rel table
- Pet_likes rel table

And you can query in the following way
```
MATCH (a:User:Pet)-[e:User_likes|:Pet_likes]->(b:User) ...
```

Let us know if this solves your use case. We are still in a stage to figure out what set of features will fit in the general use case. Your feedback is highly appreciated.

Best,
Xiyang

**Comment by uwegeercken** [comment]
The doc https://kuzudb.com/docs/cypher/ddl.html says:

CREATE REL TABLE Likes(FROM **User|Pet** TO User, ONE_MANY)

I interpret this as: there can be a likes relation from a user or from a pet to a user.

I don't think the User_likes and Pet_likes is a good idea. It makes the cypher statement longer and a simple "likes" would be much better/clearer. Also, if I have a chain of nodes (hierarchy) e.g. street belongsTo city, city belongsTo country, country belongs to continent. I have fewer relations to remember. In your example I would end up with one name per relation.

Maybe you could support the idea of having two rel tables with the same name when they have different from and to definitions.

rgds,

Uwe

**Comment by semihsalihoglu-uw** [comment]
Supporting multi-src/dst node labels for relationships at the storage level is quite complicated and slows us down as we add new features. So we decided to constrain the modeling, so users need to explicitly pick single src and dst labels for each relationship as User_Likes and Pet_Likes. 

For querying: I think the right way is to use Cypher's flexible querying features to make up for the constraint we are putting on modeling. In this case, you can use unlabeled relationships in queries, which is quite helpful. For example: 

```
MATCH (a:street)-[e1]->(b:city)-[e2]->(c:city)
```
This "unlabeled" relationships allows users to query over multiple possible relationships, without remembering their names (if that's a problem in your case). You can also do:
```
WHERE label(e1) =~ "*Likes*"
```
in your WHERE clause to put constraints on the labels of the relationships with regexes.

**Comment by ray6080** [comment]
> The doc https://kuzudb.com/docs/cypher/ddl.html says:
> 
> CREATE REL TABLE Likes(FROM **User|Pet** TO User, ONE_MANY)
> 
> I interpret this as: there can be a likes relation from a user or from a pet to a user.
> 

@uwegeercken Indeed this is a mistake in our documentation. Thanks for pointing this out! We've fixed it now.

**Comment by uwegeercken** [comment]
thanks. I understand the constraint so I will work around it.
