### ISSUE TITLE
Remove CSV reader

### ISSUE THREAD

**Issue by andyfengHKU** [kuzudb/kuzu#1338]
Since we are using the CSV reader from arrow. We should no longer maintain our own CSV reader.

**Comment by mewim** [comment]
In #1341, I have removed the `CSVReader` class and renamed all `csv_reader` to `csv_reader_config`. @ray6080 Please double check if `NodeStructuredStringPropertyTest` is still needed and also consider if we should move the `CSVReaderConfig` to another place.
