### ISSUE TITLE
Client exits/dies on copy .. from

### ISSUE THREAD

**Issue by uwegeercken** [kuzudb/kuzu#1339]
I have imported several csv file meanwhile. also larger ones. But with one file I have the issue that the client exits/dies:

Fedora Linux 37 Workstation
HP HP ProDesk 600 G5 MT
Intel® Core™ i5-9500 × 6
Mesa Intel® UHD Graphics 630 (CFL GT2)
16Gb RAM

here are the files I use:
-rw-r--r--. 1 uwe uwe  59K  2. Mär 22:32 node_feature.csv
-rw-r--r--. 1 uwe uwe 997M  2. Mär 22:33 node_geoname.csv
-rw-r--r--. 1 uwe uwe 161M  2. Mär 22:48 relation_geoname_feature.csv

I am issuing this command, it runs for a while and then exits, dies. 

this all works:

create node table Geoname(geonameid int64, name string, asciiname string, latitude double, longitude double, population int64, elevation int64, dem string, timezone string, modification_date string, primary key(geonameid));
create node table Feature(class string, code string, name string, description string, primary key(code));
copy Feature from "/home/uwe/development/git/tweakstreet-kuzudb/data/node_feature.csv";
copy Geoname from "/home/uwe/development/git/tweakstreet-kuzudb/data/node_geoname.csv";

this one fails:
copy isTypeOf from "/home/uwe/development/git/tweakstreet-kuzudb/data/relation_geoname_feature.csv";

the error is (the client dies):
Speicherzugriffsfehler (Speicherabzug geschrieben)

here are the first ten lines from the relation_geoname_feature.csv:
3,S.CRRL
4,H.STM
5,P.PPL
6,H.STM
8,T.HLL
9,T.MT
10,P.PPL
11,H.STM
12,P.PPL
13,P.PPL

you can see that the Geoname node geonameid is a long and the Feature node code is a string. I don't think I have a memory problem, as some of the other files are much larger and did work. I did try to increase the number of threads, but without luck.

greetings,

Uwe

**Comment by acquamarin** [comment]
Hi Uwe,
Can you provide the dataset that you are trying to load? So i can better look into this issue.
If the csv file is large, you may need to increase the buffer pool size. To increase the buffer pool size, simply launch the shell with option `-d sizeInMegabytes`.  (e.g. `./kuzu_shell -i /tmp/db -d 1024` which starts kuzu with buffer pool size = 1024MB and sets database path to /tmp/db )

**Comment by uwegeercken** [comment]
Hi Ziyi,

I did some debugging and found the issue. The file has  a bit more than 11 million rows. I started deviding it by half to further narrow down the problem. Then I found the error with id=309866 (that is line 300109 in the file). The key "S." does not exist - which is true.

309862 | P.PPL
309863 | P.PPL
309864 | P.PPL
309865 | T.PT
**309866 | S.**
309867 | H.LK
309868 | H.LK
309869 | H.LK
309870 | H.SPNG
309871 | P.PPL

Now when I use a file with 320000 rows, the client will **NOT** abort and display the error like this:

Error: Copy exception: Cannot find key: S. in the pkIndex.

But when I use a larger file like e.g. 1 million rows, then instead of logging the error, the client will die and exit.

Let me know if this helps. I have attached the file with 1 million rows.
[relation_geoname_feature_1mio.zip](https://github.com/kuzudb/kuzu/files/10884401/relation_geoname_feature_1mio.zip)

**Comment by acquamarin** [comment]
Hi Uwe,

It appears from the error message that the primary key "S.".  doesn't exist in the “feature“ csv file. Could you please share the node_feature.csv and node_geoname.csv files with me so that I can better dig into the issue?

**Comment by uwegeercken** [comment]
Here is the file you requested. Hope this helps. Otherwise I will have to redo the error (I already corrected it in my ETL process).
[node_feature.zip](https://github.com/kuzudb/kuzu/files/10922565/node_feature.zip)

**Comment by uwegeercken** [comment]
@acquamarin I think the error might be somewhere else... 

Example:

I create a rels table with an invalid ONE_ONE relation: 

`create rel table belongsTo(from Geoname to AdminDivision, ONE_ONE);`

 I import the data:

`copy belongsTo from "/home/uwe/development/git/tweakstreet-kuzudb/data/relation_geoname_admin_division.csv";`

I get this error: 

`Error: Copy exception: RelTable belongsTo is a ONE_ONE table, but node(nodeOffset: 338, tableName: AdminDivision) has more than one neighbour in the backward direction.`

The I drop the table and recreate it with a MANY_MANY relation.

If I now try to import the data again, the client will exit/die.

But if I now start the client again and then import the data again, it will work correctly.

**Comment by acquamarin** [comment]
Hi Uwe,
Since you haven't provided me `node_geoname.csv`, i used a randomly generated `node_geoname.csv` file and your [node_feature.zip](https://github.com/kuzudb/kuzu/files/10922565/node_feature.zip), [relation_geoname_feature_1mio.zip](https://github.com/kuzudb/kuzu/files/10884401/relation_geoname_feature_1mio.zip).
Unluckily, i still not able to reproduce the bug.
Can you provide me the `node_geoname.csv` as well?

Ziyi

**Comment by uwegeercken** [comment]
The uncompressed size is about 1Gb - compressed 265Mb but the limit is 25Mb. How can I get the file to you?

**Comment by uwegeercken** [comment]
Are you testing on Linux?

**Comment by acquamarin** [comment]
I am testing on my MAC, can you please upload it to onedrive or google drive and share the link with me?

**Comment by uwegeercken** [comment]
here is the data (already shared it with Xiyang): https://drive.google.com/drive/folders/1FWi-si9auV5NhpqMq0fqsxTCeXuLAvF0?usp=share_link

**Comment by andyfengHKU** [comment]
This has been solved since we have migrated Copy pipeline to reuse task schedular. Exception messages can not be propagated properly
