### ISSUE TITLE
Is index creation currently supported?

### ISSUE THREAD

**Issue by jmftrindade** [kuzudb/kuzu#1373]
Hi there! This is more of a question rather than an issue: is it currently possible to create an index in addition to the one created on non-primary keys? E.g., given the example schema for User table:

```
kuzu> :show_node User
User properties:
        name STRING(PRIMARY KEY)
        age INT64
```

In Neo4J you can create an index like so:
```
CREATE INDEX ON :User(age)
```

And when I try that on Kuzu shell, it looks like index creation is not supported yet:
```
kuzu> CREATE INDEX ON :User(age)
Error: Parser exception: Parentheses are required to identify nodes in patterns, i.e. (INDEX) (line: 1, offset: 7)
"CREATE INDEX ON :User(age)"
        ^^^^^
```
Is that the case, or does the syntax for creating indexes in Kuzu differ from that of Neo4J?

Thanks!
Joana

**Comment by andyfengHKU** [comment]
Hi Joana,

We don't yet support creating indexes in the current release.

Thanks,
Xiyang

**Comment by jmftrindade** [comment]
Alright, thanks for the prompt response. Cheers --Joana
