### ISSUE TITLE
kuzu binary: readline functionality buggy

### ISSUE THREAD

**Issue by vbmithr** [kuzudb/kuzu#1391]
I frequently end up in a state where readline functionality (emacs-like key bindings) in the shell are not working anymore.

**Comment by ray6080** [comment]
Hi @vbmithr , can you provide a bit more details, such as the OS version, are you compiling from the latest master or using the released binary, and is there a specific operation in the shell that triggers the bug? so we can reproduce it more quickly. Thanks!

**Comment by vbmithr** [comment]
OS: Archlinux
Release: git
To reproduce on example of bugs:

1. Type a command
2. Do Ctrl+p to get it back from history
3. Ctrl+a to go to beginning of the line
4. Ctrl+d to delete thef first character.

Step 4 doesn't work. If typing characters at this point, something weird happens.

**Comment by ray6080** [comment]
@vbmithr thanks! We will take a look.

**Comment by uwegeercken** [comment]
on Linux I have similar issues. I do a Ctrl-a to go to the beginning and then the cursor will not move anymore. Sometimes when I move backwards in a line and then start typing, the text appears appended at the end of the line. At other times, pressing the right arrow once moves the cursor about 10 chars right and then the left arrow moves it to the starting position and the last character of the line gets removed. Very weird and seems to be different all the times.

**Comment by uwegeercken** [comment]
This is my line for testing:

```
hello this is a test line for checking the keyboard functionality
```
1. I am at the end of the line
2. I press Ctrl-a - the cursor jumps to the first position

Result: right arrow or Ctrl-e does not work. If I start typing multiple "a" (cursor is in the first position), this is the result:
```
hello this is a test line for checking the keyboard functionalityaaaaaaaaaa
```
If I press the backspace key, the cursor moves left and for each backspace an "a" at the end is removed

**Comment by vbmithr** [comment]
duckdb made it right, it's also a C++ project, maybe you could just port their solution :D

**Comment by semihsalihoglu-uw** [comment]
:) Nice! I am sure if we can write a DBMS, we can get this right too :)

**Comment by uwegeercken** [comment]
it is sooo much better now. It's sometimes the little things that make the developer happy  :-)

**Comment by vbmithr** [comment]
Ok, seems fixed indeed. Thanks @acquamarin!
