### ISSUE TITLE
source code compile error 

### ISSUE THREAD

**Issue by nevermore3** [kuzudb/kuzu#1393]
my system info: ubuntu, x86_64

when I use the source code to compile, the error message is as follows

```
fatal error: arrow/api.h: No such file or directory
    9 | #include <arrow/api.h>
      |          ^~~~~~~~~~~~~
```
Is it that the compilation option is not set correctly

**Comment by mewim** [comment]
Hi @nevermore3,

We regularly build and test with Ubuntu 22.04 LTS on our CI/CD pipeline. Could you please let us know the version of your Ubuntu and CMake and the compiler you are using, as well as the command you used?

**Comment by nevermore3** [comment]
my OS version : Ubuntu 20.04 LTS
CMAKE : 3.16.3
compiler : gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

My operation is as follows
1、download  source code 
2、cd  ~/kuzu 
3、mkdir build
4、cd  build
5、 cmake ..
6、 make NUM_THREADS=20

**Comment by mewim** [comment]
Hi @nevermore3. Could you please try to run `make clean-all`  and then `make all NUM_THREADS=20` under `kuzu` directory? The build script should automatically fetch and build Apache Arrow dependency first before building `kuzu`.
