### ISSUE TITLE
Add a CMake Option to specify if Arrow should be compiled from scratch or linked

### ISSUE THREAD

**Issue by mewim** [kuzudb/kuzu#1401]
As title. Building Arrow can be slow and can also cause issue when the server for hosting Arrow dependencies is down. We should provide an option to allow linking Arrow installed to system (e.g. via apt / brew) instead of fetching from Github and building from scratch.

**Comment by ray6080** [comment]
This is no longer relevant, as we've removed arrow lib as a third party dependency now.
