### ISSUE TITLE
Cannot start kuzu_shell with existing data (database path)

### ISSUE THREAD

**Issue by uwegeercken** [kuzudb/kuzu#1405]
I just built kuzu from src.

Compiling went well, but when I wanted to start kuzu_shell with the usual -i flag for the database path I get an error:

```
Flag could not be matched: 'i'
  ./kuzu_shell databasePath {OPTIONS}

    KuzuDB Shell

  OPTIONS:

      databasePath                      Database path.
      -h, --help                        Display this help menu
      -d, --defaultBPSize               Size of buffer pool for default and
                                        large page sizes in megabytes
      "--" can be used to terminate flag options and force all following
      arguments to be treated as positional options
```
Note that the database path already contains data from the kuzu 0.2 version!

Running kuzu_shell without the -i also does not work (with an existing db pat)::

```
./kuzu_shell /home/uwe/development/kuzu-db
Opened the database at path: /home/uwe/development/kuzu-db
Enter ":help" for usage hints.
std::bad_alloc
```
The client immediately exits.

But running kuzu_shell on an empty directory works:
```
./kuzu_shell /home/uwe/development/kuzu-db2
Opened the database at path: /home/uwe/development/kuzu-db2
Enter ":help" for usage hints.
kuzu>
```

**Comment by andyfengHKU** [comment]
Hi @uwegeercken,

This is desired behaviour. Because we are iterating quickly and constantly modifying storage format. We cannot provide backward compatibility between different versions. This will be the case for a while until we stabilize on the storage side.

Thanks,
Xiyang

**Comment by uwegeercken** [comment]
Yes, I thought so. I wanted to add it here so that others see the issue as well.

Thanks,

Uwe

**Comment by andyfengHKU** [comment]
PR #1436 has introduced storage format number so we throw error message if storage version is not aligned with kuzu binary version.
