### ISSUE TITLE
support for current_date/currentTimestamp functions

### ISSUE THREAD

**Issue by uwegeercken** [kuzudb/kuzu#1412]
please add functionality to retrieve the current system date and timestamp.

So one can e.g. do this:

```
match(g:Geoname) where g.modification_date = current_date() - interval('3 days') return g.name, g.modification_date;
```

**Comment by acquamarin** [comment]
Hi Uwe,
Actually `current_date()` and `current_timestamp` doesn't return the current system date and timestamp, it returns the date/timestamp when the transaction starts. We have added this feature to our TODO list.

**Comment by andyfengHKU** [comment]
This should be added in #3497
