### ISSUE TITLE
Add progress bar to loadder 

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#1419]
We should follow the duckdb way to add a progress bar to loader.

**Comment by semihsalihoglu-uw** [comment]
Hmmm, I was happy with our previous progress bar, which got removed without my consent because "other systems didn't have it" argument :) Happy to see this coming back.

**Comment by andyfengHKU** [comment]
I think we removed it because it print arbitrarily when running tests

**Comment by andyfengHKU** [comment]
Duplicate with #2968
