### ISSUE TITLE
Support all integer data types as primary key

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu#1433]
As we've added more integer data types, such as (U)INT8, (U)INT16 and (U)INT32, etc., we should also support all of them as primary keys.

**Comment by acquamarin** [comment]
Should we also support uint and int8 type as primary key?

**Comment by ray6080** [comment]
> Should we also support uint and int8 type as primary key?

We should support all int types. Updated the title and description now.

**Comment by ray6080** [comment]
Done in #2728.
