### ISSUE TITLE
`:show_node` does not show an empty node table

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#1445]
I have created a node table, which is empty, and typed `:show_node` on the shell and get this:

```
kuzu> :show_node
Cannot find node table 
kuzu> create node table Comment (ID INT64,creationDate TIMESTAMP,locationIP STRING,browserUsed STRING,content STRING,length INT64, PRIMARY KEY(ID));
Error: Binder exception: Node Comment already exists
```
Did not try but the same problem might exist for a rel table as well.

**Comment by andyfengHKU** [comment]
Can u try `:list_nodes` and `show_node Comment`

**Comment by acquamarin** [comment]
:show_node will throw an exception if the tablename is not given.
