### ISSUE TITLE
Implement csv file auto detection

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#1448]
As described in duckdb's documentation page:
https://duckdb.org/docs/data/csv/auto_detection
We should have a mechanism to detect the csv parsing options:

1. Detect the dialect of the CSV file (delimiter, quoting rule, escape)   (DONE)
2. Detect the types of each of the columns                                           (REFACTORING)
3. Detect whether or not the file has a header row                               (CONSTRUCTING)

**Comment by SterlingT3485** [comment]
The Dialect Detection is implemented.

The Header Detection may involve in the refactor of our previous code from stage 2 [CSVNameAndTypeSniff](https://github.com/kuzudb/kuzu/pull/3932). As the Sniffing of Names should be done independently from the Sniffing of Types, in stage 3.
