### ISSUE TITLE
Function expression type

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu#1481]
Currently, both `FUNCTION` and `AGGREGATE_FUNCTION` are expression types, and when we bind function expression, we are manually check function type:
```
    // check for special function binding
    if (functionName == ID_FUNC_NAME) {
        return bindInternalIDExpression(parsedExpression);
    } else if (functionName == LABEL_FUNC_NAME) {
        return bindLabelFunction(parsedExpression);
    }
    auto functionType = binder->catalog.getFunctionType(functionName);
    if (functionType == FUNCTION) {
        return bindScalarFunctionExpression(parsedExpression, functionName);
    } else {
        assert(functionType == AGGREGATE_FUNCTION);
        return bindAggregateFunctionExpression(
            parsedExpression, functionName, parsedFunctionExpression.getIsDistinct());
    }
```
This is quite confusing and probably due to stale code.
We can remove `AGGREGATE_FUNCTION` from `ExpressionType`, and add a new `FunctionType` enum to indicate scalar, agg, schema, etc. functions.

**Comment by andyfengHKU** [comment]
This is now replaced by `CatalogEntryType` I don't think we should remove ExpressionType::AGGREGATE_FUNCTION, it's being used in other places as well.
