### ISSUE TITLE
optimize Metadata design for in-memory

### ISSUE THREAD

**Issue by g31pranjal** [kuzudb/kuzu#149]
Issue:
- The current design does pointer chasing to traverse PageListGroups while finding the required pageIdx from the pageList. 

What can done:
- We keep pageLists as vector in memory {different from the layout on disk} - as we had before. 

Challenges/things to consider:
- We need to make the setup update-friendly so that metadata files on disk can be easily updated, in as less i/o cycles as possible.
-  If we keep metadata in 2 formats, vectors and as blob (current design), updates get easy (since we update the blob and re-construct the required vector), there is data duplication.

**Comment by ray6080** [comment]
This is no longer relevant.
