### ISSUE TITLE
SEGFAULT on collect struct

### ISSUE THREAD

**Issue by aziz-mu** [kuzudb/kuzu#1666]
I'm getting a segfault on this query, on the ldbc-sf01 dataset: 
`MATCH (message:Post:Comment)<-[like:Person_likes_Post|:Person_likes_Comment]-(liker:Person)
       RETURN collect({msg: message, likeTime: like.creationDate})[1] AS Collected;`

**Comment by acquamarin** [comment]
This query now passes on ldbc-sf0.1 dataset.
