### ISSUE TITLE
CSV cleaner extension using LLM

### ISSUE THREAD

**Issue by rfdavid** [kuzudb/kuzu#1701]
### Motivation

I was trying to import [WikiKG90Mv2](https://ogb.stanford.edu/docs/lsc/wikikg90mv2/) from OGB to Kùzu, but the CSV contains some small errors in different lines, for example, escaping `,`, extra `,` at the end of line, extra `"` etc. 

```
6031876,Q12857511,Template:\,Wikimedia templat
3119806,Q105422542,"Alley, Jerome",article in A Compendium of Irish Biography,
3738009,Q106122025,"Kristian Hvidt: \""Forsker, furie, frontkæmper. En bog om Lis Jacobsen\""",
```

These small errors might not be a problem for some parsers, and we can also make ours more flexible to handle known situations automatically. However, it only partially solves the problem. Real-world data is extremely noisy and full of errors and incompletions. From the user's perspective, cleaning CSV is a time-consuming task, and it is difficult to automate. 

My idea is to propose a feature as an extension to automatically clean CSV data using LLM while importing. LLMs are proven to be very efficient in spotting and fixing these errors by contextualizing the current CSV data and inferring a correction.
This optional extension should be able to learn the structure from a tiny portion of the CSV and automatically fix broken lines during data ingestion.

**Comment by andyfengHKU** [comment]
Close for now because we don't have plans for this in the foreseeable future (due to performance & cost issues)
