### ISSUE TITLE
PRAGMA statements

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#1708]
| pragma statement | usage | example | support | 
|---|---| --- | --- |
| threads | CALL threads=4 | set the amount of threads for parallel query execution | &check; |
| timeout | CALL query_timeous=40 | set the query timeout value | &check; |
| show_tables | CALL show_tables | list all node/rel tables | &check; |
| table_info | CALL table_info('table_name') | get info for a specific node/rel table | &check; |
| recurrsive join upper bound | CALL recurrsive_join_upper_boound=30 | set the recurrsive join upper bound | |
| version | CALL version | show Kùzu version | &check; |
| logging_level | CALL logging_level=debug | set the logging level of the database | |

**Comment by FactEngineCommunity** [comment]
Are these feature requests? Or some form of documentation?

If they are feature requests then I support them. I'd support as many PRAGMA type calls to help reverse engineer a KuzuDB.

**Comment by andyfengHKU** [comment]
> Are these feature requests? Or some form of documentation?
> 
> If they are feature requests then I support them. I'd support as many PRAGMA type calls to help reverse engineer a KuzuDB.

Hi, 

This is a proposal of what PRAGMA functions we will implement in the first batch.  This feature will be available in our next release which is coming in 2 weeks.
