### ISSUE TITLE
Throw copy exception when num of columns in files are not matched with num of properties in table schema

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu#1738]
We should throw an exception when the num of columns in files are not expected, i.e., not matched with the num of properties defined in table schema.

**Comment by LowLevelMahn** [comment]
> I think the arrow parser will throw an exception if the number of columns doesn't match

but the table schema should be valid before - i wouldn't rely on the implementation detail of arrow here
especially when there were (if im correct) talks to remove the arrow dependency someday
