### ISSUE TITLE
Build time is very slow

### ISSUE THREAD

**Issue by LowLevelMahn** [kuzudb/kuzu#1740]
its seems that make forces -j1 meaning that my new 8 core system is "nearly" degraded to Gameboy-Color speed :)
is there a reason for not allowing parallel builds?

**Comment by mewim** [comment]
We do allow build in parallel. As per the documentation:
> To build in parallel, pass `NUM_THREADS` as parameter, e.g., `make NUM_THREADS=8`.

**Comment by LowLevelMahn** [comment]
thanks
