### ISSUE TITLE
Rust API doesn't compile with clang

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#1754]

**Comment by benjaminwinger** [comment]
I'm not sure exactly what error you're getting with it, but I was able to reproduce this on Ubuntu where it will fail in cxx's autogenerated `cxx.h` with the message `fatal error: 'algorithm' file not found` (when importing `<algorithm>`).
No such issue on my Gentoo or Arch Linux machines, so I suspect that's something to do with clang's standard library. Maybe CMake is doing something to detect those files which the rust cc crate used to build the shim doesn't.

**Comment by acquamarin** [comment]
I got two errors:
1. PropertyList doesn't have a constructor, maybe clang doesn't generate. a default constructor for property list.
so line112: `std::make_unique<PropertyList>(val.getProperties());` will cause a compilation error.
2. lstdc++  is not included in clang++
L/Users/z473chen/Desktop/code/kuzu/tools/rust_api/kuzu-src/external/build/arrow/install/lib64'
          ld: library not found for -lstdc++
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
