### ISSUE TITLE
Parallelize finalization of the hash table in hash join

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu#177]
Currently, the finalization phase of the hash table is executed as single-threaded (the last thread in the pipeline).
This can be further optimized by utilizing the CAS to concurrently finalizing the ht directory.

This is now the bottleneck of hash join scalability when the build side is large, which dominates the cost of the hash join.

**Comment by andyfengHKU** [comment]
This is duplicate with https://github.com/kuzudb/internal/issues/10
