### ISSUE TITLE
How to show this "Primary key column contains values that do not exist in the table"

### ISSUE THREAD

**Issue by gasvn** [kuzudb/kuzu#1801]
When copy from csv file to the table, I get the following error. Is there a way to show this "Primary key column"? As I have checked the csv file and I cannot find a missing node.

conn.execute('COPY NEWDATA FROM \"../data/edges_relation_int.csv\";')
  File "/home/shgao/miniconda3/envs/gpt/lib/python3.10/site-packages/kuzu/connection.py", line 88, in execute
    self._connection.execute(
RuntimeError: Copy exception: Primary key column contains values that do not exist in the table.

**Comment by acquamarin** [comment]
Hi Shanghua,
The error message suggests that the rel file that you are trying to load contains an edge whose src/dst id is not a valid primary key.
Can you double check that the src/dst id of each edge in the rel file is a valid primary key as defined in the node file?

**Comment by gasvn** [comment]
Thanks for the quick reply! I have checked the rel file, but I cannot find a src/dst that is not in the node file. Is there a way to locate this wrong src/dst in zuku? Like get the src/dst name in the exception

**Comment by acquamarin** [comment]
Can you provide me the dataset that you are trying to load so i can locate the problem efficiently.

**Comment by gasvn** [comment]
Thanks, here is the dataset link https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IXA7BM
I am trying to load nodes.csv and the edges.csv

**Comment by ray6080** [comment]
Hi @gasvn , I didn't catch the `Copy exception` you reported. But I did catch a concurrency error on my local. Will work on that very soon. Hope that can also address your problems.
Btw, are you using our latest version? and may I know which platform you're on?
If you want to play around a bit more, I suggest to try setting max num of threads to 1 (https://kuzudb.com/docusaurus/cypher/configuration#change-number-of-threads-for-execution) before copying the file, which hopefully can fix your problem.
 
Thanks!

**Comment by ray6080** [comment]
Hi @gasvn , we just released a new hot fix version (https://kuzudb.com/docusaurus/blog/kuzu-0.0.6-release). Can u give a try and verify if the issue has been fixed? Thanks!

**Comment by gasvn** [comment]
Thanks! I have tried the latest verison and the issue has been fixed.
