### ISSUE TITLE
Buffer manager exception

### ISSUE THREAD

**Issue by MaximilianoPona** [kuzudb/kuzu#1826]
I'm having an error when i want to create a database

import kuzu

shutil.rmtree("./testdb", ignore_errors=True)

db = kuzu.Database('./testdb')

---> 56     self._database = _kuzu.Database(self.database_path,
     57                                     self.buffer_pool_size)

RuntimeError: Buffer manager exception: Mmap for size 8796093022208 failed.

I have changed the parameter buffer_pool_size but i get the same error. I'm running this in IBM cloud pak for data linux server, in colab works just fine

**Comment by ray6080** [comment]
Hi @MaximilianoPona , thanks for the reporting! It looks like the server has a smaller address space than expected. Let me reproduce it first, I will take a look and get back to you.

**Comment by acquamarin** [comment]
Hi @MaximilianoPona 
I am not able to reproduce your error on IBM cloud pak for data jupyter notebook:
<img width="1325" alt="image" src="https://github.com/kuzudb/kuzu/assets/47264495/43ed1cc5-5b94-4cc4-8156-584a57a823b5">
IBM machine configuration:
1vCPU and 4GB memory.

**Comment by ubmarco** [comment]
I see the same error on a Raspberry Pi 4 with 4GB of RAM. Using kuzu with the Python client.

**Comment by mewim** [comment]
> Raspberry Pi 4

Hi @ubmarco, now we have an additional parameter in the database constructor: `max_db_size`, which defines the size for mapped memory space, it defaults to `8796093022208` (8 TBs). Can you try to set it to a smaller value to see if it fixes your issue? For Python API, you can do something like:
```
 db = kuzu.Database(..., max_db_size=107374182400) # limit max_db_size to 100GB
```

**Comment by mewim** [comment]
> Thanks, that worked. Just a note, `max_db_size` needs to be a power of 2, so
> 
> ```python
> MAX_KUZU_DB_SIZE = 64 * 1024 * 1024 * 1024 # 68_719_476_736 == 64 GiB
> MAX_KUZU_DB_SIZE = 128 * 1024 * 1024 * 1024 # 137_438_953_472 == 128 GiB
> ```
> 
> would be valid options. Do I understand correctly, this does not relate to RAM but to memory space that can be addressed by the CPU?

Yes this is not the actual memory but the maximum memory space that can be mapped via the `mmap` system call. This depends on a few things, such as the configuration of the kernel and the CPU specs. In the future we may develop a way to automatically detect this on the system instead of requiring manual configuration.

**Comment by ubmarco** [comment]
Thanks for the feedback. Is it possible to set this value for the CLI app?
I get the error already when starting the Kuzu CLI.

**Comment by mewim** [comment]
> Thanks for the feedback. Is it possible to set this value for the CLI app? I get the error already when starting the Kuzu CLI.

I don't think it is currently doable but can be supported quickly. I have created #4731 for it.
