### ISSUE TITLE
Expression type refactor

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#1838]
We current have 3 function related expression types:
```
SCALAR_FUNCTION
AGGREGATE_FUNCTION
MACRO
```
We should consider have a single function expression type since those three types are a type of FUNCTION expression.

**Comment by andyfengHKU** [comment]
So ExpressionType::MACRO is no longer in use.

I do need a way to differentiate FUNCTION & AGGREGATE_FUNCTION. So it either happens at ExpressionType level or at FunctionType level. I don't perceive a major difference so I'm closing this issue.
