### ISSUE TITLE
Handmade execution plan

### ISSUE THREAD

**Issue by ErvinXie** [kuzudb/kuzu#1841]
Is there any possibility that write my own execution plan on kuzu db? I am conducting some performance test, while the cypher compiler sometimes cannot generate execution plans that I am expecting.

**Comment by andyfengHKU** [comment]
Hi Ervin,

We did implement a similar feature when we perform benchmark internally. The `query` interface under `Connection` can take `encodedJoin` as a parameter which will guide the join order.

```
std::unique_ptr<QueryResult> Connection::query(
    const std::string& query, const std::string& encodedJoin) {
    lock_t lck{mtx};
    auto preparedStatement = prepareNoLock(query, true /* enumerate all plans */, encodedJoin);
```

One example of encoded is join can be found under `benchmark/queries/ldbc-sf100/join`
```
-NAME q29
-COMPARE_RESULT 1
-QUERY MATCH (a:Person)-[:knows]->(b:Person) RETURN MIN(a.birthday), MIN(b.birthday)
-ENCODED_JOIN HJ(b._ID){E(b)S(a)}{S(b)}
---- 1
1980-02-01|1980-02-01
```

`S` stands for `SCAN`, `E` stands for `EXTEND` and HJ stands for `HJ`. Inside `HJ()` is the join condition, i.e. the `_ID` of the table that we are joining on.

Note that it may not always be able to find the join order if the join graph becomes very large. This feature is not very user friendly but might be able to solve your problem temporarily.

In the long term, I will expose a configuration to disable join order optimizer, and the join order will be picked in the left to right order as the written query.

**Comment by ErvinXie** [comment]
Hello Andy, thanks for your detailed reply. 

Beside the join order, I wonder if I can control the physical plan? Such as use worst case optimal join instead of binary hash join, and change aggregation orders. I know usually there is no user interface for this kind of demand. So which part of code should I edit if I want to build a execution plan on my own and execute it?

**Comment by andyfengHKU** [comment]
I think for worst case optimal join you can still encode, e.g.

Given statement 
```
(a)->(b)->(c), (a)->(c)
```

One WCOJ plan could be encoded as
```
I(c._id){E(b)S(a)}{E(c)S(a)}{E(c)S(b)}
```

For aggregation order, I'm assuming you mean eager/lazy aggregation. I think the most principled way is to write an optimizer rule to do that. Which means you will need to take a look at `optimizer` module and add your own ones. Alternatively this could be done during planning phase so you can change `planner` module. Let me know if my understanding of aggregation order is wrong. Happy to chat more in slack if you want.

**Comment by ErvinXie** [comment]
Thank you for the reply. I will look into the code then.
