### ISSUE TITLE
Transaction refactor

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#1851]
## Why we need this refactor
Since we support UDF, user created macros should have different visibilities to read/write transactions. E.g. user created macros should only be visible to the statements within that write transaction until it commits. To achieve this, binder needs to use the transaction pointer when matching macros from the catalog.

## Plan:
1. Move transaction pointer from executionContext to clientContext so binder can access this transaction pointer as well. Client context should also be saved in the executionContext, so processors (operators) can access the transaction pointer.
2. We should prepare statements in a transaction. When the user calls to `prepare()`, we should check whether there is an active transaction. If not, we should start an auto-commit transaction.
3. Refactors the catalog APIs:
We should stop exposing the `getReadOnlyVersion()`, `getWriteVersion()` to the caller. Instead, each get API in the catalog should take in a transaction pointer.

**Comment by ray6080** [comment]
This is no longer relevant.
