### ISSUE TITLE
Index scan returning incorrect results for queries

### ISSUE THREAD

**Issue by anuchak** [kuzudb/kuzu#1915]
![Screenshot from 2023-08-09 20-46-49](https://github.com/kuzudb/kuzu/assets/21187588/8113267b-39ac-4b70-9b71-00e1b846c6a3)

![Screenshot from 2023-08-09 20-52-32](https://github.com/kuzudb/kuzu/assets/21187588/10b4ee63-e0c9-42cd-a8f5-e7733b781319)

This is from LDBC-100 dataset, when I give exact equality condition on PK the `IndexScan` operator is used.
Incorrect properties and everything gets returned.

**Comment by anuchak** [comment]
The 2nd screenshot shows for the same tuple, the correct answer when filter is given.

**Comment by ray6080** [comment]
@anuchak , can you give a try on latest master again? I can't reproduce it locally.

**Comment by ray6080** [comment]
Actually, i've reproduced it. This [PR](https://github.com/kuzudb/kuzu/pull/2001) should fix it.
