### ISSUE TITLE
Variable Length Query - path length write to ValueVector taking long time

### ISSUE THREAD

**Issue by anuchak** [kuzudb/kuzu#1925]
![Screenshot from 2023-08-11 17-33-26](https://github.com/kuzudb/kuzu/assets/21187588/238030bd-1643-4151-b41f-f814dd124370)

Keeping this issue open here, essentially for a var length query that is returning path lengths the 2nd run of the query is taking almost double time that of 1st query run.

This usually doesn't happen and the execution time goes down after the 1st query run. Not sure where the issue is coming from.

**Comment by andyfengHKU** [comment]
This is longer relevant since we are moving to new GDS framework
