### ISSUE TITLE
`bun install` does not automatically exeucte the installation script for Node.js bindings

### ISSUE THREAD

**Issue by mewim** [kuzudb/kuzu#1947]
[Bun](https://bun.sh/) which is an alternative Node.js run time does not execute the installation script as defined in https://github.com/kuzudb/kuzu/blob/master/tools/nodejs_api/install.js. This causes the downloaded package unusable when the user installs kuzu via `bun install`. We should look into how to make `bun install` also execute the script automatically.

**Comment by notzree** [comment]
Add `{
  "trustedDependencies": [
    "kuzu"
  ]
}` to package.json and run` bun remove kuzu` `bun add kuzu` to run post install scripts
[#4738 Bun doesn't run install scripts on packages](https://github.com/oven-sh/bun/issues/4738)

**Comment by mewim** [comment]
@notzree Thanks for providing this solution. We can close this issue for now.

**Comment by ansarizafar** [comment]
I am getting this error even after following the work around.
```
error: Cannot find package "kuzu" from "/home/zafaransari/projects/bun/adarea/src/index.ts"
```

**Comment by mewim** [comment]
@ansarizafar  I am able to use kuzu with bun v1.0.10 on macOS 14. This is a minimal demo which contains my setup:

[kuzu-bun-test.zip](https://github.com/kuzudb/kuzu/files/13281722/kuzu-bun-test.zip)

This example can be run with `bun install && bun run index.js`.

Output:
```
bun install v1.0.10 (d85bd49d)
 + kuzu@0.0.12
Prebuilt binary is available.
Copying prebuilt binary to package directory...
Copied /Users/lc/Developer/kuzu-bun-test/node_modules/kuzu/prebuilt/kuzujs-darwin-arm64.node -> /Users/lc/Developer/kuzu-bun-test/node_modules/kuzu/kuzujs.node.
Copying JS files to package directory...
Files to copy: 
  access_mode.js
  connection.js
  database.js
  index.js
  logging_level.js
  prepared_statement.js
  query_result.js
Copied JS files to package directory.
Done!

 71 packages installed [53.00ms]
{
  "u.name": "Adam",
  "u.age": 30
}
{
  "u.name": "Karissa",
  "u.age": 40
}
{
  "u.name": "Zhang",
  "u.age": 50
}
{
  "u.name": "Noura",
  "u.age": 25
}
```
