### ISSUE TITLE
[Rust] Getting current node / relationship / property table names

### ISSUE THREAD

**Issue by amartins23** [kuzudb/kuzu#1958]
Kuzu provides a couple of metadata methods on the current DB connection to obtain [node table names](https://docs.rs/kuzu/0.0.7/kuzu/struct.Connection.html#method.get_node_table_names), [node relationship table names](https://docs.rs/kuzu/0.0.7/kuzu/struct.Connection.html#method.get_rel_table_names), [node property names](https://docs.rs/kuzu/0.0.7/kuzu/struct.Connection.html#method.get_node_property_names) and [relationship property names](https://docs.rs/kuzu/0.0.7/kuzu/struct.Connection.html#method.get_rel_property_names). Sadly, each of these methods returns a single string. A much nicer API would return a vector of strings.

Please improve this side of the API. Thank you!

**Comment by ray6080** [comment]
Hi @amartins23 , thanks! This is nice suggestion. Will do this! 😄

**Comment by andyfengHKU** [comment]
We have supported this as internal functions rather than Rust APIs. This can be done through `CALL table_info(<table_name>) RETURN *`.
