### ISSUE TITLE
Extend Developer Documentation

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#1996]
This is a work-in-progress issue, so it is meant to be updated regularly.

Let's have a working issue to take notes of important information that developers would need and slowly put them into our documentation. I will send this around to our interns and other developers to put the information they'd like to include in the developer documentation and we can go through them and add them over time.

**Comment by mewim** [comment]
Docs for building Kùzu is added: https://kuzudb.com/docusaurus/development/building-kuzu
