### ISSUE TITLE
Make Python API compilation optional 

### ISSUE THREAD

**Issue by mewim** [kuzudb/kuzu#2000]
The current CMake config always compiles Python API, which requires python and its related headers to be present on the system to be able to run the build. We should make Python optional just like other APIs (rust, Java, and JavaScript), so that CLI and libs can be compiled without Python.

**Comment by benjaminwinger** [comment]
I'd already made it optional to speed up the rust build. I just had made it default to enabled to keep the behaviour the same.

See [here](https://github.com/kuzudb/kuzu/blob/ad5fa79688d1845726a78dab89b7431e6daaa9a0/CMakeLists.txt#L117)
