### ISSUE TITLE
Python API multiple tests fail due to Parser exception on Windows

### ISSUE THREAD

**Issue by russell-liu** [kuzudb/kuzu#2010]
Example failed run on windows-2022 GitHub-hosted runner -- logs and workflow file:
https://github.com/kuzudb/kuzu/actions/runs/6122723770/job/16619119282
There does not seem to be any evidence of these tests ever passing on a Windows machine.

**Comment by mewim** [comment]
The failures are likely due to path handling issues on Windows. We need to modify the test suites to normalize the paths for Python on Windows platform.

**Comment by benjaminwinger** [comment]
> The failures are likely due to path handling issues on Windows. We need to modify the test suites to normalize the paths for Python on Windows platform.

I'm not sure that it's the fault of the test suite as much as the fault of the query parser (which I'm guessing doesn't fully support windows paths right now). I think it's properly treating the backslashes as literal backslashes and not escapes, e.g. the logs show them both with escapes and without for the following query (from [here](https://github.com/kuzudb/kuzu/actions/runs/6122723770/job/16619119282#step:6:21564)), which as far as I can tell uses a valid windows path:

- `'COPY person FROM "D:\\a\\kuzu\\kuzu\\dataset\\tinysnb/vPerson.csv" (HeaDER=true, deLim=\',\');'` 
- `"COPY person FROM "D:\a\kuzu\kuzu\dataset\tinysnb/vPerson.csv" (HeaDER=true, deLim=',');"`
