### ISSUE TITLE
Benchmark Docker Node Installation Deprecation

### ISSUE THREAD

**Issue by Riolku** [kuzudb/kuzu#2021]
![image](https://github.com/kuzudb/kuzu/assets/41458184/58fabc76-6d82-47f7-b024-7c8ffc1402fa)

The script we use to install node in the benchmark docker container is deprecated, we need to replace it.

**Comment by mewim** [comment]
This seems to be a very recent change. The benchmark container actually does not require Node.js so we can remove the Node.js installation steps. The test container needs Node.js though and we need to migrate the script.

**Comment by Riolku** [comment]
Done in #2163.
