### ISSUE TITLE
Add outlines to documentation pages 

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2061]
Some of our documentation pages are very long: https://kuzudb.com/docusaurus/cypher/ddl and requires scrolling down to different parts. We need to either adopt a template that will create an outline at the top of the page automatically for different sections of the page or break these into multiple pages, so the left panel provides an automatic outline for it.

**Comment by mewim** [comment]
@semihsalihoglu-uw There is an outline at the side generated by the template already:
<img width="1576" alt="Screenshot 2023-09-20 at 6 13 29 PM" src="https://github.com/kuzudb/kuzu/assets/14037726/52c29a26-79ca-4723-9f3d-a6df3557b7ef">

**Comment by semihsalihoglu-uw** [comment]
OK, didn't notice that. Closing this for now.
