### ISSUE TITLE
Parquet reader improvement

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#2080]
Since we don't support reading from remote file system, prefetch mode in parquet reader is disabled by default. Consider enable is when we support reading from more filesystems.

**Comment by prrao87** [comment]
@acquamarin, per [your comment](https://github.com/kuzudb/kuzu/issues/2190#issuecomment-1758669733) on the other issue, I think it makes sense to add another item to this issue? 

- [ ] Support more parquet compression and encodings (e.g., `zstd`) in the upcoming releases
