### ISSUE TITLE
Data type checklist

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu#2170]
Draft issue for now.

This is a checklist to track how well each data type is supported currently in Kùzu, and what's left.

| Data Type | C/C++ | Rust | Python | Java | NodeJS | CopyToCSV | CopyToParquet | CopyFromCSV | CopyFromParquet | Comparison | Casting | aggregation | function | exportToArrow + getArrowSchema |
| ---------- | ------ | ----- | ------- | ----- | -------- | ----------- | --------------- | --------------- | ------------------ | ----- | ------------------ | ----- | ----- | ------ |
| BOOL
| INT64       |             |          | 
| INT32
| INT16
| INT8
| UINT64
| UINT32
| UINT16
| UINT8
| DOUBLE
| FLOAT
| DATE
| TIMESTAMP
| INTERVAL
| FIXED_LIST
| VAR_LIST
| STRING
| BLOB
| STRUCT
| MAP
| UNION
| NODE
| REL
| RECURSIVE_REL
| SERIAL

**Comment by Riolku** [comment]
We should add `getArrowSchema` as a column in this table.

**Comment by ray6080** [comment]
> Nono, I mean the previously untested API function `kuzu_query_result_get_arrow_schema`

Yeah, I mean that is part of the export to arrow feature. but I don't mind being more explicit. Can you make the edit directly in the table?

**Comment by Riolku** [comment]
Updated to add `+ getArrowSchema`.

**Comment by ray6080** [comment]
This is not maintained.
