### ISSUE TITLE
Support simple path patterns in WHERE clause without EXISTS

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#2182]
You often read about WHERE clauses like these in Neo4j documentation:
```cypher
// works in Neo4j
MATCH(t:T) WHERE (t)-[:KIND_OF]->() return t;
MATCH(t:T) WHERE NOT (t)-[:KIND_OF]->() return t;
```
openCypher supports it as well: https://s3.amazonaws.com/artifacts.opencypher.org/openCypher9.pdf -> "Using path patterns in WHERE"; starting at p. 88.

Currently Kuzu errors using this pattern. Example:
```cypher
CREATE NODE TABLE T(name STRING, PRIMARY KEY(name));
CREATE REL TABLE KIND_OF(FROM T TO T);

CREATE (t1:T {name: "T1"}), (t2:T {name: "T2"}), (t3:T {name: "T3"}),
 (t4:T {name: "T4"}), (t1)-[:KIND_OF]->(t2),(t2)-[:KIND_OF]->(t3);
```
```
kuzu> MATCH(t:T) WHERE NOT (t)-[:KIND_OF]->() return t;
Error: Parser exception: Invalid input <MATCH(t:T) WHERE NOT (t)-[:>: expected rule oC_SingleQuery (line: 1, offset: 26)
"MATCH(t:T) WHERE NOT (t)-[:KIND_OF]->() return t"
```

Instead it is required to use `EXISTS`:
```cypher
MATCH(t:T) WHERE NOT EXISTS {MATCH (t)-[:KIND_OF]->()} return t;
```

Please [add above pattern](https://github.com/kuzudb/kuzu/issues/1644) to allowed syntax to make migration from Neo4j easier and be compatible with openCypher.

**Comment by andyfengHKU** [comment]
This is handled in #2429
