### ISSUE TITLE
CREATE REL TABLE with MAP causes "Error: Copy exception: Invalid type for property list creation." + CLI freeze

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#2184]
Works:
```cypher
CREATE NODE TABLE T(name STRING, PRIMARY KEY(name));
CREATE NODE TABLE T2(name STRING, myprops MAP(STRING,STRING), PRIMARY KEY(name));
CREATE REL TABLE KIND_OF(FROM T TO T);
CREATE REL TABLE KIND_OF2(FROM T TO T, mystring STRING);
```
Causes error:
```cypher
kuzu> CREATE REL TABLE KIND_OF3(FROM T TO T, myprops MAP(STRING,STRING));
Error: Copy exception: Invalid type for property list creation.
```
Now subsequent commands afterwards cause CLI freeze/loop:
```
kuzu> MATCH(n) return n;
// CLI freezes / idles
```

(Version: kuzu compiled from today's sources)

**Comment by sapalli2989** [comment]
Hi @ray6080, good to know. Just being curious: Is there a rough ETA for storage rel table rework? Until then, I'd suggest to change error message to something like "Error: MAP, UNION, STRUCT currently are not supported in REL TABLE".

**Comment by ray6080** [comment]
The rework will be done within this month.
For the error message, we do plan to change it in our coming bug fix release so it's more clear.
