### ISSUE TITLE
Query not parallelizing for Bulk Shortest Path queries

### ISSUE THREAD

**Issue by anuchak** [kuzudb/kuzu#2203]
Not sure if anything was recently changed in the Recursive Join operator for parallelizing, but I noticed that for bulk shortest path query we are not morselizing on the BFS sources. For example for this query - 

> MATCH (n1:lj_node)-[r:lj_rel* SHORTEST 1..30]->(n2:lj_node) WHERE n1.id < 1000 return length(r);

![Screenshot from 2023-10-12 16-52-51](https://github.com/kuzudb/kuzu/assets/21187588/34abb778-2175-4caf-88ba-ffa0aaac09a2)

we seem to be running only on 1 thread even though we have 1000 sources and 32 threads.

**Comment by andyfengHKU** [comment]
This is no longer relevant given we are migrating to GDS
