### ISSUE TITLE
Build fails with gcc (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders) 13.2.0

### ISSUE THREAD

**Issue by SunnyYasser** [kuzudb/kuzu#2216]
Hi, I was trying to build the KuzuDB on Windows11  version 22h2 OS build 22621.2283. 

Command used - build clean && build debug

CMake version - Cmake version 3.27.1

I am attaching the log file as well.
[build.log](https://github.com/kuzudb/kuzu/files/12907956/build.log)

**Comment by ray6080** [comment]
Hi @SunnyYasser, thanks for reporting this! Will take a look at this soon.

**Comment by acquamarin** [comment]
Hi @SunnyYasser,
We currently only support compiling with MSVC on windows.

**Comment by SunnyYasser** [comment]
Thanks for your comments, I will try building with MSVC and update. 
@acquamarin , any recommended MSVC version?

**Comment by acquamarin** [comment]
Building with visual studio 2022 is well-tested, so i do recommend install visual studio 2022.
