### ISSUE TITLE
Rename `len()` to `size()` for compatibility with openCypher

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#2218]
Currently Kuzu uses [`len()`](https://kuzudb.com/docusaurus/cypher/expressions/list-functions/) to get the length of a list (and strings). openCypher names this function [`size()`](https://s3.amazonaws.com/artifacts.opencypher.org/openCypher9.pdf#functions-size), which is also the standard in [Neo4j](https://neo4j.com/docs/cypher-manual/current/functions/scalar/#functions-size).

So I guess the suggestion is to just rename function `len` -> `size`.

Related
- https://github.com/kuzudb/kuzu/issues/535
- [is there a way to get length of a string in Neo4j cypher?](https://stackoverflow.com/questions/20324034/is-there-a-way-to-get-length-of-a-string-in-neo4j-cypher)

**Comment by andyfengHKU** [comment]
Hi @sapalli2989, this make sense to me. Will make the change soon.

**Comment by sapalli2989** [comment]
That was fast :-). With the risk of repeating myself, but in this case I gladly do it: Much appreciated!

**Comment by dezren39** [comment]
hi the docs still reference len, how do i update the docs? it would be nice if every page had a link to the markdown so that it's easier to fix things

**Comment by acquamarin** [comment]
Hi,
Here is the URL to the list functions documentation: https://github.com/kuzudb/kuzu-docs/blob/main/docs/cypher/expressions/list-functions.md
Internally, we implement `size()` as an alias of `len()`, so you can add another function called `size()` which is an alias of `len()`
