### ISSUE TITLE
Return variables that bind to deleted or created nodes and rels

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2223]
I have not thought hard about this but one of our users asked if we could return deleted nodes and rels. As I understand currently DELETE and CREATE need to be the final clauses in a query, i.e., we cannot continue the same query with a following MATCH. If we support that and we keep the variables mentioned in CREATE And DELETE in the next clause, we should be able to return deleted and created nodes. For example:

```
MATCH (u:User) 
WHERE u.name = 'Alice'
DELETE u
RETURN u;
```
Could be a way to delete all User nodes with name Alice and then return these nodes. On problem with this is that the query planning needs to ensure that we scan the properties of deleted nodes/rels before they are deleted. Trying to read the properties of deleted nodes after the deletion could lead to scans of those nodes/rels to return NULLs.

**Comment by andyfengHKU** [comment]
This has been supported.
