### ISSUE TITLE
jemalloc vs malloc use (Recursive Joins memory issue)

### ISSUE THREAD

**Issue by anuchak** [kuzudb/kuzu#2226]
The full analysis of the problem is in this doc: https://docs.google.com/document/d/1fZoIx7RjkKuTJn3DVEc8FvaDzm2MkMODBxi-yKs31w8/edit 

Essentially, main problem being observed was that even after query finished execution the final memory Kuzu was consuming was huge. To give an example of a query and its memory consumption - 

> MATCH (n1:lj_node)-[r:lj_rel* 1..5]->(n2:lj_node) WHERE n1.id < 50 AND n2.id > 4847070 return r;
> Query run on LiveJournal
>  138,471 paths 

| Scheduler | Final Memory (GB) (after 5 runs) |
|-----------|----------------------------------|
| nTkS      | 76                               |
| 1T1S      | 105                              |

The 1T1S scheduler is Xiyang's code from master which allots 1 BFS work to 1 thread at a time. I tested on himrod machine (256 GB RAM) with 64 GB buffer manager. Even after high memory consumption was occuring on the machine (230 GB) the allocator was not releasing memory back to the OS - 

![Screenshot from 2023-10-17 15-48-16](https://github.com/kuzudb/kuzu/assets/21187588/0f9b3920-b585-4edf-b86e-d177e3628edb)

After running on jemalloc v5.3.0 with LD_PRELOAD, 

| Scheduler | Runtime (ms) | Peak Memory (GB) | Final Memory (GB)          |
|-----------|--------------|------------------|----------------------------|
| nTkS      | 24847        | 45               | 9.5                        |
| 1T1S      | 86208        | 75.1             | 25 [10.5 after next query] |

Not only does the memory consumption reduce but the runtime also improves, the previous execution time for 1T1S was 227 s for the 1st run and ~110 s for subsequent runs. 

**DuckDB** also has faced this issue when they were using glibc malloc:  **OOM when reading Parquet file**
https://github.com/duckdb/duckdb/issues/3969

They now use jemalloc as an extension while building: **jemalloc "extension" for Linux**
https://github.com/duckdb/duckdb/pull/4971 

For more information: https://www.oracle.com/technical-resources/articles/it-infrastructure/dev-mem-alloc.html 
There are other alternatives such as tcmalloc from Google, Hoard open source allocator etc.

**Comment by semihsalihoglu-uw** [comment]
I know I suggested you open an issue on this but thinking a bit more about this: I think we should do this change only if there are other code lines that use malloc extensively. We are planning using buffer manager-backed memory for recursive joins too to tightly control its memory usage (and error if it overuses memory), so this problem might just disappear.
