### ISSUE TITLE
Not allowing "DETACH DELETE"

### ISSUE THREAD

**Issue by decentropy** [kuzudb/kuzu#2238]
This should be a valid query to simultaneously delete and remove edges, but gives error

MATCH (n:abc) WHERE n.name = 'Test' DETACH DELETE n
error:Parser exception: Query must conclude with RETURN clause (line: 1, offset: 0)

I tried appending "RETURN *", but gives same error

**Comment by andyfengHKU** [comment]
Hi @decentropy, thanks for the reporting. DETACH DELETE is not support in the current version. This feature instead is planned for the next release.

On the other hand, I agree the error message is misleading, we will fix this error message soon.

**Comment by decentropy** [comment]
Okay thanks for response... will close.
