### ISSUE TITLE
Fix path of `0..*` variable-length relationships and align it with Neo4j

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#2244]
Sample case for Kuzu:
```cypher
CREATE NODE TABLE T(id SERIAL, PRIMARY KEY(id));
CREATE REL TABLE CHILD_OF(FROM T TO T);
CREATE (t:T);

kuzu> MATCH p = (t1:T)<-[:CHILD_OF*0..]-(t0:T) return properties(nodes(p),'id');
---------------------------
| PROPERTIES(NODES(p),id) |
---------------------------
| [0,0]                   |
---------------------------
(1 tuple)
```

Sample case for Neo4j:
```cypher
CREATE (t:T);
MATCH p = (t1:T)<-[:CHILD_OF*0..]-(t0:T) return [i in nodes(p) | id(i)]
╒═══════════════════════╕
│[i in nodes(p) | id(i)]│
╞═══════════════════════╡
│[0]                    │
└───────────────────────┘
```

#### Interpretation
A variable-length relationship `0..*` can be interpreted as matching a path with `0` to `n` hops between nodes.
Taking the special case `0..0` for this bug report, it can be regarded as: "match a node without hops/relationships in-between". Following this logic, we get node with id `0` as result here, despite having no existing `CHILD_OF` relationship. In fact the relationship does not matter at all and we could write `(t1:T)<-[:NOT_EXISTING_REL*0..]-(t0:T)` in Neo4j and still retrieve node `0`, 

I would expect `[0]` as output for the matched path, which is Neo4j's result. 
Output of Kuzu currently is `[0,0]`, which does not seem to reflect above quantifier semantics. 

Note: `0..0` is probably not really useful. But this behavior also has influence on results of `0..` relations.

**Comment by andyfengHKU** [comment]
Solved in #2412
