### ISSUE TITLE
Provide command-line option to disable or change path of `history.txt` for Kuzu CLI

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#2245]
`history.txt` is created by kuzu shell and used to record executed shell commands. Unfortunately, users currently aren't allowed to disable it or customize the path.

A typical use case is to navigate to project root directory and execute Kuzu. It will pollute project root with `history.txt`, which might be accidentally added to version control (e.g. Git) as well. 

Suggestion: Provide command-line option to customize handling of  `history.txt`:
1. Disable it completely
2. Set custom path location

Workaround for now: add `history.txt` to `.gitignore` or choose a different working directory.

**Comment by benjaminwinger** [comment]
Is it useful to have different histories for different databases, or should we just store a single history.txt in a standard directory (e.g. `$XDG_STATE_HOME/kuzu` on linux)?

**Comment by sapalli2989** [comment]
@benjaminwinger I guess project history would make sense, as identifiers like table or relation names are mostly specific to one project. What about creating a `history.txt` within database directory and provide a CLI option to overwrite this default with a specific history file location (or a standard one like `$XDG_STATE_HOME/kuzu/history.txt`), if needed?
