### ISSUE TITLE
copying from CSV file with (PARALLEL=false) may get stuck if error is encountered

### ISSUE THREAD

**Issue by russell-liu** [kuzudb/kuzu#2253]
### How to reproduce:
a.csv:
```
a
```
schema.cypher:
```
CREATE NODE TABLE t (id INT64, PRIMARY KEY (id));
```
copy.cypher:
```
COPY t FROM "a.csv";
```
copy2.cypher:
```
COPY t FROM "a.csv" (PARALLEL=false);
```
Executing `cat schema.cypher copy.cypher | path/to/kuzu_shell ./t` creates the table and throws a conversion exception, as expected, but
Executing `cat schema.cypher copy2.cypher | path/to/kuzu_shell ./t2` creates the table and then gets stuck.

**Comment by Riolku** [comment]
The reason this occurs is we don't use exception-safe locks in the `reader`. There might be many more of this kind of bug, sadly. We should ensure that we use exception-safe locks whenever possible.
