### ISSUE TITLE
ListCreation with parameter in preparedStatement.

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#2269]
`conn.prepare(MATCH p = (a:Entity)<-[e:Connection*1..3 ]-(b:Entity) WHERE LIST_CONTAINS([$1], a.id) RETURN p;)`
Binder will blindly binds the type of `[$1]` to `int64[]` because the first parameter `$1` has type `any`. According to the rule:
```
// ListCreation requires all parameters to have the same type or be ANY type. The result type of
// listCreation can be determined by the first non-ANY type parameter. If all parameters have
// dataType ANY, then the resultType will be INT64[] (default type).
```
Binder will resolve type of `[$1]` to `int64[]`, which causes binder exception during execution.

**Comment by andyfengHKU** [comment]
Sovled in #2281
