### ISSUE TITLE
Support hash/comparison operations on var_list and fixed_list

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#2277]
Hash/comparison operations are currently not supported on var_list and fixed_list datatype, which means we are not able to group by/compare a var_list and fixed_list.
For example, we should support such query (group by var_list which computes hash on var_list):
```
match (p:person) return p.workedHours, count(p.ID)
```

Similarly we need to support hashing over nested data types. This issue, which asks for a better error message should be resolved automatically once we support hashing over nested data types: https://github.com/kuzudb/kuzu/issues/2637

**Comment by andyfengHKU** [comment]
Should be done in #3174
