### ISSUE TITLE
Plans to provide a FindKuzu.cmake ?

### ISSUE THREAD

**Issue by jmftrindade** [kuzudb/kuzu#2295]
Hi there!

Any plans for providing a `FindKuzu.cmake`, similar to what the Parquet folks did in [FindArrow.cmakle](https://github.com/apache/parquet-cpp/blob/master/cmake_modules/FindArrow.cmake)?

A `FindKuzu.cmake` would make it a lot easier for folks using cmake based builds to depend on kuzu without having to build it from scratch by e..g, using [`ExternalProject_Add`](https://cmake.org/cmake/help/latest/module/ExternalProject.html) , or make their own Docker container with kuzu and all its deps installed.

Cheers

**Comment by jmftrindade** [comment]
Sure, I can clarify.

Kuzu currently gives the option to use a system installation of Apache Arrow and Parquet here: https://github.com/kuzudb/kuzu/blob/master/CMakeLists.txt#L76C8-L76C24

This triggers the following `find_package` targets in the cmake build:
```
if (${USE_SYSTEM_ARROW})
    find_package(Arrow REQUIRED)
    find_package(Parquet REQUIRED)
```

Kuzu could give a similar option to its users as well by e.g., providing a `FindKuzu.cmake` so that clients can call `find_package(Kuzu REQUIRED)` in their cmake builds. Example corresponding files from both Arrow and Parquet:

[FindParquet.cmake](https://github.com/apache/parquet-cpp/blob/master/examples/parquet-arrow/cmake_modules/FindParquet.cmake)
[FindArrow.cmake](https://github.com/apache/parquet-cpp/blob/master/cmake_modules/FindArrow.cmake)

That way, C++ developers who use cmake builds with Kuzu as a dependency have the option to use their system install not only for Arrow and Parquet, but also for Kuzu. Currently, the ways for C++ devs to depend on Kuzu are:

1) Download a prebuilt lib file with Kuzu and its deps. If they already have Arrow or Parquet in their system, they cannot reuse it as part of their cmake build.
2) Build Kuzu and all its dependencies (using `ExternalProject_Add`), which is super slow as it builds Kuzu + Arrow + Parquet.
3) Still build Kuzu, but skip building Arrow + Parquet by setting `$USE_SYSTEM_ARROW` to true. This is better, in that it allows clients to use their local installs of Arrow + Parquet. However, it still forces clients to build Kuzu.

Does that make more sense?

**Comment by Riolku** [comment]
We're planning on removing Arrow + Parquet in this upcoming release, so this issue should go away :).

**Comment by semihsalihoglu-uw** [comment]
Is this issue resolved? Can we close it? @jmftrindade? @Riolku?

**Comment by Riolku** [comment]
This would be a long term discussion. FindKuzu.cmake is useful only if there is a system install of kuzu, which I imagine is a bit far off.

**Comment by Riolku** [comment]
However, I'd like to know if @jmftrindade was able to easily build now that arrow and parquet are not a dependency.

**Comment by jmftrindade** [comment]
Hey there, thanks for circling back. I was able to build, and I also ended up using `FetchContent_Declare` to make kuzu targets available to the build. Closing it as per discussion above.
