### ISSUE TITLE
INT64 <-> SERIAL conversion fails in Python API

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#2297]
#### Minimal example
```cypher
CREATE NODE TABLE T(id SERIAL, name STRING, PRIMARY KEY(id));
CREATE (t:T {name: "foo"});

kuzu> MATCH (n) RETURN n;
-------------------------------------------
| n                                       |
-------------------------------------------
| {_ID: 0:0, _LABEL: T, id: 0, name: foo} |
-------------------------------------------
```

```python
conn.execute("MATCH (t:T {id: $p}) return t;", {"p": 0})
```

> Traceback (most recent call last):
  File "$HOME/testproj/kuzu_api.py", line 22, in execute
    results = conn.execute("MATCH (t:T {id: $p}) return t;", {"p": 0})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$HOME/testproj/venv/lib64/python3.11/site-packages/kuzu/connection.py", line 90, in execute
    self._connection.execute(
RuntimeError: Parameter p has data type INT64 but expects SERIAL.

#### Workaround
```python
conn.execute("MATCH (t:T {id: to_serial($p)}) return t;", {"p": 0})
```

#### Description
Python `int` seems to be correctly [converted](https://github.com/kuzudb/kuzu/blob/515f778bfd0e34ae3dfd47f1dccd94fdf90ae030/tools/python_api/src_cpp/py_connection.cpp#L167-L168) to `INT64`, but mapping from `INT64` to `SERIAL` isn't right. At least https://github.com/kuzudb/kuzu/issues/1628 states, `SERIAL` internally is just `INT64`.

#### Suggestion
Enhance developer experience by auto-converting `INT64` to `SERIAL` from perspective of (Python) API client.

**Comment by ray6080** [comment]
Hi @sapalli2989 , thanks for reporting this and the suggestion definitely makes sense. we should be able to perform the implicit casting. Will look into this soon.

**Comment by sapalli2989** [comment]
Much appreciated @ray6080 . 

While we are at it 🙂: Do you think it makes sense to add the Python/Kuzu mapping `None` -> `null` as well?
I encountered this, when I wanted to embed an optional value into Kuzu query. `None` type currently is not supported in Prepared statements

**Comment by sapalli2989** [comment]
As side note, `SERIAL` mismatch also happens outside prepared statements. Today same error in combination with `list_contains`:

Manual `INT64` id (works)
```cypher
CREATE NODE TABLE T(id INT64, PRIMARY KEY(id));
CREATE (:T{id:0}),(:T{id:1}),(:T{id:3});
kuzu> MATCH (t:T) WHERE list_contains([0,1], t.id) RETURN t;
--------------------------------
| t                            |
--------------------------------
| {_ID: 0:0, _LABEL: T, id: 0} |
--------------------------------
| {_ID: 0:1, _LABEL: T, id: 1} |
--------------------------------
(2 tuples)
```

`SERIAL` id (doesn't work)
```cypher
CREATE NODE TABLE T2(id SERIAL, PRIMARY KEY(id));
CREATE (:T2),(:T2),(:T2);
kuzu> MATCH (t:T2) RETURN t.*;
--------
| t.id |
--------
| 0    |
--------
| 1    |
--------
| 2    |
--------
(3 tuples)

kuzu> MATCH (t:T2) WHERE list_contains([0,1], t.id) RETURN t;
-----
| t |
-----
(0 tuples)
```

`to_serial()` conversion doesn't work either:
```cypher
kuzu> MATCH (t:T2) WHERE list_contains([to_serial(0),to_serial(1)], t.id) RETURN t;
-----
| t |
-----
(0 tuples)
```

Manual `to_int64()` conversion *does* work:
```cypher
kuzu> MATCH (t:T2) WHERE list_contains([0,1], to_int64(t.id)) RETURN t;
---------------------------------
| t                             |
---------------------------------
| {_ID: 1:0, _LABEL: T2, id: 0} |
---------------------------------
| {_ID: 1:1, _LABEL: T2, id: 1} |
---------------------------------
(2 tuples)
```

**Comment by ray6080** [comment]
Hey @sapalli2989 , sorry for the late reply. The mismatch of SERIAL and INT64 in `LIST_CONTAINS` function should be fixed in https://github.com/kuzudb/kuzu/pull/2621.
We will fix the rest problems in the issue later.

**Comment by sapalli2989** [comment]
This seems to have been solved already:
```python
import kuzu
import tempfile


with tempfile.TemporaryDirectory() as d:
    conn = kuzu.Connection(kuzu.Database(d))
    conn.execute("CREATE NODE TABLE T(id SERIAL, name STRING, PRIMARY KEY(id));")
    conn.execute("CREATE (t:T {name: 'foo'});")
    
    # works
    print(conn.execute("MATCH (t:T {id: $p}) return t;", {"p": 0}).get_next()[0]) 
```

@ray6080 @mewim @acquamarin @hououou Free free to reopen otherwise.
