### ISSUE TITLE
Testing framework currently does not support asserting RETURN result column names

### ISSUE THREAD

**Issue by russell-liu** [kuzudb/kuzu#2308]
The testing framework currently only supports asserting RETURN result tuple values. Consider
```
-STATEMENT RETURN 0 as O;
---- 1
0
```
There is currently no way to verify that the column name is `O`.

**Comment by ray6080** [comment]
This is already supported. See [`-CHECK_COLUMN_NAMES`](https://docs.kuzudb.com/developer-guide/testing-framework/).
