### ISSUE TITLE
Build seems to fail for disk_overflow_file.cpp

### ISSUE THREAD

**Issue by jmftrindade** [kuzudb/kuzu#2318]
This is on v0.0.12. I'm having to build Kuzu from scratch as the pre-compiled library triggers linker errors related to CXX11 strings. The latter can be fixed by using `-D_GLIBCXX_USE_CXX11_ABI=0` in my cmake build, but this causes linkage errors with googletest (another dependency of the project I'm building).

So I'm now building Kuzu together with all other deps in my project by having it setup as a cmake `ExternalProject`, and I get the following build errors on disk_overflow_file.cpp (there's more, but these are the first couple of errors):

```
[ 94%] Building CXX object src/storage/storage_structure/CMakeFiles/kuzu_storage_structure.dir/disk_overflow_file.cpp.o
/root/orb_bkp/build/third_party/kuzu/src/kuzu-project/src/storage/store/compression.cpp:206:31: error: no member named 'bit_width' in namespace 'std'; did you
      mean 'arrow::bit_width'?
    if (min > 0 && max > 0 && std::bit_width((U)(max - min)) < std::bit_width((U)max)) {
                              ^~~~~~~~~~~~~~
                              arrow::bit_width
/root/orb_bkp/build/third_party/kuzu/src/kuzu-project/arrow-build/arrow/install/include/arrow/type_traits.h:1242:19: note: 'arrow::bit_width' declared here
static inline int bit_width(Type::type type_id) {
                  ^
/root/orb_bkp/build/third_party/kuzu/src/kuzu-project/src/storage/store/compression.cpp:206:64: error: no member named 'bit_width' in namespace 'std'; did you
      mean 'arrow::bit_width'?
    if (min > 0 && max > 0 && std::bit_width((U)(max - min)) < std::bit_width((U)max)) {
                                                               ^~~~~~~~~~~~~~
                                                               arrow::bit_width
/root/orb_bkp/build/third_party/kuzu/src/kuzu-project/arrow-build/arrow/install/include/arrow/type_traits.h:1242:19: note: 'arrow::bit_width' declared here
static inline int bit_width(Type::type type_id) {
                  ^
/root/orb_bkp/build/third_party/kuzu/src/kuzu-project/src/storage/store/compression.cpp:208:41: error: no member named 'bit_width' in namespace 'std'; did you
      mean 'arrow::bit_width'?
        bitWidth = static_cast<uint8_t>(std::bit_width((U)(max - min)));
                                        ^~~~~~~~~~~~~~
                                        arrow::bit_width
/root/orb_bkp/build/third_party/kuzu/src/kuzu-project/arrow-build/arrow/install/include/arrow/type_traits.h:1242:19: note: 'arrow::bit_width' declared here
static inline int bit_width(Type::type type_id) {
                  ^
/root/orb_bkp/build/third_party/kuzu/src/kuzu-project/src/storage/store/compression.cpp:210:38: error: no member named 'bit_width' in namespace 'std'; did you
      mean 'arrow::bit_width'?
    } else if (min < 0 && max < 0 && std::bit_width((U)(min - max)) < std::bit_width((U)max)) {
                                     ^~~~~~~~~~~~~~
                                     arrow::bit_width
(...)
```

What's the toolchain currently being used to build Kuzu? This error above is happening with clang++ on Ubuntu 20.04. All my other deps (e.g., googletest, googlebenchmark, googlelog, and antlr4) build as expected. Apache Arrow and Parquet also seem to build correctly (as part of building Kuzu). 

NOTE: [`std::bit_width`](https://en.cppreference.com/w/cpp/numeric/bit_width) is a C++20 feature, so I'm suspecting it might be related, but I already have `SET(CMAKE_CXX_STANDARD 20)` in my root `CMakeLists.txt`, as well as `-std=c++20` on my common build flags. So not sure what's going on exactly, and why Kuzu's build is not picking that up. Happy to share more info (e.g., cmake config command for the Kuzu `ExternalProject_add` target I wrote here) in case that helps.

**Comment by benjaminwinger** [comment]
Our CI currently is testing against GCC 11.4.0, Clang 17.0.4, AppleClang 14.0.3.14030022 and MSVC 19.35.32217.1.

What version of clang are you using? std::bit_width was added in c++20, and features don't get added to compilers all at once, so it's possible that you're using an old version of the compiler that mostly supports c++20 but is missing some features. From [this](https://en.cppreference.com/w/cpp/compiler_support/20) it appears support for std::bit_width was added in clang 12.

**Comment by jmftrindade** [comment]
Alright, thanks for the toolchain info! AFAIK I'm using clang++ v14, though it's a custom one from [OpenCilk](https://github.com/OpenCilk/opencilk-project), and it's a least a year old. Will update to latest and see if that helps. I also noticed on `CMakeError.log` that `-std=gnu++2a` instead of `-std=c++20` (what I have in my root CMakeLists.txt), which is a little odd. Will look more into it and report back, thanks again!

**Comment by jmftrindade** [comment]
Following up on this one, in case other Ubuntu 20.04 users have the same issue, and this might end up being helpful:

- Upgrading to clang++ v17 (and even clang++ v18) did **not** fix the build error. NOTE: I used the LLVM install script at [llvm.org](https://ubuntuhandbook.org/index.php/2023/09/how-to-install-clang-17-or-16-in-ubuntu-22-04-20-04/), which might be related to why it did not fix it.
- [Upgrading g++ to v10](https://askubuntu.com/questions/1263704/how-do-i-install-gcc-10-2-with-sudo-apt-get-install-gcc-x-g-x) **did fix** the build error. Also, upgrading to g++-10 fix the build error for all compilers (g++ and all the clang++ versions I had). So I wonder if the LLVM install script for clang is just not bringing in the appropriate libstd?

Anyway, I used the following program (from [cppreference](https://en.cppreference.com/w/cpp/numeric/bit_width)) to test it:

```
#include <bit>
#include <bitset>
#include <iostream>

int main() {
  for (unsigned x{0}; x != 8; ++x) {
    std::cout << "bit_width( " << std::bitset<4>{x}
              << " ) = " << std::bit_width(x) << '\n';
  }
}
```

And `-std=c++20` for clang++, `-std=c++2a` for g++.

All good now, thanks again for the help!
