### ISSUE TITLE
Remove `isSingleMultiplicityInDirection`

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu#2321]
The function `isSingleMultiplicityInDirection` is used often to determine if the underlying data is stored as a regular column or CSR lists.
```cpp
        return relMultiplicity == RelMultiplicity::ONE_ONE ||
               relMultiplicity == (direction == common::RelDataDirection::FWD ?
                                          RelMultiplicity::MANY_ONE :
                                          RelMultiplicity::ONE_MANY);
```
However, instead of calling this function redundantly, we should simply keep an extra field in table schema to track if each direction is single multiplicity or not.

**Comment by semihsalihoglu-uw** [comment]
Can you say more about this? Why do we need an extra field? Is this a simple refactoring? In general we don't need to keep extra fields if the property that we are interested in is computable from other fields (in this case from relMultiplicity and direction).

**Comment by andyfengHKU** [comment]
This is a pure refactor and has been done.
