### ISSUE TITLE
Extended Cypher toNodesAndRels() Function to Return Distinct Nodes and Rels

### ISSUE THREAD

**Issue by andyfengHKU** [kuzudb/kuzu#2325]
As required by user and internal team members, we need to provide an API/function that can output in graph format instead of tabular format by automatically de-duplicating returned node and relationships. It's unclear what the API will look like at this moment. A detailed design should be updated to this issue.

**Comment by semihsalihoglu-uw** [comment]
I propose we add a new function to Cypher called `toNodesAndRels()`, which takes as input an arbitrary set of arguments (assuming this is doable) and returns a struct[List(Node), List(Rels)]. If we do this as part of query planning, we can have better control over the memory and other resource usages of this conversation when users try to convert large outputs to graphs. Two notes:

1) The output should contain every distinct node and relationship that has bound to one of these three:

- a node variable
- a relationship variable
- a variable length relationship variable (this requires some discussion; see below)
- a path variable.

2) We have the ability to project out properties that will bind to the nodes and relationships of a variable-length relationship pattern. See the description [here](https://kuzudb.com/docusaurus/cypher/query-clauses/match/#project-intermediate-nodes-and-rels).  If a relationship `r` in the database, say between Adam and Karissa, had two properties `p1` and `p2` and the query output projects only one of them, then we have a few things to consider. First, suppose `r` appears only once in the output tuples. How do we output `r`? As a node with a single property `p1`? Or as a node with two properties where `p2` is null? If possible I would advice doing the former, so no nulls. Second, if `r` appears multiple times in the output tuples, then we should merge the properties of `r` correctly. So if in one appearance `r` has the property `p1` and the second time it has the property `p2`, then we should be able to output both of them. This implies that the logic of deduplication may not be as simple as deduplicating and removing a copy as a merge may need be needed for those relationships that appear within a variable length relationship.

Finally, I also prefer if we don't use the name `toGraph()`  or `toSubgraph()` to reserve those words for possible use if we find a way to have a well defined graph/subgraph data type one day.

**Comment by andyfengHKU** [comment]
Since we now have abstract `Graph` class. We will redesign the API around it.
