### ISSUE TITLE
Remove rowIDExpression from logical operators

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#2379]
We should remove rowIDExpression from LogicalInQueryCall, LogicalScanFile since most of the table functions don't need to output the rowID (e.g. STORAGE_INFO, SHOW_TABLES). The rowID expression is currently only needed by the copy operator.

**Comment by semihsalihoglu-uw** [comment]
I labeled this as refactoring but I don't know. @acquamarin should say more about this.

**Comment by andyfengHKU** [comment]
This is duplicate with #3033
