### ISSUE TITLE
A node cannot have more than one relationship

### ISSUE THREAD

**Issue by decentropy** [kuzudb/kuzu#2397]
Create schema... where 'process' can relate to either 'application' or 'information'
```
CREATE NODE TABLE process(name STRING, PRIMARY KEY (name))
CREATE NODE TABLE application(name STRING, PRIMARY KEY (name))
CREATE NODE TABLE information(name STRING, PRIMARY KEY (name))
CREATE REL TABLE uses(FROM process TO application)
CREATE REL TABLE uses(FROM process TO information)
```

Create nodes
```
MERGE (n:process {name: 'budget process'})
MERGE (n:application {name: 'financial app'})
MERGE (n:information {name: 'financial info'})
```

Try to create both relations...
```
MATCH (n1:process), (n2:application) WHERE n1.name='budget process' AND n2.name='financial app' MERGE (n1)-[:uses]->(n2)
MATCH (n1:process), (n2:information) WHERE n1.name='budget process' AND n2.name='financial info' MERGE (n1)-[:uses]->(n2)
```

No matter which order you do the last step, only the first command will work.

**Comment by andyfengHKU** [comment]
Hi @decentropy, this is indeed one of our limitations at DDL level. When I execute the first batch of DDL statements, I did get an exception `Binder exception: uses already exists in catalog.` So I wonder if you check whether `CREATE REL TABLE uses(FROM process TO information)` has been executed successfully or not?

Back to the modelling limitation, I suggest to use multi-label querying instead. 
```
CREATE REL TABLE uses_p_a(FROM process TO application)
CREATE REL TABLE uses_p_i(FROM process TO information)
MATCH (n1)-[e:uses_p_a:|uses_p_i]->(n2) ...
```
Or, if having a single relation over multiple nodes is critical for your use case, you can also take a look at our [rel table group](https://kuzudb.com/docusaurus/cypher/data-definition/create-table#create-rel-table-group). This is an experimental feature that we are still polishing.

**Comment by semihsalihoglu-uw** [comment]
I am assuming there is nothing to do on this issue and closing. I think this is due to having multiple tables with the same name. We do not (and should not) support having tables with the same name.
