### ISSUE TITLE
Implement replacement framework in binder.

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#2404]
In duckdb, when the user tries to query a table which is not defined in the binder, their binder will try to call the replace function to replace the table.
E.g. the user tries to scan from a pandas table which is unknown to the binder, the replacement function will then be called to replace the pandas dataframe with the py::handle pointer.
`LOAD FROM person RETURN *` (where person is a pandas dataframe and not a table name in kuzu). Since the `person` table is unknown to binder, binder will call the replacement function to bind the person label.

**Comment by andyfengHKU** [comment]
This is mostly done in PR #2731
