### ISSUE TITLE
Error casting nested type of maps to string

### ISSUE THREAD

**Issue by AEsir777** [kuzudb/kuzu#2415]
`RETURN cast(cast("{{1=1}={2=2}}", "MAP(MAP(INT64, INT64), MAP(INT64, INT64))"), "STRING");` causes `Assertion failed in file "kuzu/src/common/type_utils.cpp" on line 52: KU_UNREACHABLE`

And after adding 
`case LogicalTypeID::MAP:
        return TypeUtils::toString(*reinterpret_cast<const map_entry_t*>(value), valueVector);` to `type_utils.cpp`
 `Assertion failed in file "kuzu/src/include/common/types/types.h" on line 385: type->getLogicalTypeID() == LogicalTypeID::MAP`

**Comment by andyfengHKU** [comment]
I can no longer reproduce this so I assume the bug has been fixed.
