### ISSUE TITLE
Auto-renaming when two columns in csv file share the same name.

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#2434]
1.csv:
```
a,a
1,3
```
Query:
```
create node table person (id int64, id1 int64, primary key(id));
load from '1.csv' (header=true)
```
Binder needs to rename the second column during conflict.

**Comment by semihsalihoglu-uw** [comment]
@acquamarin: This issue needs a bit more explanation. Specifically, can you explain what happens right now in this situation?
