### ISSUE TITLE
Copy options usability improvements

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#2439]
`Any option that is a Boolean can be enabled or disabled in multiple ways. You can write true, ON, or 1 to enable the option, and false, OFF, or 0 to disable it. The Boolean value can also be omitted (e.g., by only passing (HEADER)), in which case true is assumed.`
We should follow duckdb to make copy option more user friendly.

**Comment by SterlingT3485** [comment]
After overviewed the DuckDB documentation, our desired syntax for options would be: `(NAME '\s'|'=' value_with_default) `.  So we need to compatible with the DuckDB syntax and simultaneously keep our original syntax.  So we need to add not only multiple ways of expressions to boolean value, but also support both empty space and equation sign between the name of option and the value of option.
