### ISSUE TITLE
Reached unreachable code

### ISSUE THREAD

**Issue by benjaminwinger** [kuzudb/kuzu#2469]
I ran into an "unreachable" statement when trying to test something via the query `RETURN db_version();`. Partly this is just me not knowing the syntax (`CALL db_version() RETURN version;` works), but that should probably produce a meaningful error.

> Error: Assertion failed in file "../../../../src/catalog/catalog_content.cpp" on line 222: KU_UNREACHABLE

**Comment by andyfengHKU** [comment]
Fixed in #3284
