### ISSUE TITLE
how to copy from into map/struct field?

### ISSUE THREAD

**Issue by dezren39** [kuzudb/kuzu#2501]
i couldn't quite find the docs which would cover, how do i structure csv/parquet files such that i can import into a table which contains a struct/map? maybe if you had a file that is something like
```
id,name,tags
123,'test','{"name": "test machine 1", "env": "development"}'
```
or it could be normalized like
```
id,name,tags_name,tags_env
123,'test','test machine 1','development'
```
and the underscores become properties?

i can see how this could be an issue and may not have a clean answer, maybe that would be good to clarify in docs.

**Comment by acquamarin** [comment]
Hi,
To copy a map from csv you have to write your values in the following format:
"{key1=val1, key2=val2}"
So in your case, the tags field should be: "{name=test machine 1, env=development}"
To copy a. struct from csv you have to write your values as the following format:
"{field1: val1, field2: val2}"
So in your case, the tags field should be: "{name: test machine 1, env=development}"
For strings, you can either quote it using `"` or `'` or without quote. 

For parquet files, we use the schema to determine the type/layout of each column. As long as the schema specifies the column is a struct/map column, we should be able to load it.

**Comment by ubmarco** [comment]
Hi,
I am also struggling to get data from parquet into a MAP(STRING, STRING).
Currently I am using above approach `"{key1=val1, key2=val2}"`, for that column.

That is quite time consuming for big data sets to prepare as I have to create this string in Python instead of just passing a dictionary or parquet struct and tell KuzuDB to import is as MAP.
I am having difficulties to escape characters such as `,`, `'` and `/`. 
What syntax do I have to use for escaping?

**Comment by acquamarin** [comment]
Hi,

May i know where do you want to escape? Do you mean the python dictionary? Our default escape character is '\'

Thanks

**Comment by ubmarco** [comment]
This is a small example of input data that I have in JSON (or in a Python list):
```json
[
  {
    "id": "id_1",
    "options": {
      "descr": "some ' text",
      "comment": "some other, text"
    }
  },
  {
    "id": "id_2",
    "options": {
      "descr": "some / text 2",
      "comment": "some other, text 2",
      "duration": "3"
    }
  }
]
```

The `id` field is the primary key while `options` should end up as a `MAP(STRING, STRING)` in Kùzu. I don't know the keys in `options` upfront, so `STRUCT` is not an option.
Currently I am ingesting with a polars DataFrame which I write to parquet and then run COPY.
```python
df_pl = pl.DataFrame(
        data={
            "id": ids,
            "options": options,
        },
    )
out_path = Path("data.parquet")
df_pl.write_parquet(out_path)
result = db.conn.execute(f'COPY Need FROM "{out_path}"')
```
The frame has `options` as a list of strings as you describe above
```
"{key1=val1, key2=val2}"
```
This string however is quite brittle as I need to escape some characters, at least the comma `,`. 
I've also had issues with forward slash and single quotes.
My question is, how can I get my data elegantly into Kùzu without doing the string creation magic?
I ran into conversion issues trying out several approaches, a minimal working example would be nice to get a json dictionary into a Kùzu `MAP(STRING, STRING)`

Thanks!

**Comment by ubmarco** [comment]
For anyone coming here, here is a working example how to turn a variable-length dictionary into a `MAP(STRING, STRING)` in Kùzu using parquet. No escaping required. Manually defining the parquet schema does the job.

```python
import pyarrow as pa
import pyarrow.parquet as pq

data = [
    {
        "id": "id_1",
        "options": {
            "descr": "some ' text",
            "comment": "some other, text",
        },
    },
    {
        "id": "id_2",
        "options": {
            "descr": "some / text 2",
            "comment": "some other, text 2",
            "duration": "3",
        },
    },
]

ids = []
options = []

for item in data:
    ids.append(item["id"])
    options.append(list(item["options"].items()))

options_type = pa.map_(pa.string(), pa.string())
table = pa.table(
    {
        "id": pa.array(ids),
        "options": pa.array(options, type=options_type),
    },
)

# Write the table to a parquet file
pq.write_table(table, "example.parquet")

db.conn.execute(f'COPY <Table> FROM "example.parquet"')

```
