### ISSUE TITLE
Python API test_arrow.test is not enabled

### ISSUE THREAD

**Issue by AEsir777** [kuzudb/kuzu#2514]
After renabling, test_to_arrow_complex and test_to_arrow1 fails

**Comment by mxwli** [comment]
More specifically, uncommenting any one of the following lines
```py
    # _test_node(conn)
    # _test_node_rel(conn)
    # _test_marries_table(conn)
```
or calling `test_to_arrow1` inside `test_to_arrow_complex` causes the test to fail.
