### ISSUE TITLE
[Performance, Python] Constant CPU idle load after initializing `kuzu.Database()`

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#2517]
Sample server code:
```python
import kuzu
import time

def main():
    db = kuzu.Database("/tmp/foo")
    db_ro = kuzu.Database("/tmp/foo", read_only=True)
    while True:
        time.sleep(1)
        print("Idle...")

main()
```

After having started above program, I inspected CPU usage with any profiler like `top` in Linux  and noticed a constant, relative higher idle load of 10-20%.

Load  seems to increase per `kuzu.Database()` instantiation call. Initialization of connections by `kuzu.Connection(db)` is not needed to provoke CPU load.

If I comment  
```python
db = kuzu.Database("/tmp/foo")
db_ro = kuzu.Database("/tmp/foo", read_only=True)
```
, usage reduces to nearly zero percent, as expected. Hence this seems to be directly correlated to database bootstrap logic.

System info:
- Kuzu v0.1.0
- Fedora 38

**Comment by ray6080** [comment]
Hi @sapalli2989 , the constant load after initializing `Database` should come from our thread pool. We have a customized thread pool inside the `Database` that will actively check if there is new tasks available from time to time. 
One way to decrease this is we expose a configuration to increase the thread sleeping time, but it can also decrease query performance a bit, especially when they are small, and a bit tricky to tune. So we chose not to expose that.
Hope this can explain the behaviour you observed.

**Comment by sapalli2989** [comment]
Hey @ray6080, OK I see. Looked at `Database` and `Connection` classes in Python, but could not find any `delay` setting for thread sleep time. Is it only configurable from C++ and/or CLI side?

Nevertheless even if that thread pool uses a more aggressive polling mechanism:  Don't you think, 10-20% CPU for just idle is a bit much?  I need both writable and read-only database connections - even with one I get up to 10% usage.

That would mean, if I bundle Kuzu within an app, clients would have constant 10+% CPU usage.

**Comment by ray6080** [comment]
Hi @sapalli2989 . We don't have the delay setting exposed right now. Currently the only way is to set `maxNumThreads`  to a smaller number when opening a database, which also means the thread pool will be limited to a smaller number of threads.
And I agree with your point that the overhead, no matter how much it is, is causing resource waste, especially when multiple databases bundled within user applications.
I will open an issue on this, but before that I need to think a bit on how this can be addressed.
