### ISSUE TITLE
Windows: cmake --install only copies lib and exe in prefix folder, include folder is missing?

### ISSUE THREAD

**Issue by LowLevelMahn** [kuzudb/kuzu#2519]
cmake --install build/release --prefix D:\temp\kuzudb_dev\kuzu_install --strip

usually install with other packages also includes the includes folder

**Comment by Riolku** [comment]
Indeed. This is something we want to fix for the future, but it involves some internal cleanup. We currently recommend users to use our published releases. In the future, we will aim to provide better support for building from source.

**Comment by Riolku** [comment]
@LowLevelMahn , as of #2526, we now build the headers as part of the cmake build. You will need Python 3.9, and we will update the docs on all this shortly.
