### ISSUE TITLE
some problems with the C-API example

### ISSUE THREAD

**Issue by LowLevelMahn** [kuzudb/kuzu#2522]
my kuzu build is from today git, build according to the build docs, windows 10 x64, VS2022

this example: https://kuzudb.com/docusaurus/getting-started/c/

kuzu_database_init gets a nullptr in the example, but it wants a struct as copy(?)

```
// Create an empty database.
    kuzu_database *db = kuzu_database_init("test", 0);
```

```
KUZU_C_API kuzu_database* kuzu_database_init(
    const char* database_path, kuzu_system_config system_config);
```

it seems that someway the pointer get lost for the last parameter, because i think it is more typical to use a pointer here

**Comment by acquamarin** [comment]
Hi,
We recently updated our kuzu_database_init API so the old example no longer works with the new interface.
The second parameter should be a kuzu_system_config struct.
```
// Launch kuzu with 512MB buffer pool size, and 2 threads with compression.
kuzu_system_config config = {.buffer_pool_size = 512 * 1024 * 1024, .max_num_threads = 2, .enable_compression = true, .read_only = false};
 // Create an empty database.
kuzu_database *db = kuzu_database_init("test", config);

```
