### ISSUE TITLE
Make building from source more ergonomic

### ISSUE THREAD

**Issue by Riolku** [kuzudb/kuzu#2523]
Ref #2519. Right now, building from source is difficult for end-users, since we have a lot of internal-only infrastructure setup.

Steps:
- [x] Move header generation into cmake.
- [x] Export headers as part of cmake.
- [ ] Decide whether, and how, language APIs should be installed with cmake.

**Comment by benjaminwinger** [comment]
Also note the [kuzu-git AUR package](https://aur.archlinux.org/packages/kuzu-git): It's out of date, but notably produces headers which are incompatible with both the in-tree headers and the single file release headers. Having headers be generated as part of the install step would help ensure such packages install things in a consistent way.

> Decide whether, and how, language APIs should be installed with cmake.

For python I don't think installation is necessary. We provide a `setup.py` script in `scripts/pip-package` which should be able to be used to build and install the python API.
That said, I'm not sure if it should be running `make clean` if we want it to be user-facing. If we want to clean between CI builds of different wheels we should do that in the CI scripts, not in `setup.py`.

**Comment by Riolku** [comment]
Ref #2526, which addresses the issues with includes. The language API bindings probably don't need to be stripped; at least, it's not a priority.

**Comment by Riolku** [comment]
Complete in #2526. Language API binding cleanup should be done as a separate task.
