### ISSUE TITLE
C-API: Inkonsistent error return behavior

### ISSUE THREAD

**Issue by LowLevelMahn** [kuzudb/kuzu#2528]
Errors are only in some part of the C-API checkable 

for example:

kuzu_connection_query
kuzu_query_result_is_success
kuzu_query_result_get_error_message

others seems to have no error(reporting) output at all - it works, or not

for example

kuzu_database_init - returns nullptr if the path is invalid
kuzu_flat_tuple_get_value - returns nullptr on invalid index
kuzu_value_get_float( value ) - returns 0.0 if the value is a string

makes it maybe hard to find bugs - while my schema is on undergoing changes or my harddisk structure is changing etc.

**Comment by semihsalihoglu-uw** [comment]
I think this looks important. Our ability to return error statuses in APIs in general seems like a problem that we should solve in a more general way.

**Comment by mewim** [comment]
We will change the function signatures for C API. Instead of directly return the pointer we return a status code for operators that might fail. We should also implement a function which can output meaningful error messages based on error code. The list of errors needs to be determined.

**Comment by LowLevelMahn** [comment]
> We should also implement a function which can output meaningful error messages based on error code

yes please, as expressive as possible (not like sqlites better-then-nothing error messages without any context information)

**Comment by mewim** [comment]
#3133 addresses most of this. Currently all C-API functions that may fail returns a `kuzu_state` of `0` or `1`. As mentioned in #1655, we will later add more error codes to cover specific errors. I will close this for now.
