### ISSUE TITLE
VS2022 in IDE build fails with antlr4_runtime, easy fixable and then working in IDE

### ISSUE THREAD

**Issue by LowLevelMahn** [kuzudb/kuzu#2537]
build Kuzu from VS2022 IDE

```
mkdir kuzu_dev
git clone https://github.com/kuzudb/kuzu.git
mkdir _build
cd _build
cmake -G "Visual Studio 17 2022" -A x64 ..\kuzu
then open resulting Kuzu.sln in VS2022 IDE and build
```

build will fail with antlr4_runtime library due to combination of Optimization /O2 + Basic Runtime Checks with /RTC1
all other libs build

so i take a look at the antrl4_cypher CMakeLists.txt and this one missing this part from the antrl4_runtime CMakeLists.txt

```
if ("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
    if(MSVC)
        target_compile_options(${ANTLR4_RUNTIME} PRIVATE
            /W4 /Od
        )
    else()
        target_compile_options(${ANTLR4_RUNTIME} PRIVATE
            -g -Wall -O0
        )
    endif()
else()
    if(MSVC)
        target_compile_options(${ANTLR4_RUNTIME} PRIVATE
            /O2
        )
    else()
        target_compile_options(${ANTLR4_RUNTIME} PRIVATE
            -w -O3
        )
        target_compile_options(${ANTLR4_RUNTIME} PUBLIC
            -Wno-attributes
        )
    endif()
endif()
```

it seems that this if/else stuff selects the wrong build settings for Debug, but only for this lib

Kuzu builds fully in IDE if set the optimization the the antlr4_runtime to No optimization /O0

![image](https://github.com/kuzudb/kuzu/assets/580819/53d50b9d-6ee7-422a-9163-144667eb1f43)

btw: compiles and run out of the box with QtCreator IDE 12.x

![image](https://github.com/kuzudb/kuzu/assets/580819/ad5f65b9-61e4-42dd-93fa-221e9b01d820)

**Comment by Riolku** [comment]
> Kuzu builds fully in IDE if set the optimization the the antlr4_runtime to No optimization /O0

What do you mean by this? How are you setting the optimization level?

As I understand it, `/Od` and `/O0` are equivalent on MSVC.

Why would it work out of the box on QtCreator if it fails in Visual Studio?

**Comment by LowLevelMahn** [comment]
> What do you mean by this? How are you setting the optimization level?

for testing by hand to /0d to not conflict with /RTC1
 
> As I understand it, `/Od` and `/O0` are equivalent on MSVC.

yes, but cmake sets currently wrongly /O2 (which conflict with /RTC1) - i don't see whats wrong here - the cmake script seems not wrong - but all other libs have /0d only this lib got /O2

> Why would it work out of the box on QtCreator if it fails in Visual Studio?

will check that again

**Comment by Riolku** [comment]
> yes, but cmake sets currently wrongly /O2 (which conflict with /RTC1) - i don't see whats wrong here - the cmake script seems not wrong - but all other libs have /0d only this lib got /O2

Agreed... can you paste the full command line?

**Comment by LowLevelMahn** [comment]
> can you paste the full command line?

of what?

this is how i create the Vs2022 solution (sln) file for Kuzu

```
mkdir kuzu_dev
git clone https://github.com/kuzudb/kuzu.git
mkdir _build
cd _build
cmake -G "Visual Studio 17 2022" -A x64 ..\kuzu
then open resulting Kuzu.sln in VS2022 IDE and build
```

**Comment by Riolku** [comment]
> yes, but cmake sets currently wrongly /O2 (which conflict with /RTC1) - i don't see whats wrong here - the cmake script seems not wrong - but all other libs have /0d only this lib got /O2

Based on this, I figured you knew for sure that the command line for ANTLR got /O2.

I can't reproduce this on linux... the command line looks correct. I don't have a windows machine on me ATM to test. Does everything work if you do a debug build with cmake from the command line? Maybe this is a VS2022 specific issue?

**Comment by benjaminwinger** [comment]
I think the difference is the visual studio generator. Unlike the other generators, that allows multiple different build configurations to be build side-by-side (like we do manually in the makefile with separate build and release directories).

In that context, `CMAKE_BUILD_TYPE` just shouldn't be used, as it will often be incorrect with the visual studio generator.

I'd actually looked at supporting that generator a while ago, but never finished (I think because of arrow, but since we've removed that it's likely simpler to get this working). The following patch I seem to recall fixed this part. I haven't verified that; it's out of my git stash from months ago, but it replaces the `CMAKE_BUILD_TYPE` comparison with generator expressions that should work with the visual studio generator.

```
diff --git a/third_party/antlr4_runtime/CMakeLists.txt b/third_party/antlr4_runtime/CMakeLists.txt
index 8684bd167..2772a1ddf 100644
--- a/third_party/antlr4_runtime/CMakeLists.txt
+++ b/third_party/antlr4_runtime/CMakeLists.txt
@@ -324,27 +324,17 @@ if (WIN32)
 endif()


-if ("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
-    if(MSVC)
-        target_compile_options(${ANTLR4_RUNTIME} PRIVATE
-            /W4 /Od
-        )
-    else()
-        target_compile_options(${ANTLR4_RUNTIME} PRIVATE
-            -g -Wall -O0
-        )
-    endif()
+if(MSVC)
+    target_compile_options(${ANTLR4_RUNTIME} PRIVATE
+        $<$<CONFIG:Debug>:/W4 /Od>
+        $<$<CONFIG:Release>:/O2>
+    )
 else()
-    if(MSVC)
-        target_compile_options(${ANTLR4_RUNTIME} PRIVATE
-            /O2
-        )
-    else()
-        target_compile_options(${ANTLR4_RUNTIME} PRIVATE
-            -w -O3
-        )
-        target_compile_options(${ANTLR4_RUNTIME} PUBLIC
-            -Wno-attributes
-        )
-    endif()
+    target_compile_options(${ANTLR4_RUNTIME} PRIVATE
+        $<$<CONFIG:Debug>:-g -Wall -O0>
+        $<$<CONFIG:Release>:-w -O3>
+    )
+    target_compile_options(${ANTLR4_RUNTIME} PUBLIC
+        $<$<CONFIG:Release>:-Wno-attributes>
+    )
 endif()
```

**Comment by LowLevelMahn** [comment]
> > yes, but cmake sets currently wrongly /O2 (which conflict with /RTC1) - i don't see whats wrong here - the cmake script seems not wrong - but all other libs have /0d only this lib got /O2

when i create the VS2022 solution with cmake and build insider IDE i get the error that the antlr_runtime lib is incompatible with some other settings, so building in IDE fails because of this lib, i see in the IDE lib properties that /O2 is active - which fails with /RTC1 - all other libs are correctly /0d (happens also when create an VS2019 solution)

> I can't reproduce this on linux... the command line looks correct. I don't have a windows machine on me ATM to test. Does everything work if you do a debug build with cmake from the command line? Maybe this is a VS2022 specific issue?

```
open "x64 Native Tools Command Prompt for VS 2022"
make debug NUM_THREADS=8
```
works with no build problems -> creates kuzu_shared.dll

in IDE the configuration is invalid for antrl4_runtime

![image](https://github.com/kuzudb/kuzu/assets/580819/03634a54-598e-47cf-b326-a7efb580c1b9)

but ok for all others, for example antrl4_cypher 

![image](https://github.com/kuzudb/kuzu/assets/580819/a529d803-8c1c-4546-a13d-65e938b2221c)

the only difference i see is that the antrl4_runtime sets explicitly the optimization flags and antrl4_cypher does not

usually i can switch between serveral make systems, compilers with my other projects - so building on console with Ninja, make, or IDE, msys2, linux is not a problem - im doing that on daily basis and with CI, normaly there is some tiny bug in the cmake configuration that creates such errors, many developers using CMake + VStudio, even Qt6 and several other big 3rd parties are buildable using this way (and also on console)

and yes, QtCreator still builds out of the box directly using the CMakeLists.txt from the root (using VS2019)

no idea what is wrong

**Comment by Riolku** [comment]
@LowLevelMahn Can you try the patch proposed above by @benjaminwinger ?

**Comment by LowLevelMahn** [comment]
> @LowLevelMahn Can you try the patch proposed above by @benjaminwinger ?

yes, that is a good description whats happening - i don't know why the QtCreator doesnt suffer from this
best is to do these less as possible localy - derive them from the main CMakeList.txt if possible

yes the patch makes it build in debug (release still fails linking) - but its already better with the patch

btw: you should not handle warnings different in debug or release - both should have full warning level (you can get different warnings)

**Comment by Riolku** [comment]
ANTLR4 is a third-party project. We don't generally modify imported code like this too too much, as it's at best a distraction from more pressing matters.

In our own code we don't handle warnings differently. ANTLR4 is probably doing this configuration so that building in release mode doesnt present warnings to users. Whether that makes sense or not is not really up to us.

**Comment by LowLevelMahn** [comment]
> ANTLR4 is a third-party project. We don't generally modify imported code like this too too much

the CMakeLists.txt is only from Kuzu - the original CMakeLists.txt from the ANTRL project in the cpp runtime src is completely different - so Kuzu is in full control here :)

**Comment by LowLevelMahn** [comment]
builds works for Debug/Release

FYI: there are >700 Warnings uint8_t <-> bool conversion etc., uint64->int32 cast etc.
way too much to be just ignored (gcc and clang should be even more stressy with these code lines)
