### ISSUE TITLE
`IS NULL` does not work properly for `OPTIONAL MATCH`

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#2558]
Possibly related: https://github.com/kuzudb/kuzu/issues/2294

Minimal example
```cypher
CREATE NODE TABLE T(id STRING, PRIMARY KEY(id));
OPTIONAL MATCH (b {id: "non existent id"}) RETURN b is NULL;
```

- Kuzu returns `false` (`NULL` in KuzuExplorer tableview)
- Neo4 returns `true`, which should be correct result.

JSON view result from KuzuExplorer:
```json
{
  "rows": [
    {
      "IS_NULL(b)": false
    }
  ],
  "dataTypes": {
    "IS_NULL(b)": "BOOL"
  },
  "isSchemaChanged": true
}
```

This become more apparent with post-processing of boolean result:

```cypher
OPTIONAL MATCH (b{id: "non existent id"}) RETURN CASE WHEN b is NULL THEN "foo" ELSE "bar" END;
```
- Kuzu returns "bar"
- Neo4j returns "foo" (expected)

**Comment by acquamarin** [comment]
Should be solved in #2560
