### ISSUE TITLE
Support `-v`/`--version` flag in Kuzu CLI

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#2565]
It would be nice to have a `-v`/`--version` flag to quickly output installed Kuzu CLI version, as provided in many command line tools.

A related (but more involved) instruction is
```
kuzu> CALL db_version() RETURN *;
```
, but it needs an existing database and takes more steps. Also if I understand correctly, database version and CLI program version are two different things. So a CLI flag could help to detect version mismatches.
```
kuzu -v
```

**Comment by ray6080** [comment]
Hey @sapalli2989 , this is a nice suggestion. currently we don't differentiate the version of CLI and database, as you are actually starting a database when you start the CLI. but definitely should provide a `-v` (`--version`) option so no bother with `CALL db_version() RETURN *;`.
