### ISSUE TITLE
Segmentation fault for `STRUCT`

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#2572]
Accidentally using the JSON or Python dict format for `STRUCT` will result in a Segmentation fault error:
```
kuzu> RETURN {"foo": "bar"};
```
(instead of)
```
kuzu> RETURN {foo: "bar"};
```

**Comment by andyfengHKU** [comment]
@sapalli2989 This should be fixed in #2582. Thanks for reporting!
