### ISSUE TITLE
Query returns inconsistent results with multiple runs

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#2578]
### Minimal example

![screenshot](https://github.com/kuzudb/kuzu/assets/147163559/9ac0eb04-a53c-4664-9bf7-4129da4162d7)

The idea is to return all longest paths down to the leaf node, given some parent node (`parentid`) and max-depth as user input. Paths  begin with the immediate children of `parentid`. User can also provide `NULL` as input. This means to return all paths starting with the very top nodes.

E.g. 
- `parentid` = `NULL` and max-depth 0 returns `["t1"]`, `["t2"]` and `["t3"]`
- `parentid` = `t1` and max-depth 0 returns `["t11"]`, `["t12"]` and `["t13"]`
- `parentid` = `t1` and max-depth 1 returns `["t11", "t111"]`,`["t11", "t112"]`, `["t12"]`, `["t13"]`

and so on. Third one will be the reference case in this issue.

### Graph reconstruction
```cypher
CREATE NODE TABLE T(id STRING, PRIMARY KEY(id));
CREATE REL TABLE CHILD_OF(FROM T TO T);

CREATE (t1:T {id: "t1"}),
 (t11:T {id: "t11"}),
 (t12:T {id: "t12"}),
 (t13:T {id: "t13"}),
 (t111:T {id: "t111"}),
 (t112:T {id: "t112"}),
 (t1111:T {id: "t1111"}),
 (t2:T {id: "t2"}),
 (t21:T {id: "t21"}),
 (t22:T {id: "t22"}),
 (t3:T {id: "t3"}),
 (t1111)-[:CHILD_OF]->(t111),
 (t111)-[:CHILD_OF]->(t11),
 (t112)-[:CHILD_OF]->(t11),
 (t11)-[:CHILD_OF]->(t1),
 (t12)-[:CHILD_OF]->(t1),
 (t13)-[:CHILD_OF]->(t1),
 (t21)-[:CHILD_OF]->(t2),
 (t22)-[:CHILD_OF]->(t2);
```

### Query

```cypher
// user input
WITH "t1" as parentid
// max-length here 1; also consider single leaf nodes by 0..
MATCH p = (t1:T)<-[e:CHILD_OF*0..1]-(t0:T)
// handle NULL and non-NULL user input for parent node id
WHERE CASE
  WHEN parentid IS NULL THEN NOT EXISTS {MATCH (t1)-[:CHILD_OF]->(:T)}
  ELSE EXISTS {MATCH (t1)-[:CHILD_OF]->(:T {id: parentid})}
END
// Either return path, when child is leaf or max-depth is reached
AND (NOT EXISTS {MATCH (:T)-[:CHILD_OF]->(t0)} OR length(e) = 1)
// just get me the node ids
RETURN properties(nodes(p),'id');
```
Notes:
`WITH "t1" as parentid` is the prepard statement value from user input, which is modeled as static here (`WITH NULL as parentid` can be used for paths starting with top nodes). max-depth is enforced by `*0..1` in `[e:CHILD_OF*0..1]` and `length(e) = 1`, as quantifier cannot be set via prepared statement. I'd like to keep the `CASE` construct, which works for `NULL` and non-`NULL input - considering a single static query is more native and non-redundant than needing to change it via string manipulation via programming language.

### Results

First query run resulted in 
```
---------------------------
| PROPERTIES(NODES(p),id) |
---------------------------
| [t1,t112]               |
---------------------------
| [t1,t111]               |
---------------------------
| [t1,t11]                |
---------------------------
| [t1,t12]                |
---------------------------
| [t1,t13]                |
---------------------------
| [t1,t1111]              |
---------------------------
| [t1,t111]               |
---------------------------
| [t1,t112]               |
---------------------------
| [t1,t1111]              |
---------------------------
| [t1,t21]                |
---------------------------
| [t1,t22]                |
---------------------------
(11 tuples)
```

, which already seems strange. Result of second run:
```
---------------------------
| PROPERTIES(NODES(p),id) |
---------------------------
| [t1]                    |
---------------------------
| [t1]                    |
---------------------------
| [t1]                    |
---------------------------
| [t1]                    |
---------------------------
| [t1]                    |
---------------------------
| [t1]                    |
---------------------------
| [t1]                    |
---------------------------
| [t1]                    |
---------------------------
(8 tuples)
```

doesn't make sense to me either. Above two results are returned in random order (looks like a concurrency problem?). If I replace `CASE` construct by
```
WHERE EXISTS {MATCH (t1)-[:CHILD_OF]->(:T {id: parentid})}
```
for static `parentid` = `t1` case, the result at least is consistent - but still seems wrong:
```
---------------------------
| PROPERTIES(NODES(p),id) |
---------------------------
| [t11,t112]              |
---------------------------
| [t11,t111]              |
---------------------------
| [t12]                   |
---------------------------
| [t13]                   |
---------------------------
| [t111,t1111]            |
---------------------------
| [t112]                  |
---------------------------
| [t1111]                 |
---------------------------
| [t21]                   |
---------------------------
| [t22]                   |
---------------------------
(9 tuples)
```

In comparison, Neo4j returns all results as expected. Which lead me to the conclusion, that query declaration itself is valid.
To try queries out in Neo4j you can replace `RETURN properties(nodes(p),'id');` by `RETURN [i in nodes(p) | i.id];` and `length(e)` by `size(e)`.

Sorry for the bit more involved example. Feel free to ask, if you have any questions left.

**Comment by andyfengHKU** [comment]
Hi @sapalli2989, a fix is now available in PR #2581
