### ISSUE TITLE
BinderException on OPTIONAL MATCH handles Kuzu from returning non-empty results 

### ISSUE THREAD

**Issue by joyemang33** [kuzudb/kuzu#2635]
Hello here!
When executing the following query with ```OPTIONAL MATCH```, Kuzu will raise a Binder Exception:
```cypher
MATCH (n) OPTIONAL MATCH (n)-[*..0]-() RETURN COUNT(*)
```
This query should not be handled from execution because it should return all nodes even though the ```OPTIONAL MATCH``` clause can not find anything.

I noticed that the root cause may be related to the schema inspection for the ```OPTONAL MATCH```, and it would be highly appreciated if you could further confirm and investigate it.

I also noticed that Kuzu could ban the query such like `MATCH (n)-[*0..0]-(m) RETURN *` in the future.

Best regards,
Qiuyang

**Comment by andyfengHKU** [comment]
Hi @joyemang33 thanks for reporting. This is indeed a bug that doesn't comply with OPTIONAL MATCH semantic.

**Comment by andyfengHKU** [comment]
This should be fixed in #3506
