### ISSUE TITLE
Better error message for aggregation over nested data type.

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2637]
I have not tested this but this came up when we were having a discussion on the use of hash tables and ability to hash structs. Apparently we do not return an error message that clearly explains that the aggregation is not supported in the frontend. If I'm not mistaken, the error is also thrown during query execution and not compilation. We should fix this.

This is a simple issue and assigning it to a few people who might do it quickly.

**Comment by andyfengHKU** [comment]
Instead of giving better error message, we should probably just support hashing and comparing nested data types.

**Comment by semihsalihoglu-uw** [comment]
Agreed. Eventually, we should do that but until then, we should just quickly fix this to give a better error message.

**Comment by andyfengHKU** [comment]
We now support hash & compare over nested types.
