### ISSUE TITLE
Metadata isn't always accurate when scanning

### ISSUE THREAD

**Issue by benjaminwinger** [kuzudb/kuzu#2647]
I noticed this when adding an assertion in `string_column.cpp` checking that scans don't go past the number of values as stored in the metadata, which caused `EmptyCreateNodeTest.CreateStructWithWriteTransaction` to fail. The issue isn't causing test failures by itself as the data is intact, and in this case the missing metadata isn't a problem (evidently the metadata for the string data column is correct since the number of values is used to determine the end of last string).

```diff
diff --git a/src/storage/store/string_column.cpp b/src/storage/store/string_column.cpp
index 1c4815113..3da1409de 100644
--- a/src/storage/store/string_column.cpp
+++ b/src/storage/store/string_column.cpp
@@ -28,6 +28,7 @@ StringColumn::StringColumn(std::string name, std::unique_ptr<LogicalType> dataTy
 
 void StringColumn::scanOffsets(Transaction* transaction, const ReadState& state,
     string_offset_t* offsets, uint64_t index, uint64_t numValues, uint64_t dataSize) {
+    KU_ASSERT(index + numValues <= state.metadata.numValues);
     // We either need to read the next value, or store the maximum string offset at the end.
     // Otherwise we won't know what the length of the last string is.
     if (index + numValues < state.metadata.numValues) {
@@ -215,6 +216,7 @@ void StringColumn::scanFiltered(transaction::Transaction* transaction,
         auto pos = nodeIDVector->state->selVector->selectedPositions[i];
         if (!resultVector->isNull(pos)) {
             // TODO(bmwinger): optimize index scans by grouping them when adjacent
+            KU_ASSERT(pos < indexState.metadata.numValues);
             auto offsetInGroup = startOffsetInGroup + pos;
             string_index_t index;
             Column::scan(
```

Additionally, more failures occur when adding bounds checks to the primitive Column code. I haven't looked at those failures as closely, but as one example: `DeleteRelTest.deleteRelsFromOneToOneTableRollbackNormalExecution` is failing when querying after rolling back the previous transaction and beginning a new one (but in this case no changes have been made in the new transaction):
```diff
diff --git a/src/storage/store/column.cpp b/src/storage/store/column.cpp
index 9be02ceed..c8de29315 100644
--- a/src/storage/store/column.cpp
+++ b/src/storage/store/column.cpp
@@ -460,6 +460,7 @@ void Column::scanInternal(
     auto cursor = getPageCursorForOffset(transaction->getType(), nodeGroupIdx, offsetInChunk);
     auto chunkMeta = metadataDA->get(nodeGroupIdx, transaction->getType());
     if (nodeIDVector->state->selVector->isUnfiltered()) {
+        KU_ASSERT(offsetInChunk + nodeIDVector->state->selVector->selectedSize <= chunkMeta.numValues);
         scanUnfiltered(transaction, cursor, nodeIDVector->state->selVector->selectedSize,
             resultVector, chunkMeta);
     } else {
@@ -500,6 +501,7 @@ void Column::scanFiltered(Transaction* transaction, PageElementCursor& pageCurso
                 numValuesToScan - numValuesScanned);
         if (isInRange(nodeIDVector->state->selVector->selectedPositions[posInSelVector],
                 numValuesScanned, numValuesScanned + numValuesToScanInPage)) {
+            KU_ASSERT(nodeIDVector->state->selVector->selectedPositions[posInSelVector] < chunkMeta.numValues);
             KU_ASSERT(isPageIdxValid(pageCursor.pageIdx, chunkMeta));
             readFromPage(transaction, pageCursor.pageIdx, [&](uint8_t* frame) -> void {
                 readToVectorFunc(frame, pageCursor, resultVector, numValuesScanned,
```

(patches are for commit aa2d017378ab44)

The following tests trigger the assertions:
```
        960 - TinySnbReadTest.CastDataTypeToString (Failed)
        1064 - CreateRelTest.insertRelsToOneToOneRelTableRollbackRecovery (Failed)
        1065 - CreateRelTest.insertRelsToOneToOneRelTableRollbackNormalExecution (Failed)
        1130 - DeleteRelTest.deleteRelsFromOneToOneTableRollbackRecovery (Failed)
        1131 - DeleteRelTest.deleteRelsFromOneToOneTableRollbackNormalExecution (Failed)
        1132 - DeleteRelTest.deleteRelsFromOneToOneTableCommitRecovery (Failed)
        1133 - DeleteRelTest.deleteRelsFromOneToOneTableCommitNormalExecution (Failed)
        1180 - UpdateRelTest.updateOneToOneRelTableRollbackRecovery (Failed)
        1181 - UpdateRelTest.updateOneToOneRelTableCommitRecovery (Failed)
        1182 - UpdateRelTest.updateOneToOneRelTableRollbackNormalExecution (Failed)
        1183 - UpdateRelTest.updateOneToOneRelTableCommitNormalExecution (Failed)
        1245 - TinySnbDeleteNodeTest.DeleteNodeMultiLabel1 (Failed)
        1255 - EmptyCreateNodeTest.CreateStructWithWriteTransaction (Failed)
        1272 - EmptyCreateRelTest.CreateAndScanOneToOneRel (Failed)
        1273 - EmptyCreateRelTest.CreateOneToOneRelOnLargeNodeTable (Failed)
        1275 - EmptyCreateRelTest.CreateOneToOneRel (Failed)
        1281 - TinySnbDeleteRelTest.OptionalMatchDelete (Failed)
        1285 - TinySnbMergeRelTest.MergeOneToOne (Failed)
        1289 - TinySnbSetReadRelTest.OptionalSetReadTest (Failed)
        1300 - NodeInsertionDeletionTests.InsertManyNodesTest (Failed)
```

**Comment by benjaminwinger** [comment]
> The issue isn't causing test failures by itself as the data is intact, and in this case the missing metadata isn't a problem (evidently the metadata for the string data column is correct since the number of values is used to determine the end of last string).

Looking into it further, the metadata for the data column is also incorrect. Nothing is actually being scanned from the disk in this test, and I think it's passing because it's afterwards being scanned from local storage. 

https://github.com/kuzudb/kuzu/blob/383a8db91c8aa409adeeafeb31fa1c531df8f670/src/storage/store/node_table_data.cpp#L34-L53

I think the real issue is that for write transactions, we scan first from the disk, even for values which haven't been written to the disk yet, and then scan from local storage on top of the data scanned from disk. This is generally fine for simple data types. For strings there are two cases:
1. No values have been written yet, so it scans an empty string since the index is zero, the offset is zero, and the numValues is zero, meaning it scans zero characters starting from the beginning of the data chunk (and hits these assertions because it's scanning out of bounds on the index and offset).
2. Strings have been written previously. The index of the out of bounds read is zero, so it scans the first string in the dictionary even though it's not the correct string.

Nether should produce invalid data though. I think that really the only actual issue with this is that it's unintuitive that we're scanning values which haven't been written yet, which could lead to bugs if we're not careful.
For example, if there are arbitrary non-zero values in the string offset/index chunks, they could cause underflows when the offsets are used to calculate string lengths resulting in hangs or crashes when we read the strings. However as long as the unused data is all zeroed that shouldn't occur.

**Comment by ray6080** [comment]
This is not relevant now.
