### ISSUE TITLE
RuntimeError: _Map_base::at When execute MATCH clause with redundant node 

### ISSUE THREAD

**Issue by joyemang33** [kuzudb/kuzu#2701]
Hi! The following query will cause a strange exception in Kuzu, i.e., `RuntimeError: _Map_base::at`
```Cypher
MATCH (n1), (n2)<-[]-(n2), (n1)<-[]-(n2) RETURN COUNT (*)
```
I also have further investigated the case. If I remove the redundant (n1) in the pattern, Kuzu will successfully return the result.

Your help in further confirming and investigating this bug will be highly appreciated.

The graph data for reproduction is as follows:
[G.zip](https://github.com/kuzudb/kuzu/files/14010367/G.zip)

Best regards,
Qiuyang

**Comment by andyfengHKU** [comment]
Hi @joyemang33, thanks for reporting. The bug should now be fixed in PR #2702
