### ISSUE TITLE
Parquet: provide better error message when handling unsupported data structures

### ISSUE THREAD

**Issue by prrao87** [kuzudb/kuzu#2709]
Related to https://github.com/kuzudb/kuzu/issues/2703

This issue described how when we have nested data (e.g., structs or lists) within  parquet columns, trying to use `COPY FROM` results in a segfault. It's only when the user either flattens the data themselves, or converts the nested data to a string, that the load happens without error.

From a usability perspective to provide an error message informing the user that "Nested data structures in parquet not supported", and add tests for the same on our end.

**Comment by acquamarin** [comment]
The bug that the user reported is not raised by the parquet reader, the copy operator raised the exception due to a bug. 
Nested datatypes (e.g. Lists and structs) are already supported in the parquet reader(except union).  I am waiting for the user for more info.
