### ISSUE TITLE
Better error message for not supporting multi-label node queries

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2753]
We support multi-label relationship queries but not multi-label node queries. The error we give when one tries is not explicit:

```
kuzu> MATCH (a:UniKG_r|UniKG_l) RETURN *;
Error: Parser exception: Invalid input <MATCH (a:UniKG_r|>: expected rule oC_SingleQuery (line: 1, offset: 16)
"MATCH (a:UniKG_r|UniKG_l) RETURN *"
```

**Comment by andyfengHKU** [comment]
We do support multi-label node queries. The syntax is in-correct because the `|` should be replaced `:`.

Try `MATCH (a:UniKG_r:UniKG_l) RETURN *;`
