### ISSUE TITLE
RDF Base IRIs not working

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2765]
According to the [RDF Turtle file specification](https://www.w3.org/TR/turtle), some IRIs can be specified as relative IRIs against a base IRI. The [specification of relative IRIs](https://www.w3.org/TR/turtle/#relative-iri) is as follows:

> [IRIs](http://www.w3.org/TR/rdf11-concepts/#dfn-iri) may be written as relative or absolute IRIs or prefixed names. Relative and absolute IRIs are enclosed in '<' and '>' and may contain [numeric escape sequences](https://www.w3.org/TR/turtle/#numeric) (described below). For example <http://example.org/#green-goblin>.
>
> Relative IRIs like <#green-goblin> are resolved relative to the current base IRI. A new base IRI can be defined using the '@base' or 'BASE' directive. Specifics of this operation are defined in [section 6.3 IRI References](https://www.w3.org/TR/turtle/#sec-iri-references)

So for example, if you ingest the triples in the example in the specification:

```
@base <http://example.org/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix rel: <http://www.perceive.net/schemas/relationship/> .

<#green-goblin>
    rel:enemyOf <#spiderman> ;
    a foaf:Person ;    # in the context of the Marvel universe
    foaf:name "Green Goblin" .

<#spiderman>
    rel:enemyOf <#green-goblin> ;
    a foaf:Person ;
    foaf:name "Spiderman", "Человек-паук"@ru .
```
You would get for <#green-goblin>, "http://example.org/#green-goblin". We currently ingest these as "#green-goblin".

**Comment by andyfengHKU** [comment]
Fixed in PR #2784
