### ISSUE TITLE
Kuzu not recognizing variable in ORDER BY

### ISSUE THREAD

**Issue by mxwli** [kuzudb/kuzu#2766]
In this query:
```
MATCH (p:Person {id: 0}), (friend:Person {firstName: "A"})
       WHERE NOT p.id=friend.id
       WITH p, friend
       MATCH path = (p)-[:KNOWS* SHORTEST 1..3]-(friend)
RETURN min(length(path)) AS distance, friend
ORDER BY
    distance ASC,
    friend.lastName ASC,
    to_int64(friend.id) ASC
LIMIT 20
```

Kuzu doesn't recognize `friend.lastName`: `Binder exception: Order by expression friend.lastName is not in RETURN or WITH clause.`

Interestingly, removing the second MATCH clause
```
MATCH (p:Person {id: 0}), (friend:Person {firstName: "A"})
       WHERE NOT p.id=friend.id
RETURN friend
ORDER BY
    friend.lastName ASC,
    to_int64(friend.id) ASC
LIMIT 20
```
works just fine.

**Comment by mxwli** [comment]
update: it appears that this bug occurs specifically when we return a table in its entirety alongside some group by aggregate. For example,
```
MATCH (p:Person)
RETURN p, count(p.id)
ORDER BY p.id;
```
triggers this bug as well.

**Comment by semihsalihoglu-uw** [comment]
Technically this is expected behavior though Xiyang might still have a plan to support this. This may also be related to this: https://github.com/kuzudb/kuzu/issues/1212.

**Comment by mxwli** [comment]
I'm not sure if it's related to #1212. neo4j supports this query, and the query doesn't order by an internal ID. Here, the schema is
```
CREATE NODE TABLE Person(id int64, PRIMARY KEY(id));
```

**Comment by semihsalihoglu-uw** [comment]
Anyways, let me not comment actually. Xiyang must have thought about what to do here.

**Comment by andyfengHKU** [comment]
This has been fixed.
