### ISSUE TITLE
Multilabel relationship pattern not working when a db has more than 1 RDFGraph

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2769]
I have 2 RDFGraphs in my database: TurtleEx and UniKG. The following gives a binder error:
```
kuzu> MATCH (a:UniKG_r {iri: "http://kuzu.io/rdf-ex#FooBar"})-[p]->(o) RETURN *;
Error: Binder exception: Relationship pattern p with multiple rdf table labels is not supported.
```
If I drop TurtleEx, then the query works as expected. I don't think there is a good reason the above query is not supported.

**Comment by andyfengHKU** [comment]
Fixed in #2788
