### ISSUE TITLE
Enable Prism Syntax Highlighting For Cypher in Documentation Pages

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2770]
Currently the code blocks we use on our documentation pages do not do any syntax highlighting. For some languages, such as sql, you can annotate the code block after the three " \` " characters you use to start a code block to trigger some syntax highlighting. Such as:
\`\`\`sql
SELECT * FROM Employee
\`\`\`
will render it as below.
```sql
SELECT * FROM Employee
```
Apparently the syntax highlighting feature of docusaurus is powered by https://github.com/FormidableLabs/prism-react-renderer, which has a set of pre-bundled language support. And prism claims to have Cypher support as per https://prismjs.com/. I tried adding the "cypher" annotation but it does not seem to trigger. Let us try to find how to trigger this.

I also tried adding "sql" annotation to some Cypher code blocks and most keywords highlight for Cypher as well. Since we have several of our own syntax that extends Cypher, such as RDFGraph or COPY, we should either solve this in a way where we have the flexibility to also highlight our own syntax or we just use sql.

**Comment by prrao87** [comment]
This has been resolved with the migration of the docs to Astro.js. We support Cypher syntax highlighting, including DDL. See below for examples.

![image](https://github.com/kuzudb/kuzu/assets/35005448/74909846-4435-4f49-9cae-52e9c3316864)

![image](https://github.com/kuzudb/kuzu/assets/35005448/9e9a3975-340a-4013-af57-ec1a34d4997a)

**Comment by prrao87** [comment]
Technically, `COPY` isn't a Cypher statement (it's more like SQL) so that's why the `COPY` keyword doesn't highlight the same color as `CREATE` (which is valid Cypher). But I think this is good behaviour, as the user shouldn't think that `COPY` is something that's from openCypher.
