### ISSUE TITLE
Error on malformed IRIs in Turtle files

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2771]
According to Turtle specification, you cannot do the following (you can use the W3 [Validata](https://www.w3.org/2015/03/ShExValidata/) tool to see this error):

```
@prefix ex: <http://example.org/> .

<ex:green-goblin>
    foo:enemyOf ex:spiderman	
```
That's because the prefix "foo" is not defined. We however interpret this as if foo:enemyOf  is written as <foo:enemyOf>, which indicates that the string inside the angle brackets is a fullIRI and should be interpreted as such. That is, we interpret it as if the file was as follows:

```
@prefix ex: <http://example.org/> .

<ex:green-goblin>
    <foo:enemyOf> ex:spiderman	
```

Then if you query the rdfgraph for the triples you get the following:
```
----------------------------------------------------------------
| s.iri           | p.iri       | o.iri                        |
----------------------------------------------------------------
| ex:green-goblin | foo:enemyOf | http://example.org/spiderman |
----------------------------------------------------------------
```

I think we should comply with the standard and error on this line (and skip the triple if that's what we do).

**Comment by andyfengHKU** [comment]
Fixed in PR #2800
