### ISSUE TITLE
Better error message for query with two CREATE statements

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2779]
I was trying the following on the RDFGraphs and wrote this query, but I can't understand the error message:

```
kuzu> WITH "http://kuzu.io/rdf-ex#" as kz, "http://www.w3.org/1999/02/22-rdf-syntax-ns#" as rdf 
..> MATCH (s:UniKG_r {iri: kz+"Nour"})
..> CREATE (s)-[p:UniKG_rt {iri: rdf + "type"}]->(o:UniKG_r {iri: kz + "student"})
..> RETURN *;
Error: Cannot evaluate expression with type PROPERTY.
```
This is after I create an RDFGraph UniKG and insert the uni.ttl turtle file with the set of triples shown the example database in RDFGraphs documentation. 

If I remove the RETURN  statement things work.

**Comment by andyfengHKU** [comment]
Sovled in #2806
