### ISSUE TITLE
Removing pid of R-R and R-L relationship tables in RDFGraphs as a visible property to users

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2781]
The internalID type pid property of the R-R and R-L relationship tables is a system-level optimization. When users query them, they are unable to query them because of binding errors that are confusing or they get confusing outputs. For example:

```
MATCH (a)-[p:UniKG_rt]->(o) 
WHERE a.iri = "http://kuzu.io/rdf-ex#Adam" 
RETURN p.pid;

Output:
--------------------------
| p.pid                  |
--------------------------
| 18446744073709551615:1 |
--------------------------
| 18446744073709551615:9 |
--------------------------
```
Above, 18446744073709551615 looks like a NULL placeholder value. Or:
```
MATCH (a)-[p:UniKG_rt]->(o) 
WHERE a.iri = "http://kuzu.io/rdf-ex#Adam" AND p.iri = " http://kuzu.io/rdf-ex#age" 
SET p.pid=7 RETURN a.iri, p.iri, o.iri;
Error: Binder exception: Expression 7 has data type INT64 but expected INTERNAL_ID. Implicit cast is not supported.
```
Instead we should explicitly say that pids should not be queried and modified.

Instead, we have a feature that you can call an `iri` property on these relationships. In reality these relationship tables do not have iri properties but we internally don't trigger binding errors because we would like users to query and obtain string IRIs. So we can do this:

```
MATCH (a)-[p:UniKG_rt]->(o) 
RETURN p.iri

Output:
---------------------------------------------------
| p.iri                                           |
---------------------------------------------------
| http://kuzu.io/rdf-ex#livesIn                   |
---------------------------------------------------
| http://kuzu.io/rdf-ex#bornIn                    |
---------------------------------------------------
...
```
Or:
```
kuzu> MATCH (a)-[p:UniKG_lt]->(o)  
WHERE p.iri = "http://kuzu.io/rdf-ex#age" 
RETURN a.iri, p.iri, o.val;
------------------------------------------------------------------
| a.iri                      | p.iri                     | o.val |
------------------------------------------------------------------
| http://kuzu.io/rdf-ex#Adam | http://kuzu.io/rdf-ex#age | 30    |
------------------------------------------------------------------
```
But when a user looks at these tables, they see this:
```
kuzu> call table_info('UniKG_lt') return *;
------------------------------------
| property id | name | type        |
------------------------------------
| 1           | pid  | INTERNAL_ID |
------------------------------------
```

This behavior is confusing. I think we should just hid pid completely from the user. That is the following should be our behavior:
- Do not show pid in table schema in `table_info('UniKG_lt')` function calls. Instead show an iri property with STRING . You can also say "(virtual)" next to string.
- Any reference to pid should trigger a binding error.
- When relationship objects from these are returned, we can keep the pid property if this is quite a bit of work but ideally we can remove this feature from the objects as well.

**Comment by andyfengHKU** [comment]
Solved in #2840
