### ISSUE TITLE
Validating IRIs as a configuration

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2783]
We currently have 2 ways to ingest triples into RDFGraphs. First is through Turtle files. Second is through CREATE statements. We however have different behaviors when given IRIs are not valid IRIs. Specifically our behavior is as follows:
- If there is a triple and any of the subject, predicate, or objects contains an invalid IRI, our Turtle parser will skip the entire "chunk" of the IRI triple, i.e. a block of triples with the same subject in the Turtle file. Therefore it is not possible to insert invalid IRIs through Turtle file.
- In contrast, we accept arbitrary strings through CREATE statements (e.g., strings with spaces between them).

I am frankly not sure what is the right thing to do here. I think accepting arbitrary strings has the advantage that people who want to model their data as triples has more flexibility and do not need to worry about their identifiers are valid or malformed IRIs (e.g., you can use a "firstname lastname" type IRIs with spaces between them). On the other hand that would mean that if we are part of a pipeline that then exports RDFGraphs out of Kuzu and puts into another system, they may not be able because we export invalid IRIs.

The three options are:
1. Keep things as is and see if this is important
2. Force IRIs to always be valid. So have a function that checks if an IRI is valid and call it upon inserting IRIs.
3. Have a configuration that gives two options: (i) forces IRIs to be valid; or (ii) allows IRIs to be arbitrary strings.

**Comment by andyfengHKU** [comment]
I tried validating URI through SERD but it doesn't seem to behave as expected (meaning invalid URI is still being parsed). So supporting this will most likely be non-trivial work and I suggest we wait.

**Comment by andyfengHKU** [comment]
Close due to #4289
