### ISSUE TITLE
Exporting RDF Literal Node Table to Different Formats (specifically the VARIANT data type)

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2785]
Currently VARIANT data type is only supported as part of the Literal Node Table. You cannot create normal tables with VARIANT data type and therefore ingest CSV or PARQUET data. However you can still export the Literal table. We should figure out how to export VARIANT data type to different formats, such as CSV, Parquet and any other format we support. 

We should also test how our integrations with networkx or pyg or any other integrations behave with Literal table.

Also: Let's test if we can use Variant in Python, Java, Rust, and C++. Can we read them correctly for each data type that it supports?

**Comment by acquamarin** [comment]
All apis have support of rdf variant, and we can also export rdf variant to csv.
Exporting to parquet, arrow will result in an exception
