### ISSUE TITLE
xsd prefix is not recognized in Turtle file when parsing RDF literals

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2790]
I was doing some debugging to double check that the data types of RDF literals are parsed correctly. I have the following file:

```
@prefix kz: <http://kuzu.io/rdf-ex#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

kz:Waterloo a kz:City ;
            kz:name "Waterloo" ;
            kz:population 10000.0 ;
            kz:population2 "20000.0"^^xsd:decimal ;
            kz:foundedIn "30000"^^<http://www.w3.org/2001/XMLSchema#decimal> .
```

Copying this into an RDFGraph will result in the following set of triples:
```
---------------------------------------------------------------------------------------------------
| a.iri                          | p.iri                                           | o.val        |
---------------------------------------------------------------------------------------------------
| http://kuzu.io/rdf-ex#Waterloo | http://kuzu.io/rdf-ex#name                      | Waterloo     |
---------------------------------------------------------------------------------------------------
| http://kuzu.io/rdf-ex#Waterloo | http://kuzu.io/rdf-ex#population                | 10000.000000 |
---------------------------------------------------------------------------------------------------
| http://kuzu.io/rdf-ex#Waterloo | http://kuzu.io/rdf-ex#population2               | 20000.0      |
---------------------------------------------------------------------------------------------------
| http://kuzu.io/rdf-ex#Waterloo | http://kuzu.io/rdf-ex#foundedIn                 | 30000.000000 |
---------------------------------------------------------------------------------------------------
| http://kuzu.io/rdf-ex#Waterloo | http://www.w3.org/1999/02/22-rdf-syntax-ns#type |              |
---------------------------------------------------------------------------------------------------
```
So the behavior is this:
- 10000.0 is automatically, by the parser, recognized and tagged as xsd:decimal (or xsd:double).
- 20000.0 is recognized as string (this is the bug, it should be recognized as xsd:decimal). This is because the RDFUtils::getLogicalTypeID function sees the string xsd:decimal instead of http://www.w3.org/2001/XMLSchema#decimal, which is what it should be expanded to because I have the `@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .` prefix at the top. 
- 30000.0 is recognized as xsd:decimal

First we should recognize prefix namespaces in literal datatype tags as well. Second, I think we should recognize xsd in datatype tags even if the prefix xsd is completely missing. I tested this in GraphDB and they do recognize xsd even if its missing (though they do recognize rdf, rdfs, and owl too). 

If you prefer: do not recognize xsd without the prefix for now and instead open an issue to have a configuration to support common namespaces including this. If you choose this, make sure you take a note reminding not to forget the xsd prefix and to add tests for it when parsing literal data types.

**Comment by andyfengHKU** [comment]
Solved in #2807
