### ISSUE TITLE
Support more RDF Literal Types

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2791]
In the documentation for Variant, I said that Variant data type can only be integer, double, decimal, boolean, date. This is inaccurate. 

These are the data types that we can currently parse from Turtle files for RDF Literals.  
```
static constexpr std::string_view XSD_integer = "integer";
static constexpr std::string_view XSD_double = "double";
static constexpr std::string_view XSD_decimal = "decimal";
static constexpr std::string_view XSD_boolean = "boolean";
static constexpr std::string_view XSD_date = "date";
```
We should support more data types.

We should also edit our documentation for Variant type when we add more data types.

**Comment by andyfengHKU** [comment]
Close due to #4289
