### ISSUE TITLE
Wrong error message when setting object in an RDF Literal table

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2792]
I issued the following query:
```
kuzu> MATCH (a)-[p:TurtleTest_lt]->(o) 
WHERE p.iri = "http://kuzu.io/rdf-ex#population" 
SET o.val=cast(true, "BOOL") 
RETURN p.iri, o.val;  
Error: Binder exception: Cannot set property of o because it refers to table TurtleTest_r under rdf graph TurtleTest.
```
o must be in TurtleTest_l not TurtleTest_r. 

So is it the case now that we cannot modify anything in RDFGraphs? First, I think we can allow them to set literals. I think that's fine. But if this is much easier, so we force them to delete and insert triples, then we should just give a better error message. Something like: `Error: Binder exception: Cannot set properties of RDFGraph tables. You are trying to set o.val but o is part of table TurtleTest_l under RDFGraph TurtleTest.`

Also Let's use the term RDFGraph instead of "rdf graph", which is what you have used in the error message.

**Comment by andyfengHKU** [comment]
Fixed in PR #2800
