### ISSUE TITLE
Enable mixing RDFGraph label and PropertyGraph label in relationship pattern

### ISSUE THREAD

**Issue by mewim** [kuzudb/kuzu#2798]
On latest master (https://github.com/kuzudb/kuzu/tree/0df0b28), running a path query after creating a RDFGraph causes SEGFAULT.

OS: macOS 14.3

Steps to reproduce:
1. Load `tinysnb` into an empty database:
```bash
cat dataset/tinysnb/schema.cypher |  ./build/release/tools/shell/kuzu_shell ../test
cat dataset/tinysnb/copy.cypher |  ./build/release/tools/shell/kuzu_shell ../test
```

2. Launch the shell:
```
./build/release/tools/shell/kuzu_shell ../test
```
Then run the following queries:
```
MATCH (a:person)-[e*1..1]->(b:organisation) WHERE a.fName = 'Alice' RETURN e;
CREATE RDFGraph T;
MATCH (a:person)-[e*1..1]->(b:organisation) WHERE a.fName = 'Alice' RETURN e;
```

The first `MATCH` query goes through, but the second one after creating the RDFGraph causes SEGFAULT.

**Comment by andyfengHKU** [comment]
We disabled the feature of combining RDFGraph rel table with PropertyGraph rel table. So this should no longer be segfault. However, we should consider enable this feature in the near future.

**Comment by andyfengHKU** [comment]
Close due to #4289
