### ISSUE TITLE
Inconsistent behavior for binder error

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2804]
I have an RDFGraph named wklx. I am running the following query:
```
match (s:wklx_r)-[p:wklx_rt]->(o) return s.iri, p.iri, o.iri, o.val limit 10;
```
This does not give a binding error and instead prints a val column with null values. I was expecting it because o can only be of type wklx_r and that does not have val property. If I specify the type, then I get a binding error.
```
match (s:wklx_r)-[p:wklx_rt]->(o:wklx_r) return s.iri, p.iri, o.iri, o.val limit 10;
Error: Binder exception: Cannot find property val for o.
```
It's not clear if we should give a binder error or but I think a smart system would by resolving the possible types first. My bigger worry is that if we are not doing such type resolutions, we might end up doing unnecessary joins (e.g., by scanning both wklx_r and wklx_l tables to bind to o). That is I can imagine not doing type resolutions correctly can decrease performance significantly in some cases.

**Comment by andyfengHKU** [comment]
The above behaviour seems expected to me.

> match (s:wklx_r)-[p:wklx_rt]->(o)
For above query, user is trying to match both resource and literal table for `o`, so `o.val` should exist in return columns. 

> match (s:wklx_r)-[p:wklx_rt]->(o:wklx_r)
For this query, user is trying to match only resource table, so `o.val` cannot pass a semantic check during binding.

Label resolution is an orthogonal optimization that we did internally and is hidden from end user. In either case, we don't scan literal table.
