### ISSUE TITLE
Add a new command to cli to print the current shell configuration

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2805]
I am often in a state where I want to see the state of my configuration for shell after I run a query. That is I want to know what are the current numThreads or timeout. We should have a command (something like "print_configs" that will print out any of the configurable parameters from the shell. Currently these include: :thread, :timeout, and logging_level.

**Comment by andyfengHKU** [comment]
try `CALL current_setting("threads") RETURN *`
