### ISSUE TITLE
Update error message of mixing RDFGraph and regular Property graph table

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2811]
If I query this on a database with an RDFGraph and regular relationship tables I get the following error message:

```
..> match (a)-[e]->(b) return *;
Error: Binder exception: Relationship pattern e contains both property graph relationship label st_to_r and RDFGraph label TurtleTest. Mixing two tables in the same relationship pattern is not supported.
```
Let's change the error message to: `... Mixing relationships tables from an RDFGraph and regular relationship tables in one pattern is currently not supported.`

**Comment by andyfengHKU** [comment]
Solved in #2836
