### ISSUE TITLE
Enable `.nt` file storage

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2814]
N-Triples files are valid Turtle files. They are the simplest of RDF formats where each triple is written one one line and without any prefix or base directives/shortening (so each IRI is written as full IRIs) and no grouping of triples by subject as in Turtle. Currently if I do this, I get an error:

```
kuzu> copy wklx from "/home/lc/Developer/semih/rdf-data/wiki-data/latest-lexemes-nt.nt";
Error: Copy exception: Unsupported file type .nt
```

However if I rename the file to `latest-lexemes-nt.ttl` then the loading works. I also tested that the Turtle and N-Triple version of the latest Wikidata lexemes dataset gives similar counts (not exact but very close).

**Comment by andyfengHKU** [comment]
Solved in #2836
