### ISSUE TITLE
Disable DELETING of Resource Nodes or Delete all of the dangling edges as well

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#2817]
If I delete a Resource r that is being used as a predicate, it leaves the predicate "dangling". That results in inconsistent behavior. For example, if you issue a query that accesses for the iris of predicates that refer to r, then those triples are excluded from the results. If you modify the same query to access the pid instead, those triples start emerging.

We should either:
Option 1. Disable DELETING of Resource nodes. So Resource node table is append-only. 
Option 2: We delete all of the triples that refer to r as well. 

I suggest we do Option 1 for now. Then we can switch to Option 2 if we think we can find it, which looks difficult to implement and support. Option 2 also seems it would be very slow for simple deletions because it seems to require that you scan all of the rt and lt triples to find those that refer to the deleted resources and delete them. So if you delete 1 resource from the database, you end up scanning the entire database.

Tentatively, I'm writing the documentation saying Resource nodes cannot be deleted.

**Comment by andyfengHKU** [comment]
Solved in #2836
