### ISSUE TITLE
Key missing from map causing assertion failure

### ISSUE THREAD

**Issue by mxwli** [kuzudb/kuzu#2822]
The following queries:
```
CREATE NODE TABLE Forum (creationDate  TIMESTAMP, id INT64, title STRING, PRIMARY KEY(id));
CREATE NODE TABLE Tag (id INT64, name STRING, url STRING, PRIMARY KEY(id));
CREATE REL TABLE HAS_TAG (FROM Forum TO Tag, creationDate TIMESTAMP, MANY_MANY);
MATCH (tag:Tag {name: "tag name"}), (forum1:Forum)
MATCH (forum1)
WHERE (forum1)-[:HAS_TAG]->(tag)
RETURN *;
```
causes an assertion failure in `src/planner/operator/schema.cpp:57` where a map doesn't have a key that it should. Specifically, it appears to be looking for the _ID of tag. This occurs in the last WHERE clause. neo4j considers this a valid query.

**Comment by andyfengHKU** [comment]
This has been fixed.
