### ISSUE TITLE
Docs: Add clarifications for LIST data type DDL specifications

### ISSUE THREAD

**Issue by d33bs** [kuzudb/kuzu#2823]
Thanks for the great work on this project! I wanted to open a suggestion for [documentation surrounding the LIST data type](https://kuzudb.com/docusaurus/cypher/data-types/list) which I thought might help clarify usage. 

Currently the beginning of this page reads:

```markdown
Kùzu supports two `LIST` data types: variable-size list `VAR-LIST` and fixed-size `FIXED-LIST`.

A `VAR-LIST` type can contain arbitrary number of values with the same type.

A `FIXED-LIST` type can contain fixed number of values with the same numerical type.
```

This could be improved with an additional statement concerning the use of other datatypes (any data type?) before the brackets in DDL. Additionally, it looked like there was a typo concerning the FIXED-LIST content ("same numerical type", not certain but it seems like this should be "same type").

```markdown
Kùzu supports two LIST data types: variable-size list `VAR-LIST` and fixed-size `FIXED-LIST.`

`LIST` data types include values of a single data type.
The data type of values within a `LIST` is declared before a set of brackets in DDL.
For example, `STRING[]` declares a `LIST` of string values.

A `VAR-LIST` type can contain arbitrary number of values with the same type.

A `FIXED-LIST` type can contain fixed number of values with the same type.
```

It might be that the following content is inferred from other, more comprehensive documentation about the DDL grammar. Please don't hesitate to correct or link to a better resource instead of the below. Thank you!

**Comment by semihsalihoglu-uw** [comment]
Thank @d33bs for the suggestion. Indeed, let's clarify this.

**Comment by acquamarin** [comment]
yes, we do allow nested lists datatype.
For example: you want to create a table with a list of list of int64 property:
You can write ddl as:
```
create node table person (ID INt64, courseScoresPerTerm INT64[][], PRIMARY KEY (ID));

```
We support list of any datatypes.

**Comment by semihsalihoglu-uw** [comment]
This is fixed in this: https://github.com/kuzudb/kuzu-docs/pull/70.
