### ISSUE TITLE
Implement cypher predicate functions

### ISSUE THREAD

**Issue by manh9203** [kuzudb/kuzu#2841]
Neo4j supports these two functions which helps checking constraints and applying an aggregation on list in some Fintech complex read queries
```
https://neo4j.com/docs/cypher-manual/current/functions/predicate/#functions-all
https://neo4j.com/docs/cypher-manual/current/functions/list/#functions-reduce
```

**Comment by acquamarin** [comment]
I think you mean `all` instead of `add` right?

**Comment by acquamarin** [comment]
https://neo4j.com/docs/cypher-manual/current/functions/predicate/#functions-all
Docs can be found there

**Comment by manh9203** [comment]
Yes, that's what I mean. I mistyped it.

**Comment by andyfengHKU** [comment]
This has been implemented as list lambda
