### ISSUE TITLE
Elements in Empty List Resolving to STRING by Default Causes Issues

### ISSUE THREAD

**Issue by mxwli** [kuzudb/kuzu#2874]
If we write a query like this:
```
UNWIND $idList as tid MATCH (t:tag {id: tid}) RETURN t;
```
Where id expects an INT64 type, the query runs fine on a non empty $idList. However, when we have idList = `[]`, then the query gives
```
Expression tid has data type STRING but expected INT64. Implicit cast is not supported.
```

**Comment by andyfengHKU** [comment]
Should be fixed in #3374
