### ISSUE TITLE
Master test open too many files

### ISSUE THREAD

**Issue by andyfengHKU** [kuzudb/kuzu#2894]
My local machine has ulimit 256 and when I run `make test` it starts complaining `too many opened files`. I assume this partially because we open 64 files in order to parallel hash index. But still 256 should be sufficient to run tests.

P.S. I'm labelling this as a bug for now. Feel free to change if this is expected.

**Comment by benjaminwinger** [comment]
This was a regression in #2857. I overlooked that the `InMemFile` used for storing strings independently opens the file for writing, so going from one to 256 of them meant it's now opening 256 files. It shouldn't be an issue for them to share a file descriptor.
