### ISSUE TITLE
Support reading from remote turtle file

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#2909]
The turtle file reader is a third-party library which uses the linux fopen directly without using our vfs.
We should refactor turtle reader using our vfs so we can support reading from remote turtle files.

**Comment by andyfengHKU** [comment]
We need to hold this for a while because we are using a third party reader and propagating our FileSystem into that library is not trivial.

I suggest we error while pulling turtle file from remote.

**Comment by semihsalihoglu-uw** [comment]
I think this should be prioritized. @acquamarin can you look into how this could be done?

**Comment by andyfengHKU** [comment]
Close due to #4289
