### ISSUE TITLE
Allow specifying PRIMARY KEY after the column definition in CREATE NODE TABLE statements

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu#2911]
Currently, we only allow specifying `PRIMARY KEY` constraint at the end of `CREATE NODE TABLE` statements.
An example:
```
CREATE NODE TABLE person(id INT64, age INT64, name STRING, PRIMARY KEY(id));
```

We should also allow specifying the constraint after column definition as SQL does:
```
CREATE NODE TABLE person(id INT64 PRIMARY KEY, age INT64, name STRING);
```

**Comment by andyfengHKU** [comment]
Fixed in #4314
