### ISSUE TITLE
Potential REL TABLE GROUP data ingest bugs with COPY (Python)

### ISSUE THREAD

**Issue by d33bs** [kuzudb/kuzu#2920]
This issue is a continuation of thoughts based on guidance provided through #2866. Specifically, I was able to use REL TABLE GROUP but experienced what I thought might be bugs and wanted to follow up with feedback. Thank you again for the kind help and comments along the way, I found it very helpful!

I've created a demonstration of potential bugs here: https://github.com/d33bs/demo-kuzu-rel-table-group-potential-bugs . Please see the readme instructions for specifics in terms of how I used Kuzu to create tables and then copy data from Parquet files. As a sidenote, I accept that I might just be using Kuzu wrong - if this is the case, please don't hesitate to let me know!

The bugs I found during development related to this code were:

### 1. Segmentation faults during COPY operations of REL TABLE GROUP Tables.

The repo linked above should be able to reproduce this on running the Poe the Poet task. These segmentation faults seemed to occur for REL TABLE GROUP's with many distinct node type pairs, though I didn't see this happen deterministically. The faults appeared to occur for me regardless of using MacOS or Ubuntu, and also didn't appear to be effected by increasing the amount of memory resources available to the system. I found that when I re-ran the COPY statement which seemed to cause the segmentation fault that it would often succeed. This led me to a simple brute-force workaround which looped through processing the data until it successfully completed (via excepting for additional `RuntimeError`'s, similar to below).

Open questions here: 

- Is there a way to increase the documentation provided during these types of segmentation faults to help inform the user?
- When re-running a COPY command which caused a segmentation fault, is there any concern about data integrity, or is this built into existing Kuzu validation procedures?

### 2. Missing NODE primary key ID's when ingesting large amounts of REL TABLE GROUP Table data.

I could not reproduce this within the repo linked above but wanted to make mention of this in case it's helpful for further work or insights. I found that when ingesting large amounts of REL table data using the COPY command that Kuzu would sometimes report missing primary key ID's which had already been ingested through NODE table COPY's. When this occurred I found that re-running the COPY for the REL table would succeed the second time around. As a result I implemented a simple workaround to retry the COPY on catching the `RuntimeError` message `"Unable to find primary key value"` (see `demo.kz_copy.kz_execute_with_retries` for more here).

Thoughts and suggestions:

- Did this perhaps occur due to latency issues in terms of Python and Kuzu interconnection or processing? If so, is there a way to guarantee a primary key ID is available to quickly occurring COPY commands issued from Python?
- I'd recommend providing a custom `Exception` class for these errors to help catch them within Python (or other languages) to help developers leverage a class name instead of a message string for scenarios like this.

Please don't hesitate to let me know if you have any questions on the above, or if I may somehow clarify. Thank you for any thoughts, suggestions, or comments you may have on fixes here!

**Comment by ray6080** [comment]
Hi, for "Missing NODE primary key ID", can you take a look at this issue (https://github.com/kuzudb/kuzu/issues/2916)? Is it similar to what you encountered?

**Comment by ray6080** [comment]
I've reproduced the first bug “Segmentation faults during COPY operations of REL TABLE GROUP Tables." Thanks for helping with reproducing. The problem lies in our COPY rel string properties. Will update here once we have a fix.

On questions:
> Is there a way to increase the documentation provided during these types of segmentation faults to help inform the user?

I don't see a practical way for us to catch segmentation faults and replace it with a meaningful error message. Possible future solutions is to provide a way to report the stack trace, but that will mostly only be useful for debugging for developers.

> When re-running a COPY command which caused a segmentation fault, is there any concern about data integrity, or is this built into existing Kuzu validation procedures?

We have built-in transaction support for COPY, so that means corrupted COPY data should not be visible and data integrity should be fine.

**Comment by d33bs** [comment]
Thanks @ray6080 for all the great comments and help with this! 

I'm unable to reproduce the bug currently for "2. Missing NODE primary key ID's" but the issue you highlighted looks similar. I didn't attempt using different amounts of threads so it's possible that would be the fix when this occurs again. I'll give this a try the next time it occurs.

Glad to hear you were able to find a bug with the segmentation faults and that there is transaction support with Kuzu! I'd love to see the capability at some point to view the stack trace easily. This might help with issues similar to this one, where you could ask that someone provides portions of the trace alongside other troubleshooting data.

**Comment by ray6080** [comment]
Quick update: the segmentation fault should be fixed now in https://github.com/kuzudb/kuzu/pull/2928.

**Comment by d33bs** [comment]
Fantastic @ray6080 , awesome turnaround time! Thanks again for the updates and information here.

**Comment by d33bs** [comment]
Just wanted to follow up to mention on a single test using `kuzu==0.3.2` I no longer witnessed this issue occurring, so it may be resolved. Generally, and possibly related, I also noticed that memory performance was also significantly better (lower than before). Thanks again @ray6080 for the prompt actions here!

**Comment by ray6080** [comment]
Close as done for now.
