### ISSUE TITLE
Regex error: The complexity of an attempted match against a regular expression exceeded a pre-set level.

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu#2933]
When trying to regex matching files under a long path, the `std::regex` throws error. I encountered this on my MacBook Air locally. didn't try other platforms.

```
kuzu> COPY occurs FROM '/Users/guodong/Downloads/demo-kuzu-rel-table-group-potential-bugs/src/demo/data/kg2c_lite_2.8.4.full.with-metanames.dataset.parquet/edges/occurs_in/Pathway_CellularComponent/*.parquet';
Error: The complexity of an attempted match against a regular expression exceeded a pre-set level.
```

**Comment by mxwli** [comment]
[std::regex is really bad](https://stackoverflow.com/questions/70583395/why-is-stdregex-notoriously-much-slower-than-other-regular-expression-librarie). For our use cases, we should use RE2.
