### ISSUE TITLE
Provide public API to return Kùzu library version

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu#2954]
Kùzu library version is often needed by users to check storage compatibility as we might change our storage layout from one version to another.

Currently, users will have to create a on-disk db folder (or open an existing but potentially incompatible db folder, and handle errors or exceptions around it) to open a Kùzu Database and then perform `CALL db_version() RETURN *;` to get Kùzu system version. 

In Python, it's pretty standard to embed `__version__` into a library (https://stackoverflow.com/questions/458550/standard-way-to-embed-version-into-python-package), so users can easily access it.
In other language APIs, we should be able to find ways to provide such usability, for example, in C/CPP, we can provide a constant value.

**Comment by mewim** [comment]
#2958 added this for C++, C, Python, Node.js and Java APIs. @benjaminwinger could you please also add this for Rust?

**Comment by ray6080** [comment]
Done.
