### ISSUE TITLE
Supporting extending to multiple destination node labels (related to queries with unlabeled node/rels)

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#297]
This feature is related to "Unlabeled Node and Rel Queries". We do not currently support extending through single relation label to nodes with possibly multiple labels. Our storage supports such lists and even our lists.cpp can read such adjacency lists into ValueVectors. But we don't seem to have the correct logic in the query plan and extend operators to handle this case. Specifically here is a test that should pass and currently fails.
The dataset under `dataset/read-list-tests/3-bytes-per-edge' is a dataset where there are both `animal` and `person` nodes and a `knows` relation over {animal,person} x {animal, person}. In this particular dataset there are 6000 person nodes and 1 animal node. person0 connectes to person0 to person5000 (so 5001 edges). animal0 connects to person6000 (all through `knows` edges). 

When I issue the following query: `MATCH (a:person)-[:knows]->(b:person) WHERE a.id = 0 RETURN COUNT(*)`,  the plan that stats scanning from b returns 5002 instead of 5001. Note that id here is an INT64 column (that also happens to be the primary key) and  exists for both animals and person. I did not look very closely but I am guessing that the filter that a should be a person does not seem to be passed along to the filter or extend to filter out the a:0 when the scan b scans p6000.

This is the plan that's failing:
```
LOGICAL_FILTER[a.id = 0]
LOGICAL_SCAN_NODE_PROPERTY[_0_a.id]
LOGICAL_EXTEND[_1_b._id<-_0_a._id]
LOGICAL_FLATTEN[_1_b._id]
LOGICAL_SCAN_NODE_ID[_1_b._id]
```
I believe LOGICAL_SCAN_NODE_PROPERTY scans a0's id column (this is not important but incidentally, I believe this operators is configured with the ID column of p, so in fact it's reading p0's id column, but regardless reads a 0) which passes the filter.

The following end to end test can be written for the 3-bytes-per-edge test. All of these should pass but the first one was failing, which is what triggered this issue.
```
-NAME NodeP0ExtendToPerson
-QUERY MATCH (a:person)-[:knows]->(b:person) WHERE a.id = 0 RETURN COUNT(*)
---- 5001

-NAME NodeP0ExtendToAnimal
-QUERY MATCH (a:person)-[:knows]->(b:animal) WHERE a.id = 0 RETURN COUNT(*)
---- 0

-NAME NodeP1ExtendToPerson
-COMPARE_RESULT 1
-QUERY MATCH (a:person)-[:knows]->(b:person) WHERE a.id = 1 RETURN b.id
---- 1
5000

-NAME NodeP1ExtendToAnimal
-QUERY MATCH (a:person)-[:knows]->(b:person) WHERE a.id = 1 RETURN COUNT(*)
---- 1
0

-NAME NodeP5500ExtendToPerson
-COMPARE_RESULT 1
-QUERY MATCH (a:person)-[:knows]->(b:person) WHERE a.id = 5500 RETURN b.id
---- 0

-NAME NodeP5500ExtendToAnimal
-QUERY MATCH (a:person)-[:knows]->(b:person) WHERE a.id = 5500 RETURN COUNT(*)
---- 0

-NAME NodeA0ExtendToPerson
-QUERY MATCH (a:animal)-[:knows]->(b:personerson) WHERE a.id = 0 RETURN b.id
---- 6000

-NAME NodeA0ExtendToAnimal
-QUERY MATCH (a:animal)-[:knows]->(b:animal) WHERE a.id = 0 RETURN COUNT(*)
---- 0
```

This test can go under read_list_end_to_end_test.cpp.
```
class EndToEndReadLists3BytesPerEdgeTest : public DBLoadedTest {
public:
    string getInputCSVDir() override { return "dataset/read-list-tests/3-bytes-per-edge/"; }
};

TEST_F(EndToEndReadLists3BytesPerEdgeTest, 3BytesPerEdgeTest) {
    vector<TestQueryConfig> queryConfigs;
    queryConfigs =
        TestHelper::parseTestFile("test/runner/queries/adj-list-reading/3-bytes-per-edge.test");
    ASSERT_TRUE(TestHelper::runTest(queryConfigs, *defaultSystem));
}
```

**Comment by andyfengHKU** [comment]
See issue #1116 for the current state of this issue
