### ISSUE TITLE
[Java API] Remove `Kuzu` prefix from class names

### ISSUE THREAD

**Issue by mewim** [kuzudb/kuzu#2973]
Since the Java API is encapsulated in `com.kuzudb` package, there is no need to add the `Kuzu` prefix for class names. We should remove it for simplicity.

**Comment by SterlingT3485** [comment]
Removed the Kuzu prefix in Java API for [kuzu](https://github.com/kuzudb/kuzu)/[ldbc_snb_interactive_v1_impl](https://github.com/kuzudb/ldbc_snb_interactive_v1_impl)/[ldbc_finbench_transaction_impls](https://github.com/kuzudb/ldbc_finbench_transaction_impls) repositories.
