### ISSUE TITLE
Fixed-list layout rework

### ISSUE THREAD

**Issue by andyfengHKU** [kuzudb/kuzu#2975]
We need to rework the in-memory layout for fixed list for the following reasons
- Support non-numerical fixed-list
- Unify in-memory layout between fixed-list and var-list so that we reuse their executor
 

### Var-list layout
Var-list is a nested data type with one vector storing entry information (offset and size), and a data vector storing actual entry in flat form. 

For example, consider a vector of var-list,`[[1,2,3], [11,22], [9,8,7]] `
In the entry information vector we store `[(0,3), (4,2), (6,3)]`
And data vector stores `[1,2,3,11,22,9,8,7]`

To decode each list entry, we first access entry information. E.g. Suppose we want to decode the second list, we first check entry information `(4,2)` which means we need to access data vector offset 4 plus size 2. And it leads to `[11,22]`

### Fixed-list layout
Current layout for fixed-list is a flat layout. Only data vector is stored.

For example, consider a vector of fixed-list, `[[1,2,3], [4,5,6],[7,8,9]]`.
We store it as [1,2,3,4,5,6,7,8,9]. And decoding is based on the fixed size.

One major draw back of such design is that we cannot store nested fixed-list, e.g. INT64[3][] because flat nested fixed-list is not trivial.

To solve this, we should make Fixed-list have a similar layout as Var-list. e.g.
entry information vector `[(0,3), (4,3), (6,3)]`
and data vector `[1,2,3,4,5,6,7,8,9]`.

And we can take one step further to leave entry information vector empty because every entry has the same size.

## On-disk layout
VAR_LIST column are stored in two columns, offset column and data column. Offset column stores end offset of each list value inside the data column.

FIXED_LIST is directly stored as a fixed-sized blob in a non-nested way.
Similar to the rework of in-mem layout, we should unify FIXED_LIST with VAR_LIST by storing data inside the data column, and leaving offset column as empty.

## Changes
- [x] rename FIXED_LIST to ARRAY.
- [x] create `Array` vector. Follow the step of creating `VarList` vector.
- [ ] fix the read from `Array` on disk data into an `Array` vector.
- [x] rewrite fixed-list functions to reuse nested-type executor. (this should mostly be about casting functions)
- [x] discard FIXED_LIST, and move to ARRAY.
- [x] rename VAR_LIST to LIST.

**Comment by ray6080** [comment]
As we discussed, I would suggest adding a new Logical and Physical type `ARRAY` while keeping `FIXED_LIST` as it is for now. Once we finish necessary changes both inside storage, query processor, and front-end for `ARRAY`, we can remove `FIXED_LIST` or rename it.

**Comment by andyfengHKU** [comment]
I'm closing this issue because it is mostly done. Whether we will have an optimized storage for Array is not yet planed.
