### ISSUE TITLE
RuntimeError: Unknown parameter type <class 'NoneType'> (Prepared statement, Python API)

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#2983]
```python
import kuzu

conn = kuzu.Connection(kuzu.Database("/tmp/db"))
conn.execute("CREATE NODE TABLE V(id STRING,PRIMARY KEY(id));")
conn.execute("CREATE (v:V {id: 'foo'}) RETURN v;")
conn.execute("MATCH (v:V {id: $1}) RETURN v;", {"1": "foo"})  # works
conn.execute("MATCH (v:V {id: $1}) RETURN v;", {"1": None})  # below error
```

>Traceback (most recent call last):
  File "/tmp/test1/main.py", line 14, in <module>
    conn.execute("MATCH (v:V {id: $1}) RETURN v;", {"1": None})
  File "/tmp/test1/.venv/lib64/python3.12/site-packages/kuzu/connection.py", line 82, in execute
    _query_result = self._connection.execute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unknown parameter type <class 'NoneType'>

[In addition to UUID](https://github.com/kuzudb/kuzu/issues/2923): please allow `None` in prepared statements of Python API mapping. This is useful for:
- passing dynamic, intermediate (a.k.a. `Maybe`) values to prepared statement
- `None`/`NULL` values are sometimes needed within Cypher statement logic
- `MATCH (v:V {id: NULL}) RETURN v;` works as well

**Comment by andyfengHKU** [comment]
#3098 should fix this.
