### ISSUE TITLE
[Python API] Using trailing `,` results in infinite loop / hanging

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#3002]
If `,` accidentally is used instead of `;` to end cypher statement, it will result in an infinite loop, hanging the program.
```python
import kuzu

dbpath = "/tmp/db1"
conn = kuzu.Connection(kuzu.Database(dbpath))
conn.execute("CREATE NODE TABLE V (id STRING, PRIMARY KEY(id));")
conn.execute("CREATE REL TABLE E (FROM V TO V, ONE_ONE);")
conn.execute(
    """
    CREATE (v1:V {id: "v1"}),
    (v2:V {id: "v2"}),
    (v1)-[:E]->(v2),
    """
)
```
Note `(v1)-[:E]->(v2),` instead of `(v1)-[:E]->(v2);`.

**Comment by ray6080** [comment]
hi @sapalli2989 , this might be a bug inside the parser as we should throw an error/exception here. We will take a look. thanks for reporting!
