### ISSUE TITLE
Allow multi-statement Cypher queries in via `conn.execute()` in Python

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#3007]
It would be great (especially for testing purposes), if `conn.execute()` could receive multiple cypher statements separated by `;`. So that we can write
```python
conn.execute(
  """
  CREATE NODE TABLE V (id UUID, name STRING, PRIMARY KEY(id));
  CREATE REL TABLE AFTER(FROM V TO V, ONE_ONE);
  MATCH (...) RETURN result;
  """
)
```
Is this possible - or would there be issues, e.g. with the returned result?

**Comment by prrao87** [comment]
@sapalli2989 In general, Kùzu is a structured property graph database that clearly divides the work into the DDL and the query stages. The DDL stage is like any relational system where you specify the schema and create the tables. The query stage involves Cypher, in which the various stages of query planning apply. It's arguable that DDL isn't true Cypher, and thus isn't subject to query planning logic and thus it should be treated as a distinct step (just like in RDBMS, you'd only create/alter tables or load data sparingly).

For subsequent queries like multiple matches or node/rel creations, those could potentially be run in a loop if it's tedious to type each one out manually?

```py
queries = [
    "MATCH (p:Person) RETURN p.name, p.age",
    "MATCH (p:Person) WHERE p.age > 30 RETURN p.name, p.age"
]

for query in queries:
    x = conn.execute(query)
    print(x.get_as_df())
```

**Comment by ray6080** [comment]
@sapalli2989 just to clarify a bit more besides @prrao87 's comment.

We do start to support multiple query statements separated by `;` on our latest master, and returned query results will be chained, so you can get the result of each query statement by traversing through a linked list inside the query result. but this is not fully done yet, for example not exposing the interface of fetching query results to python side yet.

**Comment by sapalli2989** [comment]
@prrao87 Good point about the distinction DDL vs. query stage, didn't think about that. Idea was, that you have some "unit of work" (DDL, query or a combination of both), e.g. for ad-hoc or testing purposes and need t to execute these statements possibly multiple times in a simple manner. I was thinking of copying all statements from some template and just pasting them within a Python multi-line string `""" ... """`. Of course, your alternative with iterating list is a good alternative, which requires one additional step to separate statements into a list by comma separator.

**Comment by prrao87** [comment]
I'd also add that when we finally release this in Python, we should document that it be used carefully as the chained results can explode in size if too many queries are run together.

**Comment by sapalli2989** [comment]
@ray6080 That sounds great! Regarding 
> Also note that these query statements are internally parsed into multi ones and each is run as an auto transaction.

Just as an addition: Would you be able to surround statements in one transaction, if needed, like this? 
```
conn.execute(
  """
  BEGIN TRANSACTION;
  // statements here
  // ...
  COMMIT;
  """
)
```

**Comment by prrao87** [comment]
@ray6080 Just wanted to check if the multi-statement query support will be extended to the Python side at some point? We should expose that in Python too if it's on master, so that people can begin experimenting with it.

**Comment by andyfengHKU** [comment]
It's done in cpp. @mewim will extend it into multiple APIs soon.

**Comment by andyfengHKU** [comment]
Hi @sapalli2989, this should now available on master and will be available on nightly build soon.
