### ISSUE TITLE
Confusing error message with reserved argument name in prepared statement

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#3013]
```python
conn.execute(
    "MATCH (vf:V {id: $from})-[e:LINKS_TO]->(vt:V {id: $to}) RETURN vf,e,vt;",
    {"from": "id1", "to": "id2"},
)
```
currently errors with error
> RuntimeError: Parser exception: Invalid input <MATCH (vf:V {id: $from>: expected rule oC_SingleQuery (line: 1, offset: 18)
"MATCH (vf:V {id: $from})-[e:LINKS_TO]->(vt:V {id: $to}) RETURN vf,e,vt;"
                   ^^^^

This is confusing from user perspective - statement is syntactically correct, but  `from` and `to` both seem to be reserved keywords.
Renaming `from` -> `from_id` , `to` -> `to_id` will work, but I would suggest to either provide better error description or preferrably have no restrictions on argument names.

Related: https://github.com/kuzudb/kuzu/issues/2676

**Comment by andyfengHKU** [comment]
Hi @sapalli2989,

It took a while but we finally get to this. We have updated our reversed keyword list in #3626 according to the PG standard. The list will be update to the documentation as well. You can find a temporary version [here](https://github.com/kuzudb/kuzu-docs/issues/155). 

For this specific case, FROM and TO are still reserved. 

In terms of better error message, we will continue investigate how to do it with antlr4.

**Comment by sapalli2989** [comment]
Hey @andyfengHKU No problem, thanks for having kept an eye on this !
