### ISSUE TITLE
Inconsistent Behavior between Kuzu and Neo4j in Handling Self-Loops

### ISSUE THREAD

**Issue by joyemang33** [kuzudb/kuzu#3021]
Hello there,

I've encountered some peculiar behavior while testing Kuzu on a graph with self-loops. Specifically, certain queries seem to yield unexpected results.

Additionally, I ran the same queries in Neo4j and noticed a discrepancy. It appears that Kuzu is attempting to return duplicated results exponentially.

Here's a simplified version for Command Line:

```cypher
CREATE NODE TABLE User(name STRING, age INT64, PRIMARY KEY (name));
CREATE REL TABLE Follows(FROM User TO User, since INT64);
MATCH (n1:User), (n2:User) WHERE (n1.name = "Alice") AND (n2.name = "Alice") CREATE (n1)-[:Follows]->(n2);
MATCH (n1)-[]-(n1) RETURN *;
-----------------------------------------
| n1                                    |
-----------------------------------------
| {_ID: 0:0, _LABEL: User, name: Alice} |
-----------------------------------------
| {_ID: 0:0, _LABEL: User, name: Alice} |
-----------------------------------------
MATCH (n1)-[]-(n1)-[]-(n1) RETURN *;
-----------------------------------------
| n1                                    |
-----------------------------------------
| {_ID: 0:0, _LABEL: User, name: Alice} |
-----------------------------------------
| {_ID: 0:0, _LABEL: User, name: Alice} |
-----------------------------------------
| {_ID: 0:0, _LABEL: User, name: Alice} |
-----------------------------------------
| {_ID: 0:0, _LABEL: User, name: Alice} |
-----------------------------------------
```
For Neo4j, the first query will return only one line and the second query will return an empty set cause Neo4j does not allow matching duplicated relationships in ```MATCH```.

For Kuzu, I think the first query should return one line but two lines are found. For the second query, I think both 1 line and 0 line is OK, but 4 lines looks unexpected to me.

I suspect there is a bug when handling the self-loop in Kuzu, and I have tried to execute an additional query for verification:

```cypher
MATCH (n1)-[]-(n1)-[]-(n1)-[]-(n1)-[]-(n1)-[]-(n1)-[]-(n1)-[]-(n1)-[]-(n1)-[]-(n1)-[]-(n1)-[]-(n1) RETURN COUNT(*);
----------------
| COUNT_STAR() |
----------------
| 2048         |
----------------
```
As you can see, the query yields a searching space with exponential size for numerous ```| {_ID: 0:0, _LABEL: User, name: Alice} |```, but only the graph contains one node ```Alice``` and only one line is needed.

It would be highly appreciated if you could further verify and investigate this report.

Best regards,
Qiuyang

**Comment by andyfengHKU** [comment]
Hi @joyemang33,

Thanks for pointing this out. I have checked with Neo4j and it seems they have a special handling for self-looped undirected query edge.

Normally undirected query edge meaning system should match both fwd and bwd adjacency list. For example,
```
MATCH (a)-[e]->(b) RETURN COUNT(*) AS c1;
MATCH (a)<-[e]-(b) RETURN COUNT(*) AS c2;
MATCH (a)-[e]-(b) RETURN COUNT(*) AS c3;
```
We would expect `c1 + c2 = c3`.

However, with self loop edge, Neo4j result is `c1 == c2 == c3 == 1`.  For Kuzu, we have `c1 == c2 == 1 and c3 == 2`.

Though Neo semantic might make more sense in practical usage. So I'll run this case with the team and let you know if we will do the same special handling as Neo.

**Comment by andyfengHKU** [comment]
After discussing with the team. We don't think it's critical to comply with Neo4j in this case.
