### ISSUE TITLE
Unsupported type `UINT8` in Node.js client

### ISSUE THREAD

**Issue by prrao87** [kuzudb/kuzu#3035]
I'm trying to run the following query via the [api-server](https://hub.docker.com/r/kuzudb/api-server), which utilizes the Node.js client under the hood.

Although Kùzu supports the `UINT8` data type for fields like age that have a hard limit on the maximum value, the Node.js client doesn't seem to translate it from Cypher correctly. In the example database I'm using, I store the person's age as `UINT8`, and send the request via the api-server that's running in a Docker container.

Here's my query:

```json
{
  "query": "MATCH (p:Person) WHERE p.age > $a RETURN p.name AS name, p.age AS age LIMIT 10",
  "params": {
    "a": 20
  }
}
```

### Error

Running this via a curl request (that calls the underlying Node.js client) results in this error:

```json
{
  "error": "Unsupported type UINT8 for parameter: a"
}
```

Running the same query via the Python client produces no error.

### Correct result

When I instead store the age field as `INT64`, the query runs fine, in both Python and Node.js.

### Example database

The database is attached.
[persons.zip](https://github.com/kuzudb/kuzu/files/14578479/persons.zip)

Hope this helps reproduce the error.

**Comment by mewim** [comment]
Fixed in #3037
