### ISSUE TITLE
[DRAFT PROPOSAL] DDL Transaction

### ISSUE THREAD

**Issue by andyfengHKU** [kuzudb/kuzu#3062]
Currently we have a weird constraint that DDL statements and COPY statements cannot be wrapped in a manual transaction. Without a doubt we should remove this constraint. Plus, the import database feature also requires us to support multiple DDL within one transaction.

As the first step, we should remove `DUMMY_READ_TRANSACTION & DUMMY_WRITE_TRANSACTION` in the codebase and instead pass a property transaction pointer. This can be achieved by propagating client context into each database components (mostly planner, mapper & statistics).

- [x] Remove dummy transactions and propagate client context.
- [x] Since database is stored in client context, for classes that depend on multiple database components, e.g. BM, MM, FS, ..., simply replace these components with client context.

The second step would be make catalog information available in WALReplayer after prepareCommit. @ray6080 should complete the second part of this proposal.

**Comment by ray6080** [comment]
Also, move tests in `e2e_ddl_test.cpp` to end-to-end tests.

**Comment by andyfengHKU** [comment]
Closing because the compilation part has been done. There is still more work on the `WAL` part but is no longer relevant to this PR.
