### ISSUE TITLE
Adding uint64 to client config causes load extension to segfault

### ISSUE THREAD

**Issue by MSebanc** [kuzudb/kuzu#3096]
When I add another uint64 to this struct it causes Load Extension to seg fault. 
The segfault seems to be happening on this line. https://github.com/kuzudb/kuzu/blob/6860af06114ea6875ad99a98de2dab71477cb0bd/src/processor/operator/load_extension.cpp#L75

To reproduce, add an uint64 field here and install and load the httpfs extension. 
https://github.com/kuzudb/kuzu/blob/6860af06114ea6875ad99a98de2dab71477cb0bd/src/include/main/client_config.h#L9-L24

**Comment by acquamarin** [comment]
Can you be more specific about which extension test fails?
can you try make extension-test?

**Comment by MSebanc** [comment]
Calling `LOAD EXTENSION httpfs` causes it to segfault so any test using that statement would fail. So the `ExtensionTest` in `extention.test` is fails when a uint64 gets added to client config.

**Comment by acquamarin** [comment]
i think you have to trigger the ci to recompile the extension, since you changed the clientconfig.

**Comment by MSebanc** [comment]
If I add a bool everything works correctly and there's no segfault
