### ISSUE TITLE
Website Python API docs not current

### ISSUE THREAD

**Issue by alexander-beedie** [kuzudb/kuzu#3101]
Was just about to point someone at the `QueryResult` docs, showing the new `get_as_pl` method, but it doesn't seem to be there yet. Is there some process that needs to be run to update them? 

(I see that `0.3.2` was released but the online docs don't reflect the additional method):
https://kuzudb.com/api-docs/python/kuzu/query_result.html

**Comment by mewim** [comment]
@alexander-beedie sorry I forgot to rerun docs generation for 0.3.2 release. I’ve just redeployed the docs and the docs for get_as_pl can now be found at https://kuzudb.com/api-docs/python/kuzu.html#QueryResult.get_as_pl

**Comment by alexander-beedie** [comment]
> I’ve just redeployed the docs

Thanks! Can see it now :)
