### ISSUE TITLE
Merge with duplicate primary key is not working as expected

### ISSUE THREAD

**Issue by prrao87** [kuzudb/kuzu#3103]
### Discussed in https://github.com/kuzudb/kuzu/discussions/3102

<div type='discussions-op-text'>

<sup>Originally posted by **serkancoban** March 21, 2024</sup>
Hi, we expect below query to complete successfully, but it gives error:
LOAD FROM "kuzu.parquet" WITH col1 as c1,col2 as c2, col3 as c3  limit 10 merge (n:User {id:string(id)});
Runtime exception: Found duplicated primary key value 1234, which violates the uniqueness constraint of the primary key column

Merge normally should handle this right?</div>

**Comment by andyfengHKU** [comment]
This should be solved in #3207 already.

**Comment by serkancoban** [comment]
Tried with 0.4 version, I start with empty DB. here is the table metadata:

`CREATE NODE TABLE Number(str1 STRING, PRIMARY KEY (str1));`
`CREATE REL TABLE Linked(FROM Number TO Number, dates INT64[]);`

Our parquet table is 2.1GB 3 columns f1,f2,begin_time
This works:
`LOAD FROM "kuzu.parquet" WITH f1 as f,f2 as t, begin_time as bt limit 10000 merge (n:Number {str1:string(t)});`

This OOM killed after using 92GB memory:
`LOAD FROM "kuzu.parquet" WITH f1 as f,f2 as t, begin_time as bt limit 100000 merge (n:Number {str1:string(t)});`

This gives error: "Error: Binder exception: Variable __existence already exists."
`LOAD FROM "kuzu.parquet" WITH f1 as f,f2 as t, begin_time as bt merge (n:Number {str1:string(t)}) merge (n2:Number {str1:string(f)}) merge (n)-[e:Linked]-(n2);`

**Comment by andyfengHKU** [comment]
The memory issue should be resolved in v0.5.0
