### ISSUE TITLE
Elements above the 256th position in a list cannot be null

### ISSUE THREAD

**Issue by mxwli** [kuzudb/kuzu#3138]
Steps to reproduce
```py
import kuzu
import pandas as pd
import random

db = kuzu.Database("tmpdatabase")
conn = kuzu.Connection(db)

df = pd.DataFrame({'col1': [[random.randint(-(1<<60), (1<<60)) if random.randint(0, 5) == 0 else None for i in range(2048)] for x in range(2)]})

print(df['col1'][0])
print(conn.execute("CALL READ_PANDAS(df) RETURN col1").get_next())
```

By examining the output, you can see that after the 256th position, `None` is replaced by `0`, meaning we don't register values as being null after the 256th position in a list.

This is likely not a bug with the pandas scanner; the pyarrow scanner exhibits the same behaviour, and I can confirm that the null values after position 256 were correct set by the scanner. At some point afterwards, the null was lost. Strangely, the row afterwards maintains its null values.

**Comment by acquamarin** [comment]
```
import kuzu
import pandas as pd
import random

db = kuzu.Database("tmpdatabase")
conn = kuzu.Connection(db)

df = pd.DataFrame({'col1': [[random.randint(-(1<<60), (1<<60)) if random.randint(0, 5) == 0 else None for i in range(2048)] for x in range(2)]})

tp = conn.execute("LOAD FROM df RETURN col1").get_next()[0]
assert(tp == df['col1'][0])
```
The bug should has been solved
