### ISSUE TITLE
Clang Format Upgrade

### ISSUE THREAD

**Issue by benjaminwinger** [kuzudb/kuzu#3147]
We've been using clang format 11 specifically, which is a little old, and missing some features.
While not high priority to upgrade, I thought it would be helpful to create an issue listing settings not available to clang format 11 that we might like to make use of.

- SeparateDefinitionBlocks: https://clang.llvm.org/docs/ClangFormatStyleOptions.html#separatedefinitionblocks (v14)
- EmptyLineBeforeAccessModifier: https://clang.llvm.org/docs/ClangFormatStyleOptions.html#separatedefinitionblocks (v12)

**Comment by andyfengHKU** [comment]
We have upgraded to clang format 18.
