### ISSUE TITLE
Easier Graph Construction Tools

### ISSUE THREAD

**Issue by Dalouvid** [kuzudb/kuzu#3180]
Hey guys,
please add a function that simplifies the construction of graphs from pure text. 

A possible solution would be to use the [LangChain GraphDocuments](https://api.python.langchain.com/en/latest/graphs/langchain_community.graphs.kuzu_graph.KuzuGraph.html#langchain_community.graphs.kuzu_graph.KuzuGraph) Object and provide a way to translate that to a Kùzu Graph, like it is done [here](https://api.python.langchain.com/en/latest/graphs/langchain_community.graphs.neo4j_graph.Neo4jGraph.html#langchain_community.graphs.neo4j_graph.Neo4jGraph.add_graph_documents).
Adding a LangChain GraphDocument would then simply be "KuzuGraph.add_graph_documents(graph_documents)" 

I think that offering a better way to build Kùzu graphs using LangChain could attract many new users. 

Thank you guys for your awesome work! 
Cheers, 
David

**Comment by prrao87** [comment]
Hi @Dalouvid, this is a good feature to add and we will get on it and keep the community posted 👍🏽.

**Comment by prrao87** [comment]
Completed in https://github.com/langchain-ai/langchain/pull/27949.
