### ISSUE TITLE
Support aliases for FLOAT and DOUBLE

### ISSUE THREAD

**Issue by prrao87** [kuzudb/kuzu#3185]
The current naming for float type declaration expects the user to know beforehand (or carefully go through the docs) to know the distinction in Kùzu between `FLOAT` and `DOUBLE`.

It would be nice to have the same aliases as [DuckDB does](https://duckdb.org/docs/sql/data_types/numeric.html#floating-point-types), to help users from these systems move between DBs more easily.

Name | Aliases | Description
--- | --- | ---
`FLOAT` | `FLOAT4`, `REAL`	| single precision floating-point number (4 bytes)
`DOUBLE` | `FLOAT8` | double precision floating-point number (8 bytes)

**Comment by andyfengHKU** [comment]
Should be fixed in #3284
