### ISSUE TITLE
Linking error when building rust crate in debug mode on Windows

### ISSUE THREAD

**Issue by zaddach** [kuzudb/kuzu#3225]
The rust crate fails to build on Windows because the C++ libraries are trying to link to the debug vc runtime (`/MDd`), whereas Rust always links against the release runtime (`/MD`), even when building debug configuration.

Release builds fine.

**Comment by benjaminwinger** [comment]
This should probably be documented, but we've been setting `/MDd` via environment variables in the Makefile [here](https://github.com/kuzudb/kuzu/blob/c6e62e9e08818b6ba178ebb341c8c35edfefcdf3/Makefile#L119-L120), which has been working, so it is possible (Also see https://github.com/rust-lang/rust/issues/39016#issuecomment-853964918). However I can also understand if that's not a reliable solution for your workflow.
