### ISSUE TITLE
Changes that should be removed after implementing ```ARRAY``` layout

### ISSUE THREAD

**Issue by manh9203** [kuzudb/kuzu#3240]
I made some temporary changes so that ```LIST``` and ```ARRAY``` can use the same layout. We should remove them after implementing a separate layout for ```ARRAY```.
- [ListType](https://github.com/kuzudb/kuzu/pull/3175/files#diff-d80484b6229604f5ff197c3810c4a623ac34bb4f4dc01c86045d57c0d89330a9L448)
- [ListVector](https://github.com/kuzudb/kuzu/pull/3175/files#diff-1695809415bf49667a5bfb4b563a2f8bc5f1e35c87cb7b9dc3d6bd6e2b8e796aL152)
- [ListColumnChunk](https://github.com/kuzudb/kuzu/pull/3175/files#diff-67a98634e185b67d8a385fc228fcdec8b7b40b972619633f6d56d7475bbc4d42L37)
- [StorageDriver](https://github.com/kuzudb/kuzu/pull/3175/files#diff-1c623748c81614c8d6bb94c83807e9ef3fa701685b4cf3bd4b61d63ac29fbc9aL67)

**Comment by mxwli** [comment]
Note: get_as_arrow currently assumes that LIST and ARRAY share the same layout. This will have to be changed if the ARRAY layout changes.

**Comment by prrao87** [comment]
@manh9203 could you also please track the documentation pages for the data types that will be affected by these changes? I recommend double-checking the docs page for anything that mentions `FIXED-LIST` or `VAR-LIST` or similar and tagging me on those. Thanks!

**Comment by hououou** [comment]
@manh9203 Could you please help me check the persistent storage layout of the `List`?  I've made changes to the underlying storage layout of `VAR_LIST`. If you come across anything relevant, please send it to me.

**Comment by manh9203** [comment]
@prrao87 I checked and nothing has to be changed about the docs. These changes are not exposed to users, they should only be the developer's concern.

**Comment by andyfengHKU** [comment]
I don't foresee us implementing specialized storage for ARRAY any time soon. So closing this.
