### ISSUE TITLE
compilation error 'cannot convert ‘kuzu::storage::HashIndexLocalStorage<std::__cxx11::basic_string<char> >::Key’'

### ISSUE THREAD

**Issue by excaliburwyj** [kuzudb/kuzu#3245]
environment: cmake (3.16), g++(10.5), Python (3.9) in Ubuntu 20.04
I operate like 'Building Instructions' in this page: https://docs.kuzudb.com/developer-guide/
![2024-04-10_17-47](https://github.com/kuzudb/kuzu/assets/29565053/df8a0801-a047-4c60-80d3-328adc2ab3b3)

**Comment by mewim** [comment]
Hi @excaliburwyj,

I am sorry for the confusion. We no longer support gcc 10. Now at least gcc 11 is required to build kuzu. I'll update the docs accordingly. Regarding the requirements for building kuzu on Ubuntu 20.04, I suggest you to refer to:

https://github.com/kuzudb/kuzu/blob/master/.github/workflows/multiplatform-build-test.yml#L22-L46

which has been verified on GitHub runner with Ubuntu 20.04.

**Comment by excaliburwyj** [comment]
Thank you for your reply. I will try again using GCC 11

**Comment by mewim** [comment]
Closing this for now. If you encounter issue with GCC 11, feel free to reopen it. Thanks.
