### ISSUE TITLE
Avoid lock challenges through context management for Kuzu database connections

### ISSUE THREAD

**Issue by d33bs** [kuzudb/kuzu#3260]
Thanks again for the awesome work in this project! This issue expands upon topics brought up in #3145 to suggest a `kuzu.Connection().close()` be somehow implemented to ensure locks don't interrupt possibly concurrent use of single Kuzu databases. It's possible the behavior is better suited for `kuzu.Database().close()`, please feel free to correct!

Generally I've experienced that open Python processes through Jupyter notebooks which have connected to Kuzu databases will continue to lock the database. This becomes problematic when modularizing work through multiple notebooks that possibly make use of the same database (resulting in errors: `RuntimeError: Could not set lock on file : ..`). As a workaround, one can interrupt or restart Jupyter kernels associated with a notebook to unlock the database, but this takes time and manual action.

It is common for databases in Python to use context management for connections to help ensure they close properly without impacting other work. This also applies to DuckDB through Python, which enables this type of functionality (e.g. `with duckdb.connect() as ddb: ...`). It may be that `contextlib.closing()` is a more appropriate match ([similar to `sqlite3` connection management in Python](https://docs.python.org/3/library/sqlite3.html#sqlite3-connection-context-manager)), and if that's the case, I suggest updating the documentation to reflect this.

Suggested demo of how this could work:
```python
import kuzu

# init a Kuzu database and connection
db = kuzu.Database(target_database_path)
kz_conn = kuzu.Connection(db)

# run a query
kz_conn.execute("RETURN 1;")

# close the connection manually
kz_conn.close()
```

Similarly, with a context manager:
```python
import kuzu

# init a Kuzu database and connection
db = kuzu.Database(target_database_path)

# form a context manager for the kuzu connection
with kuzu.Connection(db) as kz_conn:
    # run a query
    kz_conn.execute("RETURN 1;")

# the connection closes to anything outside the context
```

In both of the above cases, my hope would be that the lock is also removed on the database, meaning other processes may do work on the database without running into a `RuntimeError`.

**Comment by ray6080** [comment]
Hi @d33bs , thanks for the issue! this makes good to me. we will look into this 😄

**Comment by prrao87** [comment]
Hi @d33bs, yes, other users have also noted that working with a Kùzu database from a Jupyter notebook exhibits this behaviour. From an analysis perspective, it would make sense that more than one user might want to connect to a database at the same time from a Jupyter notebook. It's worth looking into for sure, as @ray6080 mentioned.

In the meantime, as a workaround, there shouldn't be any issues with multiple users connecting to a single database via Python scripts (though it's not ideal from an exploratory standpoint). Hope this helps!

**Comment by d33bs** [comment]
Thanks @ray6080 and @prrao87 for the replies here!

> In the meantime, as a workaround, there shouldn't be any issues with multiple users connecting to a single database via Python scripts (though it's not ideal from an exploratory standpoint). Hope this helps!

Thank you for the additional context here. Just to make sure I understand: would one be able to use multiple Python scripts in parallel to connect with a single Kuzu database? Or would this encounter the same locking challenges mentioned?

**Comment by prrao87** [comment]
I think my earlier statement was incorrect, see the best practices in the docs: https://docs.kuzudb.com/client-apis/#best-practices

If you run multiple Python scripts in parallel, you'd have multiple `Database` instances that would conflict with each other for the afore mentioned reasons, leading to the same issue that you face with Jupyter notebooks. However, within a single `Database` instances, you're free to open multiple `Connection` objects that can read from the DB concurrently. I believe this is the approach we use when wrapping Kùzu as an [API server.](https://github.com/kuzudb/api-server).

How to use concurrency is something we've been meaning to clarify better in our docs, and hopefully the user experieonce should also improve with time 😅. Let us know if you have any more questions!

**Comment by prrao87** [comment]
Now that I think about it a bit more, as long as the state of the DB doesn't change (i.e., another process isn't writing to the DB), you should be able to run multiple *read* query scripts in Python concurrently, even if they have different `Database` instances. @ray6080 should be able to clarify this once he has a moment, but feel free to give it a try via scripts for now!

**Comment by mewim** [comment]
I have implemented a `Database.close()` method which should release the lock. A test case is added here: https://github.com/kuzudb/kuzu/blob/master/tools/python_api/test/test_database.py

I am closing this for now. If you still encounter issue releasing the lock, feel free to reopen this. Thanks.
