### ISSUE TITLE
`Connection.close()` is missing.

### ISSUE THREAD

**Issue by phf-1** [kuzudb/kuzu#3268]
Hello,

While testing Kuzu, I have noticed the absence of a `Connection.close()` method, as [one exists](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.close) for sqlite3. 
Is it supposed to be the case? If yes, how to release a lock on `.lock` ?

Cheers,
PHF

----

Here are a few lines of code that lead the previously mentioned observation.

This code:
```Python
writer = KuzuWriter(tmpdir)
writer.start()

viz = KuzuViz(tmpdir, debug=True)
viz.start()
```
where `writer` opens a connection using the Python API and `viz` starts the docker container visualization tool leads to the following error:

```
[15:13:22.343] INFO (1): Access mode: READ_WRITE
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: Could not set lock on file : /database/.lock]
```

As a workaround, this code:
```Python
writer = KuzuWriter(tmpdir)
writer.start()

del writer
gc.collect()

viz = KuzuViz(tmpdir, debug=True)
viz.start()
```
does not yield any error.

**Comment by andyfengHKU** [comment]
Hi @phf-1, this seems to be the same problem as mentioned in #3260. We will fix this problem in the coming week. Feel free to join the discussion if you have a different idea.

Thanks for bringing this up!

Best,
Xiyang

**Comment by mewim** [comment]
I have implemented a `Database.close()` method which should release the lock. A test case is added here: https://github.com/kuzudb/kuzu/blob/master/tools/python_api/test/test_database.py

I am closing this for now. If you still encounter issue releasing the lock, feel free to reopen this. Thanks.

**Comment by phf-1** [comment]
Great ! Thank you @mewim.
