### ISSUE TITLE
`hasNextQueryResult()` can return `true` for single query statement

### ISSUE THREAD

**Issue by mewim** [kuzudb/kuzu#3312]
Consider the following test case:
```cpp
TEST_F(ApiTest, SingleQueryHasNextQueryResult) {
    auto result = conn->query("MATCH (a:person) RETURN a.fName;");
    ASSERT_TRUE(result->isSuccess());
    ASSERT_FALSE(result->hasNextQueryResult());
}
```

This is supposed to return `false` as there is only one query statement. However, this returns `true`, but calling `getNextQueryResult` subsequently causes `SEGFAULT`:
```cpp
auto nextResult = result->getNextQueryResult();
ASSERT_TRUE(nextResult->isSuccess());
```

I have pushed the branch as https://github.com/kuzudb/kuzu/tree/single-query-has-next. And logs for failed tests is available at https://github.com/kuzudb/kuzu/actions/runs/8735678979

**Comment by hououou** [comment]
close as completed via #3311
