### ISSUE TITLE
Query like match (a:Person) return count(distinct a) has an infinite loop problem 

### ISSUE THREAD

**Issue by ted-wq-x** [kuzudb/kuzu#3339]
# DataSet
ldbc sf100

# Problem

While the  numbers of a exceeded `BaseHashTable#maxNumHashSlots`, the dead loop appears in the loop outside the method `AggregateHashTable::increaseSlotIdx`

**Comment by acquamarin** [comment]
Hello!
May i know the query that causes the infinte loop?

Thank you!
