### ISSUE TITLE
Add a system-level mechanism (possibly lock) to coordinate changes that might affect multiple components

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#336]
We are implementing several functionalities that change some components of the system, e.g., the buffer manager's buffer pool size, or updates, which affect the storage files. These need to be: (1) coordinated and; (2) happen when the system is idle, i.e., no queries, updates, or some system configuration changes are happening. We need a mechanism to coordinate these.

One idea is to have functions waitUntilSystemIsIdleAndAcquireSystemLock() and releaseSystemLock() somewhere, possibly in System. The first function could do two things: (i) acquire a system-level lock that the query compiler, BufferManager::resize(), and future components related to updates (e.g., transaction manager) can acquire before doing such changes; and (ii) monitor the query processor to ensure all query processing tasks have been completed.

**Comment by ray6080** [comment]
This is no longer relevant.
