### ISSUE TITLE
Extension Documentation TODOs

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#3367]
I'm putting these issues that I found here, so we can better keep track of them.:

- [ ] Code snippets have confusing color fonts. Some keywords are black and others are red.
- [ ] The larger purpose of the DuckDB -> One important use case of the DuckDB Scanner extension is ...
- [ ] MATCH (p:person) RETURN p.*; -> p:Person. (In addition the result table's schema is wrong: "s.name | s.age").
- [ ] PostgreSQL databases that are persisted to disk -> remove the part about "persisted to disk".
- [ ] Clarify that the extension is only to scan data and not to write any data.
- [ ] Official extensions can be simply installed by running the install command:-> Say that this can be executed from the CLI or any programming language.
- [ ] In the documentation, should we link to: https://github.com/kuzudb/extension, or https://extension.kuzudb.com/?
- [ ] Prerequisites before using DuckDB extension? Are there any (e.g., brew install DuckDB) or no. For DuckDB, it has to be 0.10.x. 
- [ ] Document about DuckDB and Postgres schema cache
- [ ] Document that each time you create a new Database cpp object, which happens when you start your CLI again, or start your python script or cpp code again, you need to LOAD each EXTENSION. => Main extensions page.
- [ ] Document that Postgres extension should work with any relatively recent Postgres version (e.g., 14 and above and possibly earlier versions).
- [ ] Test that if you don't have DuckDB, you can still use the Postgres extension. Test this after Chang handles the static linking to DuckDB.
- [ ] PostgreSQL documentation of DuckDB has more extensive description about the "PG_CONNECTION_STRING": https://duckdb.org/docs/extensions/postgres#configuration. We don't want to copy-paste all they did, but we can give several examples of connection strings, also discuss "Configuring via Environment Variables" and point to the Postgres documentation on connection strings: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS. We need similar information.

**Comment by prrao87** [comment]
I've been addressing them on the docs repo here: https://github.com/kuzudb/kuzu-docs/issues/129
