### ISSUE TITLE
WASM Support

### ISSUE THREAD

**Issue by justin0mcateer** [kuzudb/kuzu#3400]
Kuzu seems to be supported in a number of environments, including NodeJS. Is there any intention or desire to support running in the browser via WASM? Is there any reason this can't be compiled using Emscripten?

**Comment by prrao87** [comment]
Hi @justin0mcateer, the information in #3327 might be useful - we do intend to support running in the browser via WASM, but it's not on the immediate roadmap. As mentioned in @mewim's comment, there was some preliminary work done to enable WASM support for Kùzu, with the following roadblock:

> but it does not quite work right now as Kùzu’s current buffer manager uses memory mapping and requires support of MADV_DONTNEED

As for compiling with Emscripten, @mewim will get back to you on this. Feel free to drop any more comments in the linked discussion and upvote it over there too.

**Comment by justin0mcateer** [comment]
Sorry for the dupe. I searched a few terms, but I was searching issues, not discussions.
