### ISSUE TITLE
Several minor issues for v0.4.0  

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#3422]
I want to open a single issue for the issues I'm spotting for v0.4.0. It will help in case the list grows:
- [x] replace postgres_clear_cache() and duckdb_clear_cache() with a single function clear_attached_db_cache();
- [x] Documentation updates for clearing the cache.
- [x] USE keyword is not highlighted in the shell. I did not test KuzuExplorer but it is possible that it is not highlighted there either.

**Comment by prrao87** [comment]
I think this can be closed? @acquamarin

**Comment by andyfengHKU** [comment]
I'm closing this due to completion.
