### ISSUE TITLE
Creating multiple relationships and nodes from 1 file

### ISSUE THREAD

**Issue by Kamalika17** [kuzudb/kuzu#3470]
Hi,

Is it possible to create multiple relationships and nodes from 1 file or is it necessary to have separate files for each node type and edge type for a knowledge graph. eg:  I have 1 data frame where all information is given:
Person, City, Country, Hobby
A, Bern, Switzerland, Painting

Each column is a node type and relationships - A "lives-in" Bern, Bern "capital-of" Switzerland, A "likes" Painting

Thanks for your help!

**Comment by andyfengHKU** [comment]
Hi @Kamalika17,

Yes if you want to load them into different relationship tables then they should be in different files.

However, if your dataset is not too large. It should also work fine if you make `lives-in, capital-of, likes` as a relationship property (of type string). So effectively you only have one node table and one relationship table. Everything else is modelled as a property on these two tables.
