### ISSUE TITLE
Support JSON property type

### ISSUE THREAD

**Issue by bgoosmanviz** [kuzudb/kuzu#3508]
I want to store variable sized JSON in a node property.

```
CREATE NODE TABLE Entity(data JSON)
CREATE (n:Entity {data: {"a": 1, "b": {"c": 2}}})
```

Today, I have to stringify the JSON.

**Comment by bgoosmanviz** [comment]
I got part of the way there. KuzuDB supports MAP(STRING, STRING), which is close but I would also like values to allow for integers, lists, and booleans.

**Comment by andyfengHKU** [comment]
We have opened a proposal for JSON type #3609. Please follow the new issue instead.
