### ISSUE TITLE
Feature: Implement `contains`/`includes` text function

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#3525]
### API

Python

### Description

There are already `starts_with` and `ends_with` text functions (https://docs.kuzudb.com/cypher/expressions/text-functions/). 

What about a function `contains`/`includes` to also search for terms in-between? I think this is easier than doing full-regex searching for simple words. For case-insensitive search it might be used together with `lower()` and `upper()`. 

Related:
- https://duckdb.org/docs/sql/functions/char#containsstring-search_string
- https://github.com/kuzudb/kuzu/issues/1506

**Comment by andyfengHKU** [comment]
This should be done in #3531
