### ISSUE TITLE
Bug: Error encountered when calling show_connection() function

### ISSUE THREAD

**Issue by paopaooux** [kuzudb/kuzu#3527]
### What happened?

The bug like this:

![issue](https://github.com/kuzudb/kuzu/assets/146108555/1175941d-fe04-4349-8a27-8e0444f8452a)
when we call this function, the code throws the exception: basic_string::_M_create

**Comment by andyfengHKU** [comment]
Hi @paopaooux,

I tried a few cases but cannot reproduce this bug locally. Can u share the set of queries u run before `show_connection`?

**Comment by paopaooux** [comment]
> queries

My OS is Ubuntu 22.04.4 LTS, I clone kuzu and make release, use tinysnb and ldbc-sf01 datasets, other settings are initialized, and only execute this statement, both of which give me this error

**Comment by acquamarin** [comment]
> > queries
> 
> My OS is Ubuntu 22.04.4 LTS, I clone kuzu and make release, use tinysnb and ldbc-sf01 datasets, other settings are initialized, and only execute this statement, both of which give me this error

I tried on Ubuntu 22.04.4 LTS and build from source, could not reproduce the bug either:
```
kuzu> call show_connection("studyAt") return *;
---------------------------------------------------------------------------------------------------------
| source table name | destination table name | source table primary key | destination table primary key |
---------------------------------------------------------------------------------------------------------
| person            | organisation           | ID                       | ID                            |
---------------------------------------------------------------------------------------------------------
(1 tuple)
(4 columns)
Time: 0.21ms (compiling), 1.53ms (executing)
```

**Comment by paopaooux** [comment]
> > > queries
> > 
> > 
> > My OS is Ubuntu 22.04.4 LTS, I clone kuzu and make release, use tinysnb and ldbc-sf01 datasets, other settings are initialized, and only execute this statement, both of which give me this error
> 
> I tried on Ubuntu 22.04.4 LTS and build from source, could not reproduce the bug either:
> 
> ```
> kuzu> call show_connection("studyAt") return *;
> ---------------------------------------------------------------------------------------------------------
> | source table name | destination table name | source table primary key | destination table primary key |
> ---------------------------------------------------------------------------------------------------------
> | person            | organisation           | ID                       | ID                            |
> ---------------------------------------------------------------------------------------------------------
> (1 tuple)
> (4 columns)
> Time: 0.21ms (compiling), 1.53ms (executing)
> ```

okey, thanks very much.Maybe it's my hardware.

**Comment by acquamarin** [comment]
May i know your hardware configuration? Are you using 32bit ubuntu?

**Comment by mewim** [comment]
Hi @paopaooux,

Could you please test our pre-compiled CLI:

[x86-64](https://github.com/kuzudb/kuzu/releases/download/v0.4.2/kuzu_cli-linux-x86_64.tar.gz)
[arm64](https://github.com/kuzudb/kuzu/releases/download/v0.4.2/kuzu_cli-linux-aarch64.tar.gz)

to see if it works for you?

**Comment by paopaooux** [comment]
> Hi @paopaooux,
> 
> Could you please test our pre-compiled CLI:
> 
> [x86-64](https://github.com/kuzudb/kuzu/releases/download/v0.4.2/kuzu_cli-linux-x86_64.tar.gz) [arm64](https://github.com/kuzudb/kuzu/releases/download/v0.4.2/kuzu_cli-linux-aarch64.tar.gz)
> 
> to see if it works for you?

It's 64-bit ubuntu, it's x64 architecture, I can use the x86-64 CLI but not the arm64 CLI. i'm running it on another 64-bit ubuntu with the same problem!

**Comment by paopaooux** [comment]
Here's my hardware info that may help solve the problem
CPU :Intel® Core™ i5-6300U CPU @ 2.40GHz × 4
GPU: Mesa Intel® HD Graphics 520 (SKL GT2)
Memory: 16.0 GiB

**Comment by mewim** [comment]
> > Hi @paopaooux,
> > Could you please test our pre-compiled CLI:
> > [x86-64](https://github.com/kuzudb/kuzu/releases/download/v0.4.2/kuzu_cli-linux-x86_64.tar.gz) [arm64](https://github.com/kuzudb/kuzu/releases/download/v0.4.2/kuzu_cli-linux-aarch64.tar.gz)
> > to see if it works for you?
> 
> It's 64-bit ubuntu, it's x64 architecture, I can use the x86-64 CLI but not the arm64 CLI. i'm running it on another 64-bit ubuntu with the same problem!

Just to make sure. Do you mean that the pre-compiled CLIs also produces the same exceptions on a Ubuntu 22.04 x86-64 machine?

**Comment by paopaooux** [comment]
Here's my hardware and kuzu info that may help solve the problem
CPU :Intel® Core™ i5-6300U CPU @ 2.40GHz × 4
GPU: Mesa Intel® HD Graphics 520 (SKL GT2)
Memory: 16.0 GiB
Disk size: 256GB
kuzu version: 0.4.2.2

**Comment by paopaooux** [comment]
> > > Hi @paopaooux,
> > > Could you please test our pre-compiled CLI:
> > > [x86-64](https://github.com/kuzudb/kuzu/releases/download/v0.4.2/kuzu_cli-linux-x86_64.tar.gz) [arm64](https://github.com/kuzudb/kuzu/releases/download/v0.4.2/kuzu_cli-linux-aarch64.tar.gz)
> > > to see if it works for you?
> > 
> > 
> > It's 64-bit ubuntu, it's x64 architecture, I can use the x86-64 CLI but not the arm64 CLI. i'm running it on another 64-bit ubuntu with the same problem!
> 
> Just to make sure. Do you mean that the pre-compiled CLI also produces the same exceptions on a Ubuntu 22.04 x86-64 machine?
Yes,The error is basic_string::_S_create

**Comment by paopaooux** [comment]
> > > Hi @paopaooux,
> > > Could you please test our pre-compiled CLI:
> > > [x86-64](https://github.com/kuzudb/kuzu/releases/download/v0.4.2/kuzu_cli-linux-x86_64.tar.gz) [arm64](https://github.com/kuzudb/kuzu/releases/download/v0.4.2/kuzu_cli-linux-aarch64.tar.gz)
> > > to see if it works for you?
> > 
> > 
> > It's 64-bit ubuntu, it's x64 architecture, I can use the x86-64 CLI but not the arm64 CLI. i'm running it on another 64-bit ubuntu with the same problem!
> 
> Just to make sure. Do you mean that the pre-compiled CLI also produces the same exceptions on a Ubuntu 22.04 x86-64 machine?

Yes,The error is basic_string::_S_create

**Comment by mewim** [comment]
@acquamarin I can reproduce this with a Ubuntu 22.04 Docker container:
[issue-3527.tar.gz](https://github.com/kuzudb/kuzu/files/15427199/issue-3527.tar.gz)

Run the following command:
```bash
docker build -t issue-3527 .
docker run issue-3527
```

Output:
```
Opened the database at path: testdb in read-write mode.
Enter ":help" for usage hints.
^[[50;1R^[[50;9R^[[50;17R^[[50;26R^[[50;35R^[[50;44R^[[50;53R^[[50;62R----------------------------------
| result                         |
----------------------------------
| Table person has been created. |
----------------------------------
(1 tuple)
(1 column)
Time: 0.06ms (compiling), 6.97ms (executing)
----------------------------------------
| result                               |
----------------------------------------
| Table organisation has been created. |
----------------------------------------
(1 tuple)
(1 column)
Time: 0.04ms (compiling), 5.60ms (executing)
----------------------------------
| result                         |
----------------------------------
| Table movies has been created. |
----------------------------------
(1 tuple)
(1 column)
Time: 0.05ms (compiling), 6.98ms (executing)
---------------------------------
| result                        |
---------------------------------
| Table knows has been created. |
---------------------------------
(1 tuple)
(1 column)
Time: 0.04ms (compiling), 3.30ms (executing)
-----------------------------------
| result                          |
-----------------------------------
| Table studyAt has been created. |
-----------------------------------
(1 tuple)
(1 column)
Time: 0.02ms (compiling), 2.56ms (executing)
----------------------------------
| result                         |
----------------------------------
| Table workAt has been created. |
----------------------------------
(1 tuple)
(1 column)
Time: 0.02ms (compiling), 6.10ms (executing)
---------------------------------
| result                        |
---------------------------------
| Table meets has been created. |
---------------------------------
(1 tuple)
(1 column)
Time: 0.02ms (compiling), 2.73ms (executing)
-----------------------------------
| result                          |
-----------------------------------
| Table marries has been created. |
-----------------------------------
(1 tuple)
(1 column)
Time: 0.03ms (compiling), 4.14ms (executing)
Opened the database at path: testdb in read-write mode.
Enter ":help" for usage hints.
^[[50;1R^[[50;9R^[[50;17R^[[50;26R^[[50;35R^[[50;44R^[[50;53R^[[50;62R^[[50;71R^[[50;80R--------------------------------------------------
| result                                         |
--------------------------------------------------
| 5 tuples have been copied to the person table. |
--------------------------------------------------
(1 tuple)
(1 column)
Time: 0.25ms (compiling), 94.92ms (executing)
--------------------------------------------------
| result                                         |
--------------------------------------------------
| 3 tuples have been copied to the person table. |
--------------------------------------------------
(1 tuple)
(1 column)
Time: 0.12ms (compiling), 46.44ms (executing)
--------------------------------------------------------
| result                                               |
--------------------------------------------------------
| 3 tuples have been copied to the organisation table. |
--------------------------------------------------------
(1 tuple)
(1 column)
Time: 0.12ms (compiling), 31.85ms (executing)
--------------------------------------------------
| result                                         |
--------------------------------------------------
| 3 tuples have been copied to the movies table. |
--------------------------------------------------
(1 tuple)
(1 column)
Time: 0.13ms (compiling), 32.50ms (executing)
-------------------------------------------------
| result                                        |
-------------------------------------------------
| 6 tuples have been copied to the knows table. |
-------------------------------------------------
(1 tuple)
(1 column)
Time: 0.16ms (compiling), 7.41ms (executing)
-------------------------------------------------
| result                                        |
-------------------------------------------------
| 8 tuples have been copied to the knows table. |
-------------------------------------------------
(1 tuple)
(1 column)
Time: 0.13ms (compiling), 5.22ms (executing)
---------------------------------------------------
| result                                          |
---------------------------------------------------
| 3 tuples have been copied to the studyAt table. |
---------------------------------------------------
(1 tuple)
(1 column)
Time: 0.12ms (compiling), 3.81ms (executing)
--------------------------------------------------
| result                                         |
--------------------------------------------------
| 3 tuples have been copied to the workAt table. |
--------------------------------------------------
(1 tuple)
(1 column)
Time: 0.09ms (compiling), 3.24ms (executing)
-------------------------------------------------
| result                                        |
-------------------------------------------------
| 7 tuples have been copied to the meets table. |
-------------------------------------------------
(1 tuple)
(1 column)
Time: 0.08ms (compiling), 3.49ms (executing)
---------------------------------------------------
| result                                          |
---------------------------------------------------
| 3 tuples have been copied to the marries table. |
---------------------------------------------------
(1 tuple)
(1 column)
Time: 0.08ms (compiling), 3.83ms (executing)
Opened the database at path: testdb in read-write mode.
Enter ":help" for usage hints.
-------------------------------------------------------------------------
basic_string::_M_create
```

**Comment by acquamarin** [comment]
Hi,
After some investigation, we found that the issue is caused by the shell when printing out the query result. The call function `show_connection` should work as expected on python/c++ apis.
We will fix this soon, thanks for reporting.
