### ISSUE TITLE
Bug: Error results when calling shortest_path

### ISSUE THREAD

**Issue by paopaooux** [kuzudb/kuzu#3536]
### Kùzu version

v0.4.2.2

### What happened?

We use tinysnb dataset and run follow cypher statement,the wrong result appears
```
kuzu> call shortest_path(graph('movies','knows'),2) return *;
----------------------
| src | dst | length |
----------------------
| 2:0 | 2:0 | 0      |
----------------------
| 2:0 | 2:1 | 1      |
----------------------
| 2:0 | 2:2 | 1      |
----------------------
| 2:1 | 2:0 | 1      |
----------------------
| 2:1 | 2:1 | 0      |
----------------------
| 2:1 | 2:2 | 1      |
----------------------
| 2:2 | 2:0 | 1      |
----------------------
| 2:2 | 2:1 | 1      |
----------------------
| 2:2 | 2:2 | 0      |
----------------------
(9 tuples)
(3 columns)
Time: 0.36ms (compiling), 4.23ms (executing)
```
There's no connection between movies and movies.
```
kuzu> match (a:movies)-[]->() return a;
-----
| a |
-----
(0 tuples)
(1 column)
Time: 4.73ms (compiling), 3.94ms (executing)

```

**Comment by semihsalihoglu-uw** [comment]
@andyfengHKU can comment but I think this leaked in. We were not supposed to release this function yet. We are still working on some of these CALL functions. It will take a while. So don't use it please. It should not be part of an official release. I'll ask around how to turn this feature off.

**Comment by paopaooux** [comment]
> @andyfengHKU can comment but I think this leaked accidentally. We were not supposed to release this function yet. We are still working on some of these CALL functions. It will take a while. So don't use it please. It should not be part of an official release. I'll ask around how to turn this feature off.

Ok, thank you very much for your reply

**Comment by semihsalihoglu-uw** [comment]
👍 For shortest paths you can use these: (i) https://docs.kuzudb.com/cypher/query-clauses/match/#single-shortest-path; or (ii) https://docs.kuzudb.com/cypher/query-clauses/match/#all-shortest-paths.
