### ISSUE TITLE
website and documenation loading times really slow to the point of now useable

### ISSUE THREAD

**Issue by suiluj** [kuzudb/kuzu#3544]
### Description

hi i am playing around with kuzu and like it a lot.

I am planning to use kuzu in combination with duckdb/arrow.

but the whole website is loading really slow (especially the documentation).

The side is loading for a minute until you can read everything on the page. At least it is that slow when requesting the site from Germany.

So perhaps you could host the website on a different server/cdn. Otherwise it is no fun to read.

Thanks in advance!

### Link

https://docs.kuzudb.com/

**Comment by mewim** [comment]
Hi @suiluj,

Our website and docs are hosted on GitHub: https://github.com/kuzudb/kuzu-docs and we have also enabled CloudFlare CDN for it. I did a quick test with uptrends (report: https://www.uptrends.com/tools/web-page-speed-test?toolRequestGuid=7f1fc3ce-f345-459f-807f-ba67ab2605d3) and it seems that the loading time from Berlin is about 1 second for the index page of docs. Is it very slow for you to load every page or is there some particular pages that are slow for you?

**Comment by suiluj** [comment]
oh okay strange. then it perhaps a problem why my internet provider. strange because other website are as fast a usual.

This page in the docs is very slow (because of the images I guess):

https://docs.kuzudb.com/visualization/

**Comment by mewim** [comment]
@suiluj,
It seems that this page is slower, but can also be loaded in about 2 seconds on uptrends: 
https://www.uptrends.com/tools/web-page-speed-test?toolRequestGuid=a0665970-b1b1-4138-ad3c-7d6897277778

As a workaround, I would suggest you to clone the docs and access it locally.
