### ISSUE TITLE
Bug: IndexError: _Map_base::at in Kuzu v0.4.2 when executing Cypher query

### ISSUE THREAD

**Issue by joyemang33** [kuzudb/kuzu#3560]
### Kùzu version

v0.4.2

### What happened?

When I executed the following fuzzing Cypher query, an exception happened.
```Cypher
MATCH (DreU92rOW5jkyQD2WgK1J:L0:L4:L1:L3)-[:T0|:T4|:T7|:T3*..9]->(DreU92rOW5jkyQD2WgK1J), (DreU92rOW5jkyQD2WgK1J),
 (DreU92rOW5jkyQD2WgK1J:L4)<-[:T8|:T6|:T0|:T7|:T1|:T5|:T4]-(DreU92rOW5jkyQD2WgK1J)
-[JPhAOWgL5Oi2zb3GueD7:T4|:T2|:T5]-(NWgAEbW1xFiuOc:L0:L3:L2)-[BIF1SqfcwE1F5fsRqR7Y]
-(NWgAEbW1xFiuOc:L3:L0)RETURN COUNT (*)
```
It will result the following exception:
```
IndexError: _Map_base::at
```

### Are there known steps to reproduce?

The graph data can be easily imported by executing the statements in the attached JSON file in order.

[graph.json](https://github.com/kuzudb/kuzu/files/15500314/G_11.json)

**Comment by acquamarin** [comment]
This is a bug related to semi-mask join, @ray6080 will help you fixing the bug.

**Comment by acquamarin** [comment]
already fixed by @andyfengHKU
