### ISSUE TITLE
Bug: unstable query result when execute predicate 

### ISSUE THREAD

**Issue by joyemang33** [kuzudb/kuzu#3569]
### Kùzu version

v0.4.2

### What happened?

I execute the following Cypher query multiple times but it will unstably return "20" or "21".

```Cypher
MATCH (a) WHERE (a.p34 = 'aXKCUJeQQwHo') OR (a.p45 = true) RETURN COUNT (*)
```

### Are there known steps to reproduce?

The graph data can be imported by executing the statements in the attached JSON file in order.
[here](https://github.com/user-attachments/files/15525121/G_28.json)

**Comment by acquamarin** [comment]
Hi @joyemang33 
This is a bug related to the hash index scan and has already been fixed by us on latest master.
Are you using our python api? If yes, you can try our nightly build package.
Otherwise, you may have to build from source.

**Comment by joyemang33** [comment]
Thank you a lot @acquamarin , I will continue my testing on the newest Python package.
