### ISSUE TITLE
Incorrect statistics on relationship table.

### ISSUE THREAD

**Issue by andyfengHKU** [kuzudb/kuzu#3572]
### Kùzu version

master

### What happened?

When running `CALL storage_info('knows') RETURN *` on `tinysnb`. The min & max value on `date` column is incorrect. It reflects the statistics for initial copy but not for the second one.

**Comment by andyfengHKU** [comment]
I face a similar problem with

```
CALL storage_info('studyAt') RETURN * on `tinysnb`. The fwd_year min & max are `0, 2021` which is incorrect.
```

**Comment by benjaminwinger** [comment]
Same issue, but different place I think. The minimum and maximum for the initial copy (in ColumnChunk) are including null values. I'd just fixed it before for updates.
