### ISSUE TITLE
Bug: KU_UNREACHABLE for UUID values when copying from a loaded DataFrame

### ISSUE THREAD

**Issue by brianwisti** [kuzudb/kuzu#3587]
### Kùzu version

v0.4.2

## Summary

When copying to a table from a loaded DataFrame containing UUID values, Kùzu raises a `KU_UNREACHABLE` error and no data is copied.

## My Story

I'm building a graph consisting of potentially multi-line blocks of text identified by UUID, and exploring ways to do this without the reformatting hassle of CSV or the performance hit of of CREATE statements (though performance is improved by wrapping the create statements in a transaction).

The support for copying from a loaded DataFrame seems promising, but Kùzu raises an error when UUID values are loaded from a DataFrame.

Output using the code in reproducing section code sample:

```
Traceback (most recent call last):
  File "/Users/random/dev/kuzu-uuid-bug/main.py", line 13, in <module>
    conn.execute("COPY Block FROM (LOAD FROM df RETURN *)")
  File "/Users/random/dev/kuzu-uuid-bug/.venv/lib/python3.11/site-packages/kuzu/connection.py", line 131, in execute
    _query_result = self._connection.query(query)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Assertion failed in file "/private/var/folders/7v/l3_p0vq96qn_ck27n1cq5ql80000gn/T/cibw-sdist-ajrk0lr5/sdist/kuzu-source/tools/python_api/src_cpp/py_conversion.cpp" on line 33: KU_UNREACHABLE
```

I have been unable to find a workaround on my own. The database recognizes the value is a string when it should be a UUID if I attempt to use `uuid4().hex`, and does not copy the data.

I am new to Kùzu and Cypher, so if there's a correct path or workaround I'm missing, please let me know!

## System

- Operating System: macOS Sonoma 14.5
- Python: 3.11.4
- Kuzu: v0.4.2
- PyArrow: 16.1.0
- Pandas: 2.2.2

### Are there known steps to reproduce?

Here's a minimal case to reproduce on my system:

```python
import uuid

import kuzu
import pandas as pd


db_name = "db"
db = kuzu.Database(db_name)
conn = kuzu.Connection(db)
conn.execute("CREATE NODE TABLE Block ( uuid uuid, primary key (uuid));")
df = pd.DataFrame([{"uuid": uuid.uuid4()}])
conn.execute("COPY Block FROM (LOAD FROM df RETURN *)")
```

**Comment by andyfengHKU** [comment]
Hi @brianwisti, thanks for reporting. It is indeed a bug on our python API where UUID type is not parsed for DataFrame. We will fix this soon.

Meanwhile, casting uuid first to string on DataFrame and back to UUID while loading works for me.
```
import uuid

import kuzu
import pandas as pd


db_name = "db"
db = kuzu.Database(db_name)
conn = kuzu.Connection(db)
conn.execute("CREATE NODE TABLE Block ( uuid uuid, primary key (uuid));")
df = pd.DataFrame([{"uuid": str(uuid.uuid4())}])
conn.execute("COPY Block FROM (LOAD FROM df RETURN cast(uuid, 'UUID'))")
```

Let me know if this helps you with prototyping.

Best,
Xiyang

**Comment by brianwisti** [comment]
Thank you! The workaround you provided works for this case. And just in case another absolute beginner wanders in from a Web search, wondering how to apply this workaround when loading more complex objects:

```python
import uuid

# ...

conn.execute(
    "CREATE NODE TABLE Block (uuid uuid, text string, primary key (uuid));"
)
df = pd.DataFrame(
    [{"uuid": str(uuid.uuid4()), "text": "Graphs are cool"}]
)
conn.execute("COPY Block FROM (LOAD FROM df RETURN cast(uuid, 'UUID'), text)")
```
