### ISSUE TITLE
Bug: command client is missing some commands

### ISSUE THREAD

**Issue by uwegeercken** [kuzudb/kuzu#3598]
### Kùzu version

v0.4.2

### What happened?

In earlier versions of the command client there where commands such as:

:list_nodes     list all node tables
:list_rels     list all rel tables
:show_node     [table_name] show node schema
:show_rel     [table_name] show rel schema

In version 0.4.2 these are missing. Once some tables and relations have been created, it is hard to work without these commands.

**Comment by andyfengHKU** [comment]
Hi @uwegeercken,

We now moves to `CALL show_tables() RETURN *` and `CALL table_info("table_name") RETURN *` which should give u the same information as before.

The rationale is to make this feature available to not only CLI but all language bindings. So we move it to the database internal.

**Comment by uwegeercken** [comment]
Thank you. It would be good then if it would show up on the command client help screen (I did find it in the documentation).
