### ISSUE TITLE
Feature: Json type support

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#3609]
# Design goal
1. Support json in the kernel and use as if it is an internal type in the system.
e.g. DDL: 
`CREATE NODE TABLE PERSON (ID INT64, DESCRIPTION JSON)`
       Data Insertion: 
`CREATE (p:PERSON {ID: 5, DESCRIPTION: '{ "family": "anatidae", "species": [ "duck", "goose", "swan", null ] }'})`
2. Json can be install and loaded as an official extension using cypher queries:
`INSTALL JSON;`  `LOAD EXTENSION JSON;`
3. Support load from/copy from/ copy to  a json file.
e.g. `LOAD FROM 'test.json' RETURN *;`  `COPY (MATCH (p:person) return p.DESCRIPTION) TO 'test.json'`
4. Support common json utility functions:
e.g.  `json_keys(json[, path])`   `json_array_length(json[, path])`

## DataType registeration
Json will be implemented as user defined type in kuzu and stored in the catalog using the existing user defined type framework. Json can be treated as an alias for kuzu built-in type string, meaning that we store `JSON` as string on disk.
Can be registered as simple as:
```
catalog->createType(trx, "json", *LogicalType::STRING());
```

## Json parsing and traversing
We are going to use `yyjson` which is a high performance JSON library written in ANSI C.
yyjson takes in a json string and converts it into a json document as well as providing multiple ways to traverse the keys and values.

## DDL statement & create statement
1. DDL: `CREATE NODE TABLE PERSON (ID INT64, DESCRIPTION JSON)`
2. CREATE: `CREATE (P:PERSON {ID: 5, DESCRIPTION: '{ "family": "anatidae", "species": [ "duck", "goose", "swan", null ] }'})`

## Load from/copy from/ copy to
We have to refactor the load from/copy from/copy to use our table function framework. #3414 
Json extension should register the read/write function as table function and binder can choose the correct read/write function based on file type.
1. Load from: `LOAD FROM 'test.json'(format = 'array', other options...)  RETURN *;`
3. Copy from `COPY PERSON from 'test.json' (format = 'array', other options...);`
4. Copy to: `COPY (MATCH (p:PERSON) RETURN *) TO 'test.json'`

## Casting between JSON and built-in types
We can cast kuzu built-in types to json or cast JSON to other kuzu built in types:
```
CAST('{"kuzu": 42}', 'struct(kuzu integer)')     Result:  {'kuzu': 42}
CAST('{kuzu: 42}', 'json')      Result:  {'kuzu': 42}
```

## Utility functions
1. Json creation functions:

| Function                 | Description                                                                                     |
|--------------------------|-------------------------------------------------------------------------------------------------|
| `to_json(any)`           | Create JSON from a value of any type. LIST is converted to a JSON array, and STRUCT and MAP are converted to a JSON object. |
| `json_array([any, ...])` | Create a JSON array from any number of values.                                                  |
| `json_object([key, value, ...])` | Create a JSON object from any number of key, value pairs.                                      |
| `json_merge_patch(json, json)` | Merge two JSON documents together.                                                          |

2. Json extract functions:

| Function                                           | Description                                                                                                      |
|-----------------------------------|--------------------------|
| `json_extract(json, path)`        | Extract JSON from json at the given path. If path is a LIST, the result will be a LIST of JSON.                  |
| `json_extract_string(json, path)` | Extract VARCHAR from json at the given path. If path is a LIST, the result will be a LIST of VARCHAR.            |

3. Json scalar functions:

| Function                                | Description                                                                                                                                                                                                 |
|-----------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `json_array_length(json[, path])`       | Return the number of elements in the JSON array `json`, or 0 if it is not a JSON array. If `path` is specified, return the number of elements in the JSON array at the given path. If `path` is a LIST, the result will be a LIST of array lengths. |
| `json_contains(json_haystack, json_needle)` | Returns true if `json_needle` is contained in `json_haystack`. Both parameters are of JSON type, but `json_needle` can also be a numeric value or a string, however, the string must be wrapped in double quotes.                                  |
| `json_keys(json[, path])`               | Returns the keys of `json` as a LIST of VARCHAR, if `json` is a JSON object. If `path` is specified, return the keys of the JSON object at the given path. If `path` is a LIST, the result will be a LIST of LIST of VARCHAR.                     |
| `json_structure(json)`                  | Return the structure of `json`. Defaults to JSON if the structure is inconsistent (e.g., incompatible types in an array).                                                                                    |
| `json_type(json[, path])`               | Return the type of the supplied `json`, which is one of ARRAY, BIGINT, BOOLEAN, DOUBLE, OBJECT, UBIGINT, VARCHAR, and NULL. If `path` is specified, return the type of the element at the given path. If `path` is a LIST, the result will be a LIST of types. |
| `json_valid(json)`                      | Return whether `json` is valid JSON.                                                                                                                                                                         |
| `json(json)`                            | Parse and minify `json`.                                                                                                                                                                                    |

### Operators:
1. Retrive key value: `SELECT j.family FROM example;`
2. Extract the family key’s value with a JSONPath expression: `SELECT j->'$.family' FROM example;`
3. Extract the family key’s value with a JSONPath expression as a VARCHAR: `SELECT j->>'$.family' FROM example;`

**Comment by prrao87** [comment]
Hi @acquamarin this is great. Is there a means to support single JSON blob insertion via `MERGE` too?

**Comment by mxwli** [comment]
Note: The semantics of `json_contains` a user might expect is more complicated than it might seem. DuckDB doesn't specify their semantics in their documentation, but MySQL does, so I'll be following their specification here. `https://dev.mysql.com/doc/refman/8.4/en/json-search-functions.html#function_json-contains`

**Comment by mxwli** [comment]
This feature has been implemented. There are still some feature that are not done, though. I'll open a separate issue for that.
