### ISSUE TITLE
Bug: Issue with Kuzu to Networkx

### ISSUE THREAD

**Issue by Kamalika17** [kuzudb/kuzu#3640]
### What happened?

Hi,

I am using the kuzu to networkx functionality:
`res = conn.execute('MATCH (u:User)-[r:Rating]->(m:Movie) RETURN u, r, m LIMIT 250')`
`G = res.get_as_networkx(directed=False)`

When I use this for the graph I created, I noticed that it does not support multiple edges between the same nodes (say A and B have a connection between them with condition X and Y). eg: It removes 
`(A)-[rel: a2b {category:Y}]->(B)` and only keeps `(A)-[rel: a2b {category:X}]->(B)`.

Is there a way to resolve this?

Thanks in advance!

**Comment by prrao87** [comment]
Hi @Kamalika17, could you please provide a sample graph that we can use to reproduce the issue? If you can generate a graph using mock (not proprietary) data, you can share the Kùzu database directory with us here by zipping it and uploading the zip file to this GitHub issue.

**Comment by prrao87** [comment]
Hi @Kamalika17, could you please upload a zip file of a portion of the data that replicates this issue? We'll take a look and get back to you. Thanks!

**Comment by Kamalika17** [comment]
Hi @prrao87 ,

[Test_folder.zip](https://github.com/user-attachments/files/15834942/Test_folder.zip)

I have uploaded a "Test_folder" containing my code in jupyter notebook and an example of the issue I mentioned. The query result differs from the networkx graph object.
The edge "Adam to Waterloo" should be there twice with different properties. However, it removes one of the edges when adding to the networkx graph object.

Please let me know if I am doing something wrong or there is a way to resolve this.

Regards,
Kamalika

**Comment by Kamalika17** [comment]
Hi @prrao87 

I check the code given in the [QueryResult.get_as_networkx Python API](https://kuzudb.com/api-docs/python/kuzu.html#QueryResult.get_as_networkx) The graph object is not a multigraph.
`nx_graph = nx.DiGraph() if directed else nx.Graph()` 
A multigraph or multiDiGraph requires the networkx object to be declared as:
`nx.MultiGraph() or nx.MultiDiGraph()`

**Comment by prrao87** [comment]
Hi @Kamalika17, apologies for the delayed response. Yes, indeed, the reason you mentioned seems to be why multiple edges aren't being stored. We will look into this some more and make the necessary updates to the API. Thanks for reporting!

**Comment by prrao87** [comment]
Hi @Kamalika17, just reaching out again to get a better understanding of your requirements for MultiGraph. Because it uses a list of dicts of dicts of dicts, it does add complexity to the transformation from the underlying Kùzu query result to this format. What graph algorithms would you be using such a NetworkX graph with? Would you be using weighted edges or nodes? This might require a bit more tweaking and testing to ensure that the underlying graph in Kuzu is properly represented, and that we are able to read the data back from NetworkX to Kuzu downstream. Any additional information on your use case would help. Thanks!

**Comment by kamalikaray** [comment]
Hi @prrao87 

We haven't thought about algorithms to apply on this graph as of now. However, multigraphs are a valuable tool to represent interactions in biological systems, social networks (eg: two people can be connected in more than one way, helps to infer communities or information diffusion) more accurately than simpler graph structures. In our graph we have different edge properties. Depending on the number of edges between the same two entities, we plan to assign edge weights.
Moreover, it becomes a bit misleading if KUZU as a GraphDB supports multigraph and it is not reflected when it is converted to a networkx object. As I had mentioned, the pandas data frame provides the correct result which is not shown in the networkx object.

**Comment by prrao87** [comment]
@Kamalika17 understood - we were discussing about making the MultiGraph the default option for the get_as_networkx method to avoid this issue. We'll prioritize accordingly and make the fix. Again, thanks a lot for reporting!

**Comment by kamalikaray** [comment]
Hi @prrao87 

I was using the newly updated get_as_networkx function. I believe there is a bug in the multi-graph implementation when a complex query is given. 
In my example, I run the following query:
`MATCH (a:User)-[l:LivesIn]->(c:City)-[p:PartOf]->(con:County)
RETURN a, c, l, p, con `
            
The two edges between Adam and Waterloo makes sense as the two edges between the same nodes have different properties. However, it gives out 3 edges between Waterloo and County1 which are actually duplicates, there should be only 1 edge between the two as the information on the edge is the same. Similarly, if I keep extending the search, lot of duplicate edges are created.

I have attached the test folder (New_test_592024)

[New_test_592024.zip](https://github.com/user-attachments/files/16893971/New_test_592024.zip)

Please let me know how to resolve this.

Thanks,
Kamalika

**Comment by prrao87** [comment]
Hi @Kamalika17, indeed, it seems like the deduplication logic we have currently for multi-edges is insufficient. I've created a new issue and tagged @mewim on it and we will take a look at it and get back to you. Thanks for reporting!

**Comment by kamalikaray** [comment]
Hi @prrao87 

Thanks for your response. There is one more issue with converting complex query outputs to a networkx object,

`MATCH (a:User)-[l:LivesIn]->(c:City)`
`OPTIONAL MATCH (c)-[p:PartOf]->(con:County)`
`RETURN a, c, l, p, con `

Taking the above query as an example, if there is no record in the database for the second part of the query even if there is for the first part, ie, if there is no county connected to the city, the functions throws an error that "NoneType object is not subscriptable".

Query result from Kuzu database
  a.username  a.age     c.name  c.population    l.role con.county
0       Adam     30   Waterloo        150000  Resident    county1
1       Adam     30   Waterloo        150000    Worker    county1
2    Karissa     40   Waterloo        150000  Resident    county1
3      Zhang     50  Kitchener        200000  Resident    county2
4      Noura     25     Guelph         75000    Worker        NaN

**Comment by prrao87** [comment]
That makes sense. Is the optional match really required in your actual use case, though? The above issue could easily be avoided by only returning results from a single match clause, because you're reusing the variable `c` in the example, i.e., `MATCH (a:User)-[l:LivesIn]->(c:City)-[p:PartOf]->(con:County)` in one single line.

The main intended use case of the `get_as_networkx()` was to help users quickly isolate subgraphs of interest and apply NetworkX algorithms to the isolated subgraph. If you could provide the actual query that you're intending to run on your data, maybe that could help us identify the right way to incorporate this behaviour.

**Comment by prrao87** [comment]
Tried the code above based on #4282, and it works as intended 👌🏽.

```
['Person_Alice', 'Product_Phone', 'Person_Bob']
[('Person_Alice', 'Product_Phone', 0), ('Person_Bob', 'Product_Phone', 0)]
```

**Comment by prrao87** [comment]
> However, with this `MATCH (a:User)-[l:LivesIn]->(c:City)-[p:PartOf]->(con:County)` query it won't give any result if the entire link is not present in the graph

This is intended behaviour in Cypher, because if the path is non-existent and the path pattern was specified explicitly in the query, it would be an empty result, correct?

**Comment by prrao87** [comment]
I suppose the bigger question is this: what is the goal of the query and the `OPTIONAL MATCH` in your actual use case?

**Comment by prrao87** [comment]
I see, so it seems like you want to fan out using the nodes returned from a given match subquery - I don't think `OPTIONAL MATCH` is the right way to achieve this - let me check some more on my end and get back to you.
