### ISSUE TITLE
Bug: Filtering recursive relationships: `WHERE ...` leads to infinite loop

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#3691]
### Kùzu version

v0.4.2

### What operating system are you using?

Fedora 39

### What happened?

```cypher
CREATE NODE TABLE V (id INT64, PRIMARY KEY(id));
CREATE REL TABLE E(FROM V TO V);

CREATE (:V {id: 1})-[:E]->(:V {id: 2})-[:E]->(:V {id: 3})-[:E]->(:V {id: 4});
MATCH (v)-[e* (r,n | WHERE true)]->(v2) RETURN *;
```
Last statement will hang process. Expected would be that `WHERE true` is just a no op, that doesn't filter out anything.

Edit:
Same for 
```cypher
MATCH (v)-[e*(r,n | WHERE label(r) = "E")]->(v2) RETURN e;
MATCH (v)-[e* (r,n | WHERE EXISTS {MATCH (:V {id: 1})})]->(v2) RETURN e; // dummy exists condition here
```

I think it also makes a lot of sense to have a global timeout in case of any query loops/ too costly queries or similar.

**Comment by acquamarin** [comment]
Hi @sapalli2989 
We do allow user to set the timeout value for a query.
The command is:
`CALL TIMEOUT=3000;`
You can find detailed doc there: https://docs.kuzudb.com/cypher/configuration/#_top

**Comment by sapalli2989** [comment]
Update: Could confirm, that it still hangs with latest Kuzu cli nightly.
