### ISSUE TITLE
Feature: negative array index 

### ISSUE THREAD

**Issue by min-mwei** [kuzudb/kuzu#3700]
### API

Other

### Description

It would be nice to support "negative index" which in many cases it would be more intuitive. 

```
with [0,1] as k return k[-2], k[-1];
+---------------+
| k[-2] | k[-1] |
+---------------+
| 0     | 1     |
+---------------+
```

**Comment by andyfengHKU** [comment]
Hi @min-mwei this should be solved in #3733
