### ISSUE TITLE
Bug: field name conflicts with keyword is surprising 

### ISSUE THREAD

**Issue by min-mwei** [kuzudb/kuzu#3721]
### What happened?

field name conflicts with keyword. This will make it difficult in real world scenarios.

```
kuzu> create node table acme(id string, call string, primary key(id));
Error: Parser exception: mismatched input 'call' expecting PRIMARY (line: 1, offset: 34)
"create node table acme(id string, call string, primary key(id))"
```

**Comment by acquamarin** [comment]
The issue has been fixed in our latest master, please compile kuzu from source, or use our python nightly build package
