### ISSUE TITLE
Feature: Support negation in list operators

### ISSUE THREAD

**Issue by prrao87** [kuzudb/kuzu#3727]
### API

Other

### Description

Just tested in the latest nightly build (0.4.3dev41), and it seems like we do not support negation on the `IN` list operator.

Here's the query I want to run:

```cypher
MATCH (e)-[r]->(t)
WHERE r.type NOT IN ["IsFrom"]
RETURN *;
```

This should return all paths whose relation type is *not* `IsFrom`, but it produces the following error:

```
The evaluation of this query failed with the following error:
Parser exception: Query must conclude with RETURN clause (line: 1, offset: 0)
"MATCH (e)-[r]->(t)"
```

The following query, which is the reverse (returning only those relationships that are of type "IsFrom"), works:

```cypher
MATCH (e)-[r]->(t)
WHERE r.type IN ["IsFrom"]
RETURN *;
```

Can we also support negation on the `IN` operator?

**Comment by prrao87** [comment]
@andyfengHKU feel free to reassign - I just wanted this to be documented for now. Thanks!

**Comment by andyfengHKU** [comment]
@prrao87 

I think we should probably use `NOT r.type IN` instead of `r.type NOT IN`. The former one we should support already. Can u double check if Neo4j support the latter one?

**Comment by prrao87** [comment]
Yup, their Cypher docs make this really hard to find, but it seems like Neo4j also only supports `NOT r.type IN`. Let's close this issue and the PR as you suggested.
