### ISSUE TITLE
Feature: Show data row on data load exception

### ISSUE THREAD

**Issue by ceteri** [kuzudb/kuzu#3771]
### API

Python

### Description

When loading, e.g., using `COPY FROM`, when there is an exception is it possible to show the data row which caused the exception?

This would likely be used in each API?

**Comment by semihsalihoglu-uw** [comment]
Here's a summary of what we can do for now and I think we should do this before the next release:
- Provide row offset and the file (in case of copying from multiple files)
- If the error happens in the file reader, also print the row number

**Comment by ray6080** [comment]
We now can support skipping malformed csv rows and keep a record of skipped rows in our latest release 0.7.0. https://blog.kuzudb.com/post/kuzu-0.7.0-release/#allow-skipping-erroneous-rows-during-copyload-from
