### ISSUE TITLE
Functions for recursive relationships is not documented

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#3803]
### Description

In the [recursive relationships part of the documentation](https://docs.kuzudb.com/cypher/query-clauses/match/#match-variable-lengthrecursive-relationships), we have an example that says that one can call the length function on recursive relationships:
```
MATCH (a:User)-[e:Follows*1..2]->(b:User)
WHERE a.name = 'Adam'
RETURN b.name, length(e) AS length;
```
However this is very difficult to find. Recursive relationships do not also appear under [data types](https://docs.kuzudb.com/cypher/data-types/#rel). We should put recursive relationships as a separate data type in the [data types part of the documentation](https://docs.kuzudb.com/cypher/data-types/#rel), explain exactly what it is and list the functions we support for them (even if it's only `length`) as a category under [the functions part of the documentation](https://docs.kuzudb.com/cypher/expressions/#functions).

**Comment by prrao87** [comment]
Done in https://github.com/kuzudb/kuzu-docs/commit/4b0b9cc2b4f356396d83222aa3183e678097b43b
