### ISSUE TITLE
Bug: [Python API] Prepared statement `dict`  value should be interpreted as `STRUCT`, not `MAP`

### ISSUE THREAD

**Issue by sapalli2989** [kuzudb/kuzu#3814]
### Kùzu version

nightly

### What operating system are you using?

Fedora 39

### What happened?

Python API currently enforces that all values of a `dict` have the same type, which is not always desired:
```python
import kuzu
import tempfile

with tempfile.TemporaryDirectory() as dbpath:
    conn = kuzu.Connection(kuzu.Database(dbpath))
    result = conn.execute(
        "WITH $triples as t RETURN t;",
        {"triples": [{"subject_id": 1, "verb": "is", "object_id": 2}]},
    )
    print(result.get_next())
```
> Traceback (most recent call last):
  File "/tmp/proj/main.py", line 7, in <module>
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/tmp/proj/venv/lib64/python3.12/site-packages/kuzu/connection.py", line 133, in execute
    _query_result = self._connection.execute(prepared_statement._prepared_statement, parameters)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'is'

 (In contrast `{"triples": [{"subject_id": 1, "verb": 5, "object_id": 2}` would work.)

If `MAP` is needed as prepared statement value, there might be basic conversion provided for `STRUCT`. Like `cast`ing `STRUCT`->`MAP`, while checking that each keys and values of `STRUCT` have same type. Currently casting raises an error:
```cypher
kuzu> RETURN cast({a: 1, b: 2}, "MAP(STRING,INT)") ;
Error: Conversion exception: Unsupported casting function from STRUCT to MAP.
```

**Comment by mxwli** [comment]
The main problem with this is that structs aren't always desired either.

Struct keys are enforced to be *case insensitive strings*, and nothing else. The value of the struct itself is inside the value of its elements, while the key names are encoded inside the schema, so the keys in a list of structs must all be identical. On the other hand, the rule for maps is that all keys have the same type, and all values have the same type. There's no equivalent enforcement in python, but if you look at their type annotation system, you'll find that you can't specify dictionaries whose keys may be different types, and whose values may be different types. Also, Python dicts are variable sized, as is Kuzu maps, unlike structs. Overall I think dicts are more semantically similar to Kuzu maps than structs.

Asides from the problems I described above, we might break existing code by inferring for all dicts to be structs. The solution that closes this issue works and does encourage users to enforce for the types to be the same, though.

**Comment by sapalli2989** [comment]
Thanks! I think https://github.com/kuzudb/kuzu/pull/3824 is a good way to distinguish passing of `STRUCT`s and `MAP`s.
