### ISSUE TITLE
Documentation for size function for lists 

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#3817]
### Description

I noticed that there is a size() function that we can run on lists as follows:
```
...
RETURN size(listFoo)
```
where listFoo is a list. However I cannot find the documentation for it. I went to https://docs.kuzudb.com/cypher/expressions/list-operators/ but it's not listed there. It may be listed somewhere else but let's still mention it somehow in this part of the documentation.

**Comment by acquamarin** [comment]
I think `size` is listed in the `list_functions` section rather than `list_operators` sections: https://docs.kuzudb.com/cypher/expressions/list-functions/

**Comment by semihsalihoglu-uw** [comment]
We are not addressing the main problem: We should rethink the structure of functions vs operators. From a user's perspective this distinction is unimportant. I was looking for size and landed on the "list operators" page (though the title of that is also confusingly called "List Functions"), and couldn't find size.

We should either list these on the same page and call the page "List Functions and Operators" or at the very least add links from both to each page so users landing on one of the pages can discover the other. 

I'll let @prrao87 make the calls here.

**Comment by andyfengHKU** [comment]
All list operators are now list functions.
