### ISSUE TITLE
Feature: Auto-detect min/max values in DataFrame column to downcast integers

### ISSUE THREAD

**Issue by prrao87** [kuzudb/kuzu#3847]
### API

Python

### Description

Tested on 0.4.3.dev57

Say I have this input CSV (files attached as zip archive):
```
id,amount,counts,birthdate,is_valid,comment
a68a8af4-4a53-4420-9cb8-4a3e1fa0f324,3.635742,89,1990-01-01,true,"This is a test. "
55cfb01c-8cfc-4e3f-8408-05f362d7cf31,9.381905,57,2001-03-27,false,"This is another ""test"". "
9cddb5ae-e1d8-4382-b364-19b67e9a45a5,1.668131,29,2004-02-29,true,"This is (yet) another \"test\". "
```
I'd like to use the following schema for the node table that's created from the CSV:
```cypher
CREATE NODE TABLE Item(
    id STRING,
    amount DOUBLE,
    counts INT32,
    birthdate STRING,
    is_valid BOOLEAN,
    comment STRING,
    PRIMARY KEY(id)
)
```
If I want the `counts` column to be INT32 instead of the default INT64, I have to manually cast it using `LOAD FROM` on the DataFrame as follows:

```
COPY Item FROM (
    LOAD FROM df
    RETURN
      id,
      amount,
      CAST(counts AS INT32),
      date
      is_valid,
      comment
)
```
There are two inconveniences here:
1. Just for casting the one column in the entire DataFrame, we have to explicitly write out every column name (which is verbose if we have 10+ columns, which is really common in real world data). If we don't do the manual casting, the `COPY` will fail.
2. The min/max integer information for a column in a DataFrame is already known beforehand, so Kùzu (in theory) can estimate the right integer type for this range, rather than the user having to manually cast the type by calculating their data ranges.

The provided code in the zip file shows how DuckDB does this - it seems to auto-detect the ranges of integers, downcasting the `INT64` type from Pandas/Polars DataFrame. Here's an example of DuckDB's output before (once the Polars df is read) and after (Outputting the results of a query and sending it to a Polars df).

Before:
```
┌─────────────────────────────────┬──────────┬────────┬────────────┬──────────┬────────────────────────────────┐
│ id                              ┆ amount   ┆ counts ┆ birthdate  ┆ is_valid ┆ comment                        │
│ ---                             ┆ ---      ┆ ---    ┆ ---        ┆ ---      ┆ ---                            │
│ str                             ┆ f64      ┆ i64    ┆ str        ┆ bool     ┆ str                            │
╞═════════════════════════════════╪══════════╪════════╪════════════╪══════════╪════════════════════════════════╡
│ a68a8af4-4a53-4420-9cb8-4a3e1f… ┆ 3.635742 ┆ 89     ┆ 1990-01-01 ┆ true     ┆ This is a test.                │
│ 55cfb01c-8cfc-4e3f-8408-05f362… ┆ 9.381905 ┆ 57     ┆ 2001-03-27 ┆ false    ┆ This is another "test".        │
│ 9cddb5ae-e1d8-4382-b364-19b67e… ┆ 1.668131 ┆ 29     ┆ 2004-02-29 ┆ true     ┆ This is (yet) another \test\.  │
└─────────────────────────────────┴──────────┴────────┴────────────┴──────────┴────────────────────────────────┘
```
After (note how the `counts` column is now an `INT32`, which presumably came from DuckDB):
```
┌─────────────────────────────────┬──────────┬────────┬────────────┬──────────┬────────────────────────────────┐
│ id                              ┆ amount   ┆ counts ┆ birthdate  ┆ is_valid ┆ comment                        │
│ ---                             ┆ ---      ┆ ---    ┆ ---        ┆ ---      ┆ ---                            │
│ str                             ┆ f64      ┆ i32    ┆ date       ┆ bool     ┆ str                            │
╞═════════════════════════════════╪══════════╪════════╪════════════╪══════════╪════════════════════════════════╡
│ a68a8af4-4a53-4420-9cb8-4a3e1f… ┆ 3.635742 ┆ 89     ┆ 1990-01-01 ┆ true     ┆ This is a test.                │
│ 55cfb01c-8cfc-4e3f-8408-05f362… ┆ 9.381905 ┆ 57     ┆ 2001-03-27 ┆ false    ┆ This is another "test".        │
│ 9cddb5ae-e1d8-4382-b364-19b67e… ┆ 1.668131 ┆ 29     ┆ 2004-02-29 ┆ true     ┆ This is (yet) another \test\.  │
└─────────────────────────────────┴──────────┴────────┴────────────┴──────────┴────────────────────────────────┘
```

In Kùzu, we could potentially save a lot of user effort (and compress the data better, while also improving performance) if we auto-detect the integer ranges to downcast integer types to INT32 rather than defaulting to INT64 for every use case.

[files.zip](https://github.com/user-attachments/files/16266357/files.zip)

**Comment by andyfengHKU** [comment]
This should be solved in #3891
