### ISSUE TITLE
Feature: support SKIP rows in LOAD FROM for COPY

### ISSUE THREAD

**Issue by mewim** [kuzudb/kuzu#3869]
### API

C++

### Description

Sometimes CSV can have multiple lines of headers. It can be helpful to skip lines while copying from CSVs semantically similar to `COPY ... FROM (LOAD FROM 'csv' RETURN * SKIP ...) `

**Comment by prrao87** [comment]
This is an excellent feature - though in theory we are actually doing this for the `LOAD FROM` utility when scanning, correct? I think I'll change the heading accordingly.

**Comment by prrao87** [comment]
@mewim what do you think about skipping select header columns? If we have 10 columns but we only want to ingest 8 of them, the `SKIP` keyword can be very helpful to avoid having to type out all of the 8 in the `LOAD FROM` clause. I'm not sure if this will conflict with the multiline header you brought up.
