### ISSUE TITLE
Bug: Unexpected segmentation fault on empty table

### ISSUE THREAD

**Issue by Aurora-yzj** [kuzudb/kuzu#3897]
### Kùzu version

v0.4.2

### What operating system are you using?

Ubuntu 22.04

### What happened?

Hi! I found that when the table is empty, directly running `MATCH (n) DETACH DELETE n;` will cause an immediate segmentation fault and core dump without any notification. 
![image](https://github.com/user-attachments/assets/8003fd09-8a7b-4472-9452-c2aace259fb4)

After compiling with debug info, I found that this query triggered an assertion error `Assertion failed in file "/home/auroraeth/Project/1/kuzu/kuzu/src/binder/expression/node_rel_expression.cpp" on line 18: tableIDs.size() == 1`.
Perhaps it would be better to do some exception handling? Thank you!

**Comment by andyfengHKU** [comment]
This should be fixed in #4038
