### ISSUE TITLE
CSV LIST_BEGIN and LIST_END options do not exist

### ISSUE THREAD

**Issue by mxwli** [kuzudb/kuzu#3931]
### Description

In our [csv loading documentation](https://docs.kuzudb.com/import/csv/), we specify for the `list_begin` and `list_end` parameters to denote the beginning and ending of lists. These parameters are not real; the usage of them yields `Error: Binder exception: Unrecognized csv parsing option: LIST_BEGIN.`

**Comment by acquamarin** [comment]
we have already removed those two options.
