### ISSUE TITLE
Bug: Json related issues

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#3947]
### Kùzu version

master

### What operating system are you using?

M1 MAC

### What happened?

All test cases are in `kuzu/extension/json/test/example`
- [x] json_extract on non existing field => `stoi exception`
- [x] copy from exported json file => `std::map exception`

Missing features:
- [x] Missing alias functions:
```
json_quote(any) | Alias for to_json.
array_to_json(list) | Alias for to_json that only accepts LIST.
row_to_json(list) | Alias for to_json that only accepts STRUCT.
```
-[ ] Missing functions:
```
json_array([any, ...]) | Create a JSON array from any number of values.
json_object([key, value, ...]) | Create a JSON object from any number of key, value pairs.
```

**Comment by mxwli** [comment]
What branch are you on? I don't see any `kuzu/extension/json/test/example`

**Comment by acquamarin** [comment]
I already merged my pr, you should see it now.

**Comment by mxwli** [comment]
There is further need for the ability to distinguish between a built in type and a UDT.
For example, if I have the following data
```json
[
{"a": {"b": 1}}
]
```
And run
```
copy (load with headers (a json) from 'data.json' return *) to 'output.json';
```
It turns out that output.json and data.json don't quite match, due to how JSON is indistinguishable from STRINGS
```
// output.json
[
{"a": "{\"b\": 1}"}
]
```
