### ISSUE TITLE
Add SERIAL properties to rel tables.

### ISSUE THREAD

**Issue by Claus1** [kuzudb/kuzu#3961]
### API

Python

### Description

I got 'SERIAL properties are not supported in rel tables.' error  and it is clear why it exists and how to overcome it.
In my scheme, there can be a thousand different types of relationships between two objects (linguistic concepts). The ability to delete an edge by its ID would be extremely useful and, of course, much faster than searching by scanning and comparing all fields.

**Comment by ray6080** [comment]
Hi @Claus1 , this is already supported in our latest dev build. Can u give a try on that? Or wait a few days for our next major release.

**Comment by Claus1** [comment]
Excellent!
