### ISSUE TITLE
Optimization: Push down projection and filter predicates down to scan from source

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu#3979]
### Description

For simple cases, like `LOAD FROM 'a.parquet' WHERE a.age < 10 RETURN a.name`, we should be able to prune unrelated columns and push the filter down when scanning from the parquet file.

This should be generalized to other sources, such as Arrow tables, Polars & Pandas DataFrames, too.

**Comment by andyfengHKU** [comment]
We have applied projection push down to all sources and filter push down to relational tables. Filter push down to parquet is not urgent so I'm closing this issue.
