### ISSUE TITLE
Seemingly unnecessary join order change in MULTI_JOIN seems to change the plan

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#4022]
I'm comparing two HINTs:
```
explain MATCH (a:person)<-[e1]-(b:person)-[e2]->(c:person), (a)-[e3]->(c) HINT (((a JOIN e1) JOIN b) MULTI_JOIN e2 MULTI_JOIN e3) JOIN c return *;
```

<img width="1105" alt="Screen Shot 2024-08-04 at 1 35 59 PM" src="https://github.com/user-attachments/assets/8b145b71-b592-4fe5-9eed-d094601e29ef">

vs the following in which I move the JOIN c to the beginning. 
```
explain MATCH (a:person)<-[e1]-(b:person)-[e2]->(c:person), (a)-[e3]->(c) HINT c JOIN (((a JOIN e1) JOIN b) MULTI_JOIN e2 MULTI_JOIN e3) return *;
```
<img width="1361" alt="Screen Shot 2024-08-04 at 1 36 10 PM" src="https://github.com/user-attachments/assets/0bf40e98-db34-4c5d-95cd-f6c3862b9681">

It's difficult to print the whole plan but the plans look different. I've put parts of the plans I see get printed write above my cursor.

My questions and TODOs are: 
1. Why do we need to express the join with c at all? And if we're going to express it why don't we put it under MULTI_JOIN instead of a JOIN c that's separate. Am I missing something? It looks like the MULTI_JOIN already produces `c` values. 
2. If we should put `c` as a separate JOIN, why is placing `c` at the beginning change the plan?
3. We should explain the documentation what we expect from the "intersected node variable" (in this example `c`) is in the HINT, i.e., where should it be placed?

**Comment by andyfengHKU** [comment]
> Why do we need to express the join with c at all? And if we're going to express it why don't we put it under MULTI_JOIN instead of a JOIN c that's separate. Am I missing something? It looks like the MULTI_JOIN already produces c values

Multi-way join handles edge table only. There is still the need to join node table `c`.

> If we should put c as a separate JOIN, why is placing c at the beginning change the plan?

It's the same reason as explained in #4023. Placing `c` at left/right implies `c` is on probe/build side.

> We should explain the documentation what we expect from the "intersected node variable" (in this example c) is in the HINT, i.e., where should it be placed?

This is essentially the same question as the above one and is explained in the doc.
