### ISSUE TITLE
Document the effect of the order of variables in a single parenthesis in HINT: (x JOIN y) vs (y JOIN x)

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#4023]
### Description

I tried these two HINTs and they return different query plans:
```
explain MATCH (a:person)<-[e1]-(b:person) HINT (a JOIN e1) JOIN b RETURN *;
```
<img width="680" alt="Screen Shot 2024-08-04 at 1 45 07 PM" src="https://github.com/user-attachments/assets/0bdb102a-561a-4fcf-8703-85e4c5d223aa">

vs
```
explain MATCH (a:person)<-[e1]-(b:person) HINT b JOIN (a JOIN e1) RETURN *;
```
<img width="571" alt="Screen Shot 2024-08-04 at 1 45 33 PM" src="https://github.com/user-attachments/assets/52beb272-c850-4b6f-8d36-7897de7092e1">

I'm showing parts of the plans but they look different. I assume the difference is that this effects the build and probe sides and that the left variable/sub-join plan is the probe and the right one is the build.

We should explain the effect of using different order of the variables in the documentation clearly.

**Comment by andyfengHKU** [comment]
Documented.
