### ISSUE TITLE
Bug: READ_ONLY connection fails to read from database after ALTER TABLE is run

### ISSUE THREAD

**Issue by prrao87** [kuzudb/kuzu#4043]
### Kùzu version

0.5.0

### What operating system are you using?

macOS

### What happened?

The scenario under which this bug occurs is as follows:

- Copy from a Pandas DataFrame to a node table
- Alter node table to add a new column
- `LOAD FROM` a Pandas DataFrame and `MERGE` the new column to the existing Kùzu node table
- Open `READ_ONLY` CLI that tries to access the DB

The following error occurs when a `READ_ONLY` CLI is opened:

```
❯ kuzu ./test_db -r        
Error during recovery: Runtime exception: Failed to replay wal record from WAL file. Error: IO exception: Cannot write to file. path: ./test_db/data.kz fileDescriptor: 6 offsetToWrite: 45056 numBytesToWrite: 8 numBytesWritten: -1. Error: Bad file descriptor
```
The same error occurs with Kùzu Explorer as well.

When I change that to a `READ_WRITE` connection, either with the CLI or Kùzu Explorer, there's no error, and the process opens.

### Are there known steps to reproduce?

Consider this CSV file named `product.csv`:
```
"watch",200.0
"shoes",300.0
"wallet",150.0
```
Run this script:
```py
import kuzu
import shutil
import pandas as pd

shutil.rmtree("test_db", ignore_errors=True)
db = kuzu.Database("test_db")
conn = kuzu.Connection(db)

# create a table
conn.execute("CREATE NODE TABLE IF NOT EXISTS Product (item STRING, price INT64, PRIMARY KEY (item))")

df = pd.read_csv("product.csv", header=None, names=["item", "price"])

conn.execute("COPY Product FROM df")

# Alter a table
conn.execute("ALTER TABLE Product ADD has_discount BOOLEAN DEFAULT false")

df = pd.read_csv("product.csv", header=None, names=["item", "price"])
df["has_discount"] = pd.Series([True, False, True])

conn.execute(
    """
    LOAD FROM df
    WITH item, has_discount
    MERGE (p:Product {item: item})
    ON MATCH SET p.has_discount = has_discount
    """
)

res = conn.execute("MATCH (p:Product) RETURN p.*")
print(res.get_as_df())
```
The aim is to first copy from an initial DataFrame into a node table. Then, alter the node table to add a column. Finally, perform some other computations, and scan/merge from another DataFrame to the new node table column.

The script above runs to completion (no issues). The error is only *after* everything is done, when we try to open a `READ_ONLY` connection to the modified database.

**Comment by prrao87** [comment]
@ray6080 by any chance can this feature also go into 0.5.1 if you've figured it out?

**Comment by andyfengHKU** [comment]
I think @ray6080 is on this right now. This is part of our plan for the bug fix release

**Comment by ray6080** [comment]
hi @prrao87 , can u give a try on the latest master or branch 0.5.1 when u got a chance? This should work now.

**Comment by prrao87** [comment]
Yup, this works on dev and master build. Thanks!
