### ISSUE TITLE
Bug: Unable to prepare statement creating a node with variable for node type 

### ISSUE THREAD

**Issue by pdlug** [kuzudb/kuzu#4048]
### Kùzu version

v0.5.0

### What operating system are you using?

MacOS

### What happened?

I'm using Kuzu 0.5.0 and tried to prepare a statement with a variable for the node type. It fails with the error below. If I hard code the node type instead of using the `$type` variable it works but won't be usable for my use case.

```typescript
const nodeStmt = await conn.prepare(`CREATE (n:$type {id: $id, label: $label})`);
```

```
node_modules/.pnpm/kuzu@0.5.0/node_modules/kuzu/connection.js:103
        return reject(new Error(preparedStatement.getErrorMessage()));
                      ^

Error: Parser exception: Invalid input <CREATE (n:$>: expected rule oC_SingleQuery (line: 1, offset: 10)
"CREATE (n:$type {id: $id, label: $label})"
           ^
    at node_modules/.pnpm/kuzu@0.5.0/node_modules/kuzu/connection.js:103:23
    at new Promise (<anonymous>)
```

This also fails using variables for the nodes in a `MATCH` statement as well. In this case it will fail on the node type variables and edge label variables so neither seems to be supported. 

```typescript
  const edgeStmt = await conn.prepare(`
    MATCH (n1:$source_type), (n2:$target_type)
    WHERE n1.id = $source AND n2.id = $target
    MERGE (n1)-[:$edge_label]->(n2)
  `);
```

**Comment by andyfengHKU** [comment]
Hi @pdlug,

Thanks for the report. Though according to openCypher9 grammar specification, parameter is not supported in node/edge label. So this is expected behaviour.

I wonder if u have seen other system allowing this behaviour?

**Comment by prrao87** [comment]
Hi @pdlug, in Python it's possible to work around this issue by using string interpolation (f-strings) so that the table name/label can be passed dynamically. I presume that should be doable in Node.js too? Passing labels as parameters isn't valid as per openCypher, so this is something that's normally dealt with on the application language side.

**Comment by pdlug** [comment]
Ah I see, yeah it's no problem doing this in Node.js it just means I have to prepare a statement per type. I didn't realize dynamic labels weren't supported in openCypher
