### ISSUE TITLE
Feature:  Add support for disabling threading for emscripten and pyodide

### ISSUE THREAD

**Issue by DylanShang** [kuzudb/kuzu#4107]
### API

C++

### Description

Hi,
I think we need to add an option `DISABLE_THREADING` for compiling and build a version without threading

Reason：
- Pyodide only support module without threading which compiled by emscripten so far
- Need to enable cross origin isolation if threading wasm used

Related Link:
https://github.com/apache/arrow/pull/35471

**Comment by mewim** [comment]
Resolved in https://github.com/kuzudb/kuzu/pull/4399
