### ISSUE TITLE
Bug: Struct casting issues

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#4155]
### Kùzu version

master

### What operating system are you using?

MAC M1

### What happened?

1. Cast struct type to another struct type doesn't change the field names:
Query: `return cast({'a': 12, 'b': 24} as struct(c int64, d int64))`
Result: `{a: 12, b: 24}` instead of `{c: 12, d: 24}`

2. Cast struct type to another struct type with compatiable field type still throws exception:
Query: `return cast({'a': 12, 'b': 24} as struct(c uint32, d int64))`
Error: `Conversion exception: Unsupported casting function from STRUCT(a INT64, b INT64) to STRUCT(c UINT32, d INT64).`

### Are there known steps to reproduce?

As described.

**Comment by SterlingT3485** [comment]
is this fixed? I could take a look at it if necessary

**Comment by SterlingT3485** [comment]
is still there, interesting thing is that these two queries goes on two different code path

**Comment by SterlingT3485** [comment]
according to #4545 , the second behaviour is expected, not a bug.
