### ISSUE TITLE
Bug: unable to add edges while using Kuzu's LlamaIndex PropertyGraphIndex integration

### ISSUE THREAD

**Issue by aayan636** [kuzudb/kuzu#4208]
### Kùzu version

v0.6.0

### What operating system are you using?

MacOS 14.4.1 (23E224)

### What happened?

I was creating a graph using LlamaIndex's `PropertyGraphIndex` integration with Kuzu. I was trying to add nodes and edges to the graph (not using `PropertyGraphIndex.from_documents`, but by manually creating nodes/relations and upserting them to the graph). I was able to add nodes to the graph, but none of the edges were showing up in the graph. Upon inspecting the code inside `KuzuPropertyGraphStore.upsert_relations`:

```py
def upsert_relations(self, relations: List[Relation]) -> None:
        for rel in relations:
            if self.has_structured_schema:
                src, _, dst = utils.lookup_relation(rel.label, self.relationship_schema)
            else:
                src, dst = "Entity", "Entity"

            rel_tbl_name = f"LINKS_{src}_{dst}"
            self.connection.execute(
                f"""
                MATCH (a:{src} {{id: $source_id}}),
                        (b:{dst} {{id: $target_id}}),
                        (c:Chunk {{id: $triplet_source_id}})
                MERGE (a)-[r:{rel_tbl_name} {{label: $label}}]->(b)
                    SET r.triplet_source_id = $triplet_source_id
                MERGE (c)-[:LINKS_Chunk_{src} {{label: "MENTIONS"}}]->(a)
                MERGE (c)-[:LINKS_Chunk_{dst} {{label: "MENTIONS"}}]->(b)
                """,
                parameters={
                    "source_id": rel.source_id,
                    "target_id": rel.target_id,
                    "triplet_source_id": rel.properties.get("triplet_source_id"),
                    "label": rel.label,
                },
            )
```

 I found that the code to add edges relies on the fact that there should be `Chunk` nodes inserted into the graph, and if they do not exist (which is the situation for me) then the edge does not get added. 
 
 Ideally, in case Chunk nodes are not found but we do supply nodes between which we would like an edge to be created, it should not be conditional on a `Chunk` node also being present.

### Are there known steps to reproduce?

A minimal example which should be enough to reproduce the issue:
```py
import kuzu
from llama_index.llms.openai import OpenAI
from llama_index.core.graph_stores import EntityNode, Relation

db = kuzu.Database("/tmp/demo_db")
graph_store = KuzuPropertyGraphStore(db=db)

index = PropertyGraphIndex.from_existing(property_graph_store=kuzu_property_graph_store,llm=OpenAI(....<params>....))
graph_store.upsert_nodes([EntityNode(name="node1", label="Entity", properties={})])
graph_store.upsert_nodes([EntityNode(name="node2", label="Entity", properties={})])
graph_store.upsert_relations([Relation(source_id="node1", target_id="node2", label="Relation", properties={})])
```
After running the the code, use the Kuzu Explorer and point it to `tmp/demo_db` to see the graph. the query `MATCH(n) RETURN n` will return all nodes, but `MATCH p=()-[]-() RETURN p`returns no nodes.

**Comment by prrao87** [comment]
Hi @aayan636 thanks for reporting - we'll take a look at this at the earliest and get back with a fix.

**Comment by prrao87** [comment]
Hi @aayan636, the issue should be more or less resolved as per https://github.com/run-llama/llama_index/pull/15889. I'm not sure how soon they'll merge this and when it'll be available on the LlamaHub package index for you to test this, but you can check out the LlamaIndex repo on your end and run your code by importing the local modules in the interim.

```py
import sys
sys.path.append("/Users/prrao/code/llama_index/llama-index-integrations/graph_stores/llama-index-graph-stores-kuzu/llama_index/graph_stores/kuzu/")
from kuzu_property_graph import KuzuPropertyGraphStore
```
You might need to resolve the `utils.py` path as well to run this locally, as the structure of the code is designed to work as a package.

Hope this works!

**Comment by aayan636** [comment]
Hi @prrao87, thank you so much for resolving this quickly. I'll check the fix locally on my end and will update the ticket once I have verified the patch works for me.

**Comment by logan-markewich** [comment]
Merged 👍🏻 Should be published shortly

**Comment by prrao87** [comment]
Great, thanks, Logan!
