### ISSUE TITLE
Keep a version number for the serialization format

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#422]
Currently if we try to load a serialized graph that is stale or not exactly in the format the system expects, during starting up of a shell (and later other applications) will hang. We should instead have a versioning system for our serialization formats. Ideally, the version numbers would be automatically generated, instead of us writing a manual version number each time we change the loader but I don't know if this is possible/easy to do.  And then during shell startup, we should check if the version of the serialized db is what the system expects and if not should error (instead of hanging).

**Comment by acquamarin** [comment]
Solved in #1436
