### ISSUE TITLE
Bug: ldbc sf01 deleteComment test fail randomly

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu#4271]
### Kùzu version

master

### What happened?

See log here https://github.com/kuzudb/kuzu/actions/runs/10858946549/job/30138088819

**Comment by benjaminwinger** [comment]
I took a look at this and while I don't fully understand the issue, I did find that it was consistently reproduce-able in single-threaded mode (always with one value remaining after the deletion), so we can rule out data races. I'm not sure why the results vary when more threads are added (maybe there's also a data race...).
