### ISSUE TITLE
Several objects are deconstructed when exiting from shell (Possible memory leak)

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#437]
I put empty deconstructors with cout statements to ResultCollector and AggregationSharedState. And I noticed that when I exit the shell (press cntr + C), these are deconstructors are being called. 

You can replicate by putting deconstructors, .e.g., 
    ~AggregationSharedState() { cout << "AggregationSharedState is deconstructed." << endl; }, into these classes with couts.

This might be a memory leak or the shell might be keeping a pointer to some object that keeps a pointer to these (and possibly other classes. I did not put a decontructor with a cout statement to other classes.) We should rule out that we have a memory leak.

**Comment by MSebanc** [comment]
I was unable to replicate the deconstructors being called on shell exit and ASAN validated that are no memory leaks, so the issue seems to be resolved.
