### ISSUE TITLE
JSON Copy From Relationship Table

### ISSUE THREAD

**Issue by SterlingT3485** [kuzudb/kuzu#4402]
### Description

We seem to be lack of the documentation on importing from JSON to relationship table:
https://docs.kuzudb.com/import/copy-from-json/

We have these documentation for CSV copy from:
https://docs.kuzudb.com/import/csv/
```
Import to relationship table

When loading into a relationship table, Kùzu assumes the first two columns in the file are:

    FROM Node Column: The primary key of the FROM nodes.
    TO Node Column: The primary key of the TO nodes.

The rest of the columns correspond to relationship properties.

Create a relationship table Follows using the following Cypher query:
```

We may need to add something similar to JSON as well.

**Comment by prrao87** [comment]
This has been addressed in https://github.com/kuzudb/kuzu-docs/pull/283

The documentation page now shows this [here](https://docs.kuzudb.com/extensions/json/#copy-to-relationship-tables), where we explain the purpose of the `"from"` and `"to"` keys.
