### ISSUE TITLE
Bug: Invalid application of 'sizeof' to an incomplete type 'kuzu::storage::NullChunkDat

### ISSUE THREAD

**Issue by b3n-h4il** [kuzudb/kuzu#4477]
### Kùzu version

v0.6.1

### What operating system are you using?

openSUSE Tumbleweed

### What happened?

Following the documentation on "Creating your first Graph", and using the C++ client, instead of creating an on-disk database, I got an error about the included header "kuzu.hpp" that keeps the program from compiling: ` error: invalid application of 'sizeof' to an incomplete type 'kuzu::storage::NullChunkDat`. I'm using Clang 18.1.8. My editor's autocomplete can see the Kùzu header file, but once it's included, the error appears and the compilation fails. I have also tried using the 0.6.0 version, but to no avail. 
The docs say that the Go client library is a wrapper around the C library; it's possible to call Go from C++, so I just gave it a try (not that the wrapper part matters as a motivation for me to give the Go client a try) and I could create my first graph. But when I tried to use the C library, I got some errors about type incompatibility. 

### Are there known steps to reproduce?

Just include the header file and .so file in a C++ program. That's the only thing I did.

**Comment by mewim** [comment]
I have created a bundled zip of the test project:
[test.zip](https://github.com/user-attachments/files/17648102/test.zip)

Can you try this one and run the command to see if it works for you?

**Comment by b3n-h4il** [comment]
Thank you for your very fast answer. It seems Kùzu is not at fautl, my knowledge of the build system I'm using is. 
I used the zip file and the commands you wrote, and everything works fine, I'm having trouble configuring the build to use the files correctly.

**Comment by b3n-h4il** [comment]
I'm using Kùzu in a personal project, and my build system is Build2. Now, I don't think Build2 is the problem (and it's already been prooven that it's not Kùzu either), but I'm able to use external libraries in my project and Build2 detects and uses them just fine. With Kùzu files however I'm getting linker errors. Well, going to give the docs another read.

**Comment by boris-kolpackov** [comment]
> env LIBRARY_PATH=. LD_LIBRARY_PATH=. clang++ main.cpp -std=c++2a -lkuzu -lpthread

Try with `c++2b`. I get the above-mentioned error with Clang 18. I think in some later standard `std::unique_ptr` has tighter requirements on the pointed-to type being complete. Note that this is not specific to Clang/libstdc++, I get the same with `-stdlib=libc++`.

**Comment by b3n-h4il** [comment]
After I changed the C++ standard to c++2a the compilation works, what @boris-kolpackov said is right. The settings I have in my Build2 project are also correct. The issue was being caused by a difference in the C++ standards, Clang was using it's std=c++26 or C++2c. With the flag c++2a, the example code uses C++20
