### ISSUE TITLE
Bug: Creating a new node after exporting and importing throws an exception.

### ISSUE THREAD

**Issue by jamesblissett** [kuzudb/kuzu#4631]
### Kùzu version

0.7.0

### What operating system are you using?

Arch Linux (Linux 6.12.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:31:57 +0000 x86_64 unknown unknown GNU/Linux)

### What happened?

Runtime exception when adding a new node on exported database.
Error: Runtime exception: Found duplicated primary key value 1, which violates the uniqueness constraint of the primary key column.

See reproduction steps.

Thanks for kuzu and for making it open source.

### Are there known steps to reproduce?

- Create a new database
- Create a new table with a serial primary key
    ```
    create node table person(id serial, name string, primary key (id));
    ```
- Add at least two nodes to the table.
    ```
    merge (p:person { name: '_' }) set p.name = 'person 1';
    merge (p:person { name: '_' }) set p.name = 'person 2';
    ```
- Export the database.
    ```
    export database 'some-path' (format='parquet');
    ```
- Start from a fresh database and import the data from the old one.
    ```
    import database 'some-path';
    ```
- Try to add a new node to the table.
    ```
    merge (p:person { name: '_' }) set p.name = 'person 3';
    ```
- Exception.
    ```
    Error: Runtime exception: Found duplicated primary key value 1, which violates the uniqueness constraint of the primary key column.
    ```
- Expected behaviour is for the new node to be added without an exception being thrown.

**Comment by ray6080** [comment]
Thanks @jamesblissett . We will take a look into it soon.

**Comment by ray6080** [comment]
hi

**Comment by jamesblissett** [comment]
Just tried it out, works great. Thanks for the quick fix!
