### ISSUE TITLE
Parallel distinct aggregate

### ISSUE THREAD

**Issue by andyfengHKU** [kuzudb/kuzu#483]
Currently, distinct aggregate is only executed with single thread because it's unsafe to perform thread-local aggregation without first taking distinct values. Imagine the following example of calculating COUNT(DISTINCT a.age) with 2 threads. Both threads t1 and t2 get input 20. 20 is a distinct value in their own thread so both threads have COUNT = 1. However, when we combine the state between t1 and t2, we lose track of input vectors and thus lead to the wrong aggregate value.

## Solution
A possible solution is to first calculate thread-local distinct values in parallel which is the same as the current implementation of DISTINCT. Then during task finalize, we first obtain global distinct values by merging all thread-local distinct hash tables. Then we loop through the global distinct hash table and update aggregate states for each row.

**Comment by ray6080** [comment]
Moved as an internal issue.
