### ISSUE TITLE
Nulls and Unstructured values in the LIST

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu#532]
Null values in the LIST are not handled in both the storage and query processor sides.
One way to handle NULLs inside the query processor is to re-use ValueVector for storing LIST values recursively. The benefit of this approach is that first, we can directly re-use the null mask in ValueVector, and secondly, we can simplify the processing of sub-lists.

**Comment by andyfengHKU** [comment]
we no longer support unstructured value
