### ISSUE TITLE
VarLenExtend pattern matching front end

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#540]
We should allow the user to omit the lower bound/ upper bound of the variable length extend query.
If the user omit the lower bound of the query:
eg. (a)-[*..5]->(b), the front end should put 1 as the lower bound.
If the user omit the upper bound of the query:
eg. (a)-[*3..]->(b), the front end should put MAX_VAR_LENGTH_EXTEND_PATH as the upper bound.

Neo4j documentation for varLenExtend pattern:
https://neo4j.com/docs/cypher-manual/current/syntax/patterns/

**Comment by andyfengHKU** [comment]
I think we should just ask user to always give us lowerBound and upperBound. 

If lowerBound is omitted, it's unclear whether our default is 0 or 1.
If upperBound is omitted, it usually means Kleene star which we cannot support with walk semantic. 

So I think we won't solve this issue for a very very long time. Let me know if we should just close it.

**Comment by jkanche** [comment]
I would love to omit the upper bound on the queries to traverse the subgraph and collect all descendants with a specific relationship. 

> If the user omit the upper bound of the query:
> eg. (a)-[*3..]->(b), the front end should put MAX_VAR_LENGTH_EXTEND_PATH as the upper bound.

**Comment by andyfengHKU** [comment]
Solved in PR #2041
