### ISSUE TITLE
Node degree function

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#554]
I see many users of GDBMSs and in particular Cypher want to do query processing ignoring nodes with high degrees. We need a way for users to specify this. Queries can look like:
MATCH (a)-[:friend]->(b)
WHERE a.degree (or degree(a)) < 10
RETURN b.

We can add a new clause to our version of Cypher or probably more easily a node function that computes this. This information is stored in our list indexes, so we can compute this quickly.

I'm also open to moving to phase 1. My guess is that it is actually a very useful feature.

**Comment by andyfengHKU** [comment]
I no longer think this is necessary given we need to config the direction & relationship labels in the function. It can be done by 
```
MATCH (a)
RETURN COUNT { MATCH (a)-[]->(b) } AS degree.
```
