### ISSUE TITLE
Add List-type literal and parameter

### ISSUE THREAD

**Issue by andyfengHKU** [kuzudb/kuzu#557]
Once list type and related functions are properly supported in the system, we should also add list literal and parameter for the prepared statement.

**Comment by acquamarin** [comment]
We don't plan to support list parameter at this stage.
Duckdb's c++ api doesn't support list parameter, however their python api supports list parameter:
Example:
```
import duckdb

cursor = duckdb.connect()
cursor.execute("""
    prepare v1 as 
        select list_concat(?, [2])""")
print(cursor.execute("execute v1([1,5,3])").fetchall())
```

**Comment by andyfengHKU** [comment]
We also now support list type as parameter on the python side. 

C++ is hard to support. I would try to support with cypher statement instead
```
PREPARE RETURN $1 AS p_statement
EXECUTE p_statement([1,2,3])
```
