### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#560]
This is going to be an ongoing issue with links to other issues we will open up to implement transactions in the system based on this ongoing design [document](https://docs.google.com/document/d/1iwsjDx2ZTnN9J6OF3Pn6C9SP7Vs0upmPHis8qG-GKY4/edit?usp=sharing).

PR Groups:

- [x] Basic Transaction Manager and Mechanism for Multiple Queries through a Connection (initially read only): 
- Assignee: Xiyang/Semih
  - [x] Transaction and TransactionManager in the backend:
  - [x] Mark Transactions READ-ONLY or WRITING.
  - [x] Give an increasing number of TrxIDs to Writers and a Read Timestamp to all transactions. Start Timestamp? 
  - [x] Do not allow multiple WRITING Transactions to enter the system.
  - [x] Add commit/rollback/checkpoint functions.
  - [x] Frontend Support for Begin/Commit/Rollback Transaction (Xiyang)
- [x] Set Fixed Length Node Properties:
  - [x] Implement MVD in the FileHandles by PageVersionInfo.
  - [x] Cypher SET command and an operator SetNodeProperty and Sink operator to accumulate a factorized table for the previous pipeline.
  - [x] Have a mechanism to remove the PageLocksAndVersionsPerPageGroup's after checkpointing. One simple solution is, after  checkpoint/rollback,  loop over each storage structure and ask them to clear their PageVersionInfos.
  - [x] WAL log records for updates and pages.
  - [x] Initial infrastructure for:
      - [x] committing and checkpointing and rollbacking
      - [x] recovery.
  - [x] Test for failures during recovery: Not sure what to do here because hopefully this should never happen and there does not seem to have a fix. Marking this as done for now.
- [x] SET Fixed Length Node Properties to null (Xiyang). This is a variant of Cypher REMOVE clause.
- [ ] SET Variable Length Node Properties 
  - [x] Implementation of versioned overflow_pages (Semih):
  - [ ] Update overflow files to keep track of and reuse empty slots. (Guodong/Semih)
  - [ ] Loader merge all overflow files into a single overflow file (Guodong)
- [x] DELETE nodes
  - [x] DeletedNodeInfo
  - [x] Scans that check deleted nodes.
  - [x] Truncation of node files.
- [x] INSERT Singleton Nodes:
  - [x] Node ID recycling
- [x] Coalescing List Files under .lists: We need modification of .header, .metadata, .chunks.f1, .chunks.f2, .largeLists.f1, .largeLists.f2, .lists to be all stored in the same file. This will allow us to more easily log these pages. (Guodong)
- [x] SET/REMOVE Unstructured node properties (looks easier than updates to adjacency lists)
  - [x] DeltaUnstructuredNodePropertiesStore
  - [x] Logic to construct new ListsHeaders/Metadata and find the differences in the .list pages (hopefully reusing existing pages) upon commit. This may require also keeping track of free lists.
  - [ ] Insert a new unstructured property as part of a create statement
  - [ ] Frontend support for unstructured property updates.
- [ ] SET/REMOVE edge properties (looks easier than inserts/deletes to adjacency lists) (Phase 2)
- [x] INSERT New Edges (Phase 1)
   - [x] Backend (Ziyi)
   - [x] Frontend (Xiyang)  
- [ ] DELETE New Edges (Phase 2)
- [x] RelUpdateStore optimization
- Assignee: Ziyi
   - [x] Commiting largeList optimization #814

**Comment by ray6080** [comment]
Most features in this issue are done, except for tracking unused pages, which is referenced in our node group issue #1474 as free space management. Unstructured node properties is no longer supported. The design for string has changed, so items on overflow file are no longer relevant.
