### ISSUE TITLE
OrderBy optimizations

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#632]
Here is a list of optimizations that duckdb does on orderBy operators:
- [ ] The storage should store the value ranges of an orderByColumn. Then the orderBy operators can use the value range information to choose an optimal encoding datatype for that column.
- [ ] The storage should store whether a certain column has null values or not. If that column doesn't have null values, the orderBy doesn't need to encode the nullByte.
- [ ] OrderBy binary string encoding size alignment.(maybe 8 bytes alignment as duckdb).
- [ ] Opimize the skip operator after operator to use limit operator

**Comment by ray6080** [comment]
Moved to internal.
