### ISSUE TITLE
Enhance InMemDiskArrayBuilder with a to simplify population of lists in_mem_node_builder/in_mem_rel_builder

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#699]
Currently InMemNodeBuilder uses InMemUnstructuredLists unstrPropertyLists, which uses its own structures to populate the actual lists of lists, such as InMemFile. This is not true for ListMetadata and Lists, which uses InMemDiskArray. If we switch to using DiskArray and InMemDiskArrrayBuilder for the actual lists too some of the loading code can simplify. In particular, parts of code that are populating InMemFile work at a low-level abstraction, where they figure out where the actual page locations they need to update. Instead, if we worked at the abstraction of an array or vector, which can be supported by DiskArray, and had utility functions, such as copy(uint64_t beginOffset, uint8_t* from, uint64 numBytes) or push_back<T>(element), where T is the type of DiskArray etc, and the DiskArrayBuilder figured out exactly which pages to update could be much simpler.

As a concrete example, at a high level, the InMemNodeBuilder::putUnstrPropsOfALineToLists code, reads a line of csv, parses each unstructured property and copies to a particular offset in an array. But the code looks lower level and the following function calls happen
```
1. InMemNodeBuilder::putUnstrPropsOfALineToLists: unstrPropertyLists->setUnstructuredElement(...)
2. InMemUnstructuredLists::setUnstructuredElement:  InMemUnstructuredLists::setComponentOfUnstrProperty(...)
3. Inside InMemUnstructuredLists::setComponentOfUnstrProperty, we find the in-mem page or pages that need to be updated etc.
``` 
All this complexity can be hidden if we make lists to use DiskArrays enhance InMemDiskArrayBuilder to have several utility functions that automatically writes the given data to the correct in-memory locations and are saved to disk correctly as well.

**Comment by ray6080** [comment]
No longer relevant.
