### ISSUE TITLE
DiskArray Multi Element Updates

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#716]
Currently DiskArray supports update and pushBack elements that take in single elements. This can be quite slow when updating many elements (e.g., when inserting a batch of updates). We need faster support for updating and inserting a batch of elements in DiskArray level.

Once this feature is implemented to DiskArray, we should change our update functions (e.g., CSR reconstruction algorithms) to use it when possible.

**Comment by ray6080** [comment]
This is stale now.
