### ISSUE TITLE
Make InMemDiskArray use BufferManager for in-memory Array Pages

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#717]
Currently InMemDiskArray manages the ArrayPages directly through the OS memory. This allows faster access to these pages, but we can achieve something similar by using BM but always pinning in-memory pages. This has the following benefit: During updates, we currently create 3 versions of pages for any storage structure that uses InMemDiskArray: 1 in the InMemDiskArray, 2 in the BufferManager when calling StorageStructureUtils::createWALVersionOfPageIfNecessary(). This is so, because we have utility functions like createWALVersionOfPageIfNecessary, which were developed
for updating Columns transactionally and we wanted to reuse them. iIf we make InMemDiskArray use BufferManager, we would solve this redundancy.

InMemDiskArray also contains some logic to either read values directly from in-memory array page or BM, which might simplify if all pages were BM-backed.

In general, we should consider having a BufferPool for in-memory always pinned pages, which in-memory implementations of storage structures can use to avoid any pins.

**Comment by ray6080** [comment]
This is no longer relevant.
