### ISSUE TITLE
Make Overflow Files manage its free space

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#720]
We currently have 3 problems with how we manage OverflowFiles that leak disk space.

- [ ] Serializing nextBytePosToWriteTo: OverflowFile keeps a nextBytePosToWriteTo to decide the free space to allocate for the next large strings and lists. We do not serialize this. Therefore each time the system starts up this is set to the beginning of the "next page" on the disk, so we leak whatever space that was available on the last overflow page.
- [x] Rolling back nextBytePosToWriteTo: Currently when a write transactions starts and starts updating or inserting strings or lists, we start allocating new positions on the OverflowFile pages and update the `nextBytePosToWriteTo` pointer in the OverflowFile. However, if the transaction rollsback, we do not rollback this change. So all of the tentative updates that were performed occupy space. This one should be easy to fix, if during rollback, the WALReplayer calls a rollbackInMemoryOverflowFile() function that rolls back the pointer. (solved in https://github.com/graphflowdb/graphflowdb/pull/729)
- [ ] When strings are updated or deleted, their space is never reclaimed. We need a mechanism to keep track of the empty spaces and reuse them. We can do this by changing how we implement OverflowFiles as follows: We keep track of multiple DiskArrays that are responsible for keeping strings/lists of exponentially increasing sizes. That is we have a DiskArray that stores strings of size up to 16. Another one upto 32, another one upto 64, etc. up to some maximum limit. For each of these DiskArray we also have a separate DiskArray that keeps track of the free locations on these lists. Hopefully free lists should be very small. Then we allocate free spaces from the DiskArray. Doing this change would also reuse DiskArray update features, which should simplify atomically updating overflow files.

There is also a very minor bug reported here about a possible leak of page 0 of the overflow files: https://github.com/graphflowdb/graphflowdb/issues/725.

**Comment by ray6080** [comment]
Close this issue as it is stale now. The design should be managing free space for data file with consideration of compression and node group design.
