### ISSUE TITLE
OverflowFile Page Leak

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#725]
I am noticing that if I construct an unstructured property lists with no long strings (or lists) in it, then the .ovf that is  saved with the list still has 1 page. This I tests by adding a cout to the OverflowFile's constructor:
```
    OverflowFile(const StorageStructureIDAndFName& storageStructureIDAndFNameOfMainDBFile,
        BufferManager& bufferManager, bool isInMemory, WAL* wal)
        : StorageStructure(
              constructOverflowStorageStructureIDAndFName(storageStructureIDAndFNameOfMainDBFile),
              bufferManager, isInMemory, wal) {
        cout << "Overflow file numPages: " << fileHandle.getNumPages() << endl;
        nextBytePosToWriteTo = fileHandle.getNumPages() * DEFAULT_PAGE_SIZE;
    }
```
 I also tested with cases where I put 7 pages worth of long strings and the cout is 8 or 4 pages and the cout is 5. I didn't dig deeper but I suspect that we might be just not writing anything useful to the first page of the .ovf files because of a  minor bug in the loader.

**Comment by ray6080** [comment]
This is no longer relevant. We are moving away from overflow files.
