### ISSUE TITLE
Maintaining Free Pages in Lists and Possible General Solution to Maintaining Free Pages in Storage Structures

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#731]
Currently the page lists of chunks cannot shrink. That is suppose we have a non-empty UnstructuredPropertyLists and with some data and we remove all unstructured properties in it. Then although the headers are all 0 now, the pages that were in the page list of any non-empty chunk are not reclaimed. That is, if a chunk has used some number of list pages and then "shrinks", those pages remain "reserved" for the chunk and become useless. We need a mechanism to reclaim them and when we need more pages from .lists, when calling VersionedFileHandle::addNewPage(), we should reuse those empty pages. 

This may require some logic outside of VersionedFileHandle and directly in Lists or a new storage structure called FreePages, which can be put into other StorageStructures. Or this may even be a core piece of any StorageStructure, i.e., be implemented at the StorageStructure level. It's unclear what is more appropriate.

**Comment by ray6080** [comment]
Closing this issue as the description is stale now, though the free space management should be handled still.
