### ISSUE TITLE
Replace bufferManager and memoryManager with database in execution context.

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#755]
Currently, we store:

1. uint64_t numThreads;
2. Profiler* profiler;
3. MemoryManager* memoryManager;
4. BufferManager* bufferManager;
5. Transaction* transaction;
In the execution context.

Ideally,. we should replace memory manager and bufferManager with database since the copyRelCSV and copyNodeCSV operators need the nodeStore, relStore from the database.

**Comment by andyfengHKU** [comment]
Done in #3121. We don't replace with Database but with ClientContext
