### ISSUE TITLE
String and OverflowFile Enhancements

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#980]
- [ ] Coalesce all overflow files into a single heap file
- [ ] Overflow file free space: (https://github.com/graphflowdb/graphflowdb/issues/725), (https://github.com/graphflowdb/graphflowdb/issues/720)
- [x] UTF-8 char set
- [ ] Support for arbitrarily large strings
- [ ] String dictionary compression

**Comment by ray6080** [comment]
This is stale now, as we are moving away from overflow files.
